#9978: Add 360 photo support with Mapillary
geosolutions-it/MapStore2 pull request #10027
Opened 2024-03-06 09:04 UTC by mahmoudadel54

## Description
- adding the mapillary viewer for 360 photo support beside Google amd cyclemedia
- handle view custom 360 photos into mapillary viewer using GeoJSONDataProvider
- handle view the custom images in 2d and 3d modes
- install mapillary-js npm package
- edit VectorLayer to enable add layer features via geojson url in 2d + 3d views
- adding unit tests for mapillary

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#9978 

**What is the current behavior?**
#9978 

**What is the new behavior?**
360 Photo support with mapillary viewer is added. It currently is to view only the custom 360 images provided by client not the default mapillary images. User can add the ApiURL parameter into cfg of the streetView plugin in the created context.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
360 Photo support for mapillary is added just for the custom 360 images that can be provided by the client not the default mapillary provider.
- Adding the default mapillary provider is applicable for 2D by adding vector tile support into openLayers [it is not supported in MS] and it needs investigation to handle it in 3D as there is no straight forward support for vector tile layers into Cesium.
- I have added a custom logic to enable vector layer to get url of a geojson file to load its features into the layer for openLayers and Cesium as well.

2024-03-13 09:37 UTC, allyoucanmap requested changes

2024-03-13 09:37 UTC, allyoucanmap commented on web/client/components/map/openlayers/Layer.jsx
> +            }
Please remove this changes, if we want to manage a zoom to we should use a zoomTo action in the mapillary viewer component or related files

2024-03-14 07:38 UTC, mahmoudadel54 commented on web/client/plugins/StreetView/epics/streetView.js
> +            }
what do you mean with 'if the service is not available' ? @allyoucanmap

2024-03-18 09:28 UTC, offtherailz commented on web/client/plugins/StreetView/StreetView.jsx
> +            disablePluginIf: "{state('mapType') === 'leaflet' || (state('mapType') === 'cesium' && (state('streetView')?.configuration?.provider !== 'mapillary'))}"
Did you solved at the end, with a wrapper?

2024-04-16 09:44 UTC, tdipisa approved these changes

2024-04-16 09:45 UTC, merged

2024-04-16 09:45 UTC, tdipisa commented
@ElenaGallo just merged this. Please test this in DEV asap.