Update User Guide - Street Smart API support
geosolutions-it/MapStore2 pull request #10021
Opened 2024-03-05 11:31 UTC by ElenaGallo

## Description

Add Cyclomedia tool on [Street View](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/street-view/) section

2024-03-12 11:52 UTC, tdipisa requested changes

2024-03-12 15:06 UTC, ElenaGallo commented on docs/user-guide/street-view.md
> +* Open the **Overlays** pop-up, through the <img src="../img/button/overlays-button.jpg" class="ms-docbutton"/> button, to: view and enable/disable the layers present in the view in the **Layers** ta
* Open the **Overlays** pop-up, through the <img src="../img/button/overlays-button.jpg" class="ms-docbutton"/> button, to:

* View and enable/disable the layers present in the view in the **Layers** tab

* Enable/disable the *Show Mouse position* and the *Show Compass* in the **Viewer** tab

2024-03-13 16:10 UTC, tdipisa requested changes

2024-03-13 16:10 UTC, tdipisa commented on docs/user-guide/street-view.md
> +    The **[Cyclomedia Street Smart](https://www.cyclomedia.com/en/street-smart)** provided can be configured on the *Street View* plugin as documented [here](https://mapstore.geosolutionsgroup.com/ma
```suggestion
    The **[Cyclomedia Street Smart](https://www.cyclomedia.com/en/street-smart)** provider can be configured on the *Street View* plugin as documented [here](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.StreetView)
```

2024-03-13 16:10 UTC, tdipisa commented on docs/user-guide/street-view.md
> +    The credentials are necessary to visualize the street layer while the usual authkey is needed in plugin config to interact with the street smart APIs (see plugin config page [here](https://dev-ma
```suggestion
    The credentials are necessary to visualize the street layer while the usual authkey is needed in plugin config to interact with the street smart APIs (see plugin config page [here](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.StreetView))
```

2024-03-13 16:10 UTC, tdipisa approved these changes

2024-03-13 16:13 UTC, tdipisa commented
@ElenaGallo please backport to 2024.01.xx. Thank you

2024-03-13 16:19 UTC, merged