Generic OIDC provider support
geosolutions-it/MapStore2 pull request #10152
Opened 2024-04-03 15:53 UTC by offtherailz

## Description

This PR configures the integration of a generic OIDC provider (provided by https://github.com/geosolutions-it/geostore/pull/330 ) in MapStore, documenting it.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

#10151

**What is the new behavior?**

#10151 integrated (logout still to be impelmented on GeoStore, so not closing it). 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-05-15 16:29 UTC, offtherailz commented on docs/developer-guide/integrations/users/openId.md
> +- `oidcOAuth2Config.groupsClaim`: (*optional*) the group claims. If a claim contains groups, you can map them to MapStore groups. If the claim is not present, no group will be assigned (except the de
```suggestion
- `oidcOAuth2Config.groupsClaim`: (*optional*) the group claims. If a claim contains groups, you can map them to MapStore groups. If the claim is not present, no group will be assigned (except the default `everyone` group).
- `oidcOAuth2Config.globalLogoutEnabled`: (*optional*): if true (and the server supports it) invokes global logout on MapStore logout

```

2024-05-15 16:31 UTC, offtherailz commented
@tdipisa this is ready to review now. 
This should be tested with Azure @afabiani

2024-05-16 09:19 UTC, tdipisa requested changes
@offtherailz as discussed, I would like to add an entry point section in the documentation to provide an overall picture of available capabilities of the current OpenID support in MS across different OpenID clients / configuration methodologies we have (using old clients and the new one) such as:

- Available clients and what they can do 
- Which limits they have 
- How them can be combined to provide multiple auths
- Future steps also in term of deprecation of the old clients

I would like to provide only a brief preliminary indication of the above to allow readers to learn the details in the relevant sections of the documentation.

2024-05-16 09:32 UTC, offtherailz commented on docs/developer-guide/integrations/users/openId.md
> +        "authenticationProviders" [
```suggestion
        "authenticationProviders": [
```

2024-05-17 15:06 UTC, tdipisa commented on docs/developer-guide/integrations/users/openId.md
>  - Open Google developer console and, from credentials section, create a new credential of type **Oauth client ID**
```suggestion
- Open the Google developer console and, from credentials section, create a new credential of type **Oauth client ID**
```

2024-05-17 15:08 UTC, tdipisa commented on docs/developer-guide/integrations/users/openId.md
> +- create/edit `mapstore-ovr.properties` file (in data-dir or class path) to configure the google OpenID integration by inserting in particular the `clientId` and `clientSecret` obtained from Google C
```suggestion
- create/edit the `mapstore-ovr.properties` file (in data-dir or class path) to configure the Google OpenID integration by inserting in particular the `clientId` and the `clientSecret` obtained from Google Console. You have also to set the `autoCreateUser` to `true` to create the user if not present in the MapStore database:
```

2024-05-17 15:14 UTC, tdipisa commented on docs/developer-guide/mapstore-migration-guide.md
> +In order to have this feature working, you need to update in your project the `geostore-spring-security.xml` file in your project, if it has been customized and you are not using the default one.
```suggestion
To provide this functionality, it is necessary to update the project's `geostore-spring-security.xml` file, if the default one is not used.
```

2024-05-17 15:17 UTC, tdipisa commented on docs/developer-guide/mapstore-migration-guide.md
> +
The **_diff_** section need to be properly closed here

2024-06-05 07:59 UTC, offtherailz commented on docs/developer-guide/integrations/users/openId.md
> +# enables the keycloak OpenID Connect filter
```suggestion
# enables the OpenID Connect filter
```

2024-06-11 12:13 UTC, offtherailz commented
This can be merged for me. @tdipisaThe release is confirmed ? review and merge when you want.
If the release is confirmed, I'll proceed with backport.

2024-06-11 15:49 UTC, tdipisa approved these changes

2024-06-11 15:49 UTC, merged

2024-06-11 15:49 UTC, tdipisa commented
@offtherailz please test on azure before backporting it.