#10193: Issue with WFS added via Query params
geosolutions-it/MapStore2 pull request #10195
Opened 2024-04-12 09:46 UTC by mahmoudadel54

## Description
In this PR, the issue of not adding WFS layer to map and be not visible is resolved. GetFeature request is performed now correctly by MS.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#10193 

**What is the current behavior?**
#10193 

**What is the new behavior?**
WFS layer is added to map using query params in url if the url contains queryString.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-04-15 12:35 UTC, dsuren1 requested changes

2024-04-15 12:35 UTC, dsuren1 commented on web/client/api/WFS.js
> +
```suggestion
```

I don't think this comment is needed as it is not a new feature. Inline comment on the respective functions is fine

2024-04-15 12:36 UTC, dsuren1 approved these changes

2024-04-15 12:45 UTC, merged

2024-04-16 04:43 UTC, dsuren1 commented
@ElenaGallo Kindly test it in DEV and let us know if it can be backported. Thanks!

2024-04-16 07:39 UTC, tdipisa commented
@ElenaGallo @mahmoudadel54 this is for 2024.01.01 therefore let's wait the delivery of 2024.01.00 before backporting this. Thank you.

2024-05-09 10:04 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2024.01.xx. Thanks

2024-05-09 11:26 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport to 2024.01.xx. Thanks
@ElenaGallo 
Backport is Done here ---> https://github.com/geosolutions-it/MapStore2/pull/10296