#10136: Search for Map CRS coordinates
geosolutions-it/MapStore2 pull request #10305
Opened 2024-05-10 12:06 UTC by mahmoudadel54

## Description
In this PR: keeping user CRS coordinates X/Y as user enters in case entering them in CRS coordinate search then switches to normal coord search [lat/lon] then back again to CRS coordinates search without making change. 
They are keeping as entered without a threshold.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe: enhancement

## Issue
#10136 

**What is the current behavior?**
It is mentioned at the 1st point in this comment: https://github.com/geosolutions-it/MapStore2/pull/10220#issuecomment-2102181118

**What is the new behavior?**
X/Y coordinates are kept as entered by the user without a threshold.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-05-13 11:57 UTC, dsuren1 requested changes
@mahmoudadel54 
**Regression**
- Changing CRS doesn't change the X & Y accordingly, retains previous value

  https://github.com/geosolutions-it/MapStore2/assets/26929983/60dc5c16-7929-4604-953e-850dd69c2a24

2024-05-13 14:31 UTC, tdipisa commented
@mahmoudadel54 to clarify the purpose of this issue as per our previous exchanges in #10220, this PR should:

- Revert what requested [here](https://github.com/geosolutions-it/MapStore2/pull/10220#pullrequestreview-2045240480) as per @dsuren1 indications
- Fix the point 1 reported [here](https://github.com/geosolutions-it/MapStore2/pull/10220#issuecomment-2102181118) by @ElenaGallo during functional tests

2024-05-14 07:28 UTC, dsuren1 approved these changes

2024-05-14 07:29 UTC, merged

2024-05-14 07:29 UTC, dsuren1 commented
@ElenaGallo Kindly test it in DEV and let us know if it's good to be backported. Thanks

2024-05-14 10:39 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2024.01.xx. Thanks

2024-05-14 12:55 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport to 2024.01.xx. Thanks

@ElenaGallo 
Backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/10317