#10264: Layer visibility limits may prevent the Info panel of search results from opening
geosolutions-it/MapStore2 pull request #10302
Opened 2024-05-10 07:39 UTC by mahmoudadel54

## Description
In this PR, getting the selected search item info is implemented and showing the results into the info [identify] panel even if the layer visibility limit. 
the getFeature [identify] action is isolated from epic 'searchItemSelected' into a new epic called 'getFeatureInfoOfSelectedItem' to be applied after zoom and addMarker events  just to make sure implementing zoom action first.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: enhancement

## Issue
#10264 

**What is the current behavior?**
#10264 

**What is the new behavior?**
If the layer has a limited visibility like showing features from a specific scale level, and user searches for an existing feature into the searched layer while the hidden scale level ---> if the feature is existing, it will zoom to this feature and opening the info panel showing the feature info data

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-05-10 13:46 UTC, dsuren1 requested changes

2024-05-10 13:46 UTC, dsuren1 commented on web/client/epics/search.js
> + * it resposible for retrieving feature info of the selected search results that zoom to and added a merker for by `TEXT_SEARCH_ITEM_SELECTED` event
```suggestion
 * Handles performing a GFI on the selected search results after zooming in, and adds a marker
```

2024-05-10 13:46 UTC, dsuren1 approved these changes

2024-05-10 13:55 UTC, merged

2024-05-10 14:00 UTC, dsuren1 commented
@ElenaGallo Kindly test it in DEV and let us know if it's good to be backported. Thanks!

2024-05-14 09:29 UTC, tdipisa commented
@ElenaGallo please double check you test setup and let us know if the test passes.

2024-05-17 15:31 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2024.01.xx. Thanks