#10322: Fix scale selector to make it compatible with different projections
geosolutions-it/MapStore2 pull request #10344
Opened 2024-05-20 07:44 UTC by mahmoudadel54

## Description
In this PR, the issue of scale selector which was not compatible with different projections is resolved.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#10322

**What is the current behavior?**
#10322 

**What is the new behavior?**
Now if user opens the print modal, switches the projection to 4326 for example and select a scale from the scale selector list, it will selected successfully without choosing wrong one.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
- fix the bug by using the updated 'scaleZoom' value instead of the projected value

2024-05-20 07:56 UTC, tdipisa commented
@offtherailz I would like if you can schedule a call with @mahmoudadel54 to review issues requirements before moving on with this review.

2024-06-18 16:25 UTC, offtherailz requested changes
- [ ] I  noticed that the printing result is still wrong when switching coordinates. It have to be consistent with the map. 

[screencast-localhost_8081-2024.06.18-18_21_32.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/32493050-c870-4455-85d1-b55db021b146)

Everything have to be consistent. I'll review the code where it is fixed. 

- [ ] Other useful information are not clear, please explain them better.

2024-06-19 07:36 UTC, offtherailz commented on web/client/plugins/__tests__/Print-test.jsx
> +                await ReactDOM.render(<Plugin
I don't think ReactDOM.render returns a promise

2024-06-19 07:38 UTC, offtherailz commented on web/client/plugins/__tests__/Print-test.jsx
> +                await ReactDOM.render(<Plugin
same here. Await makes sense only on promises.

2024-06-19 07:45 UTC, offtherailz commented on web/client/plugins/__tests__/print/Projection-test.jsx
> +                await ReactTestUtils.Simulate.change(combo, {
`.Simulate.change` does not return a promise, so using `await` is wrong.

2024-06-19 07:45 UTC, offtherailz commented on web/client/plugins/__tests__/print/Projection-test.jsx
> +                await ReactTestUtils.Simulate.change(combo, {
.Simulate.change does not return a promise, so using await is wrong.

2024-06-20 12:09 UTC, mahmoudadel54 commented
> I noticed that the printing result is still wrong when switching coordinates. It have to be consistent with the map. [screencast-localhost_8081-2024.06.18-18_21_32.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/32493050-c870-4455-85d1-b55db021b146)
> 
> Everything have to be consistent. I'll review the code where it is fixed.

Hi @offtherailz 

After checking this issue, I found out, this is the same currently behavior in print [in DEV or QA] ---> if the print projection is one of the geographic coordinate systems [like 4326] and the **'geodetic'** = true  into the "overrideOptions" in print cfg, and when I edited **'geodetic'** to be false, printing map with geographic projection e.g: 4326 printing works for me.
Honestly I don't know the reason.
This is a demo of my debugging: 

https://github.com/geosolutions-it/MapStore2/assets/58145645/b0084bac-1579-4742-b888-db22244b1863

2024-06-21 15:44 UTC, mahmoudadel54 commented
> * [ ]  Other useful information are not clear, please explain them better.

@offtherailz  I have updated the useful information section. I hope it is more clear now

2024-06-26 16:38 UTC, offtherailz requested changes
AS we discussed in a call @mahmoudadel54 the PR has still the inonsistencies I notified in the Preview.

As we checked, the preview looks consistent when `geodetic` is set to `false`, so our development will do it in that direction, assuming that `geodetic` is set to `false`.
Now print plugin allows to send the geodetic parameter via configuration, but it doesn't handle to change the preview to fit the final result.

2024-06-28 08:14 UTC, offtherailz commented
Now it looks a lot better.
I'm reporting here in a comment my findings just to keep track of them.
I'll check if these issues of the preview already existed and let you know.

Discrepancy between the preview and the scale sent (as we have seen in our meeting).

![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/9f78f381-581d-48bc-9697-b6aa55d8fe73)

2024-06-28 13:11 UTC, offtherailz requested changes
Please fix the tests and do a sert of manual tests more.

2024-07-01 14:57 UTC, offtherailz approved these changes

2024-07-01 14:57 UTC, merged

2024-07-01 14:58 UTC, tdipisa commented
@ElenaGallo please test this in DEV once deployed and let us know for the backport.

2024-07-02 16:19 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2024.01.xx Thanks

2024-07-03 05:11 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport to 2024.01.xx Thanks

@ElenaGallo Backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/10452

2024-07-03 10:19 UTC, tdipisa commented
@ElenaGallo I've also tested using test map [here](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/demo_context/49601) and all seems to work as expected with this fix.