Update User Guide - Use Cache Options from WMS service
geosolutions-it/MapStore2 pull request #10362
Opened 2024-05-27 10:01 UTC by ElenaGallo

## Description

Add Use Cache Options on [Catalog](https://mapstore--10362.org.readthedocs.build/en/10362/user-guide/catalog/#advanced-settings_2) section 

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-05-29 15:54 UTC, tdipisa requested changes

2024-05-29 15:54 UTC, tdipisa commented on docs/user-guide/catalog.md
> +* *Use remote custom tile grids*: allows use of the layer cached tiles. If checked, the *Tiled=true* URL parameter will be added to the WMS request to [use tiles cached with GeoWebCache](https://docs
```suggestion
* *Use remote custom tile grids*: if checked, allows to set by default the _custom tile grid caching strategy_ when a layer is added to the map from this source as described in [Layer Settings](layer-settings.md#display).
```

2024-05-29 15:55 UTC, tdipisa commented
@ElenaGallo, changed applied. Please backport to 2024.01.xx. Thank you.

2024-05-29 15:56 UTC, tdipisa approved these changes

2024-05-30 08:56 UTC, ElenaGallo reviewed
*Use remote custom tile grids*: if checked, allows to set by default the *custom tile grid caching strategy* when a layer is added to the map from this source as described in [Layer Settings](layer-settings.md#display).

2024-05-30 09:18 UTC, tdipisa approved these changes

2024-05-30 09:18 UTC, tdipisa commented
> @ElenaGallo, changed applied. Please backport to 2024.01.xx. Thank you.

Merged @ElenaGallo please proceed.

2024-05-30 09:18 UTC, merged