#10342: Fix issue of markers are not printed correctly
geosolutions-it/MapStore2 pull request #10395
Opened 2024-06-03 08:33 UTC by mahmoudadel54

## Description
In this PR, the issue of not showing markers properly in print is resolved.  

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#10342 

**What is the current behavior?**
#10342

**What is the new behavior?**
Now in print, the markers display in it normally.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
The issue was in **symbolizerToPrintMSStyle** where if the passed symbolizer object to '**drawWellKnownNameImageFromSymbolizer**'  has no radius -> it returns NaN and here: https://github.com/geosolutions-it/MapStore2/blob/909d495947e6dadcd07927c6c2f0924418a511a4/web/client/utils/styleparser/PrintStyleParser.js#L88 
you see the initiate values of width and height should be equal size  which won't be as the returned width and height = NaN which override the symbolizer.size value

So the preproduced issue was as the icon height = NaN. not symbolizer.size

2024-06-05 13:04 UTC, allyoucanmap requested changes

2024-06-05 13:04 UTC, allyoucanmap commented on web/client/utils/styleparser/StyleParserUtils.js
> +    const radius = (symbolizer.radius || symbolizer?.size / 2);
This is changing how the `drawWellKnownNameImageFromSymbolizer` used mainly for markers.
The PrintStyleParser was using the [drawWellKnownNameImageFromSymbolizer](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/styleparser/PrintStyleParser.js#L88) to quickly access the imagesCache to get the original width and height of the image so if the function is reaching this point means that the id computed by getImageIdFromSymbolizer(symbolizer) is not correct.
The reason is related to the introduction of the style with properties functionality (https://github.com/geosolutions-it/MapStore2/pull/9541) that introduces some modifications to the symbolizer.
This parsing issue has been partially solved here #9776 but probably the part related to print was missing.
Here the proposed solution:
- create a new function in the StyleParserUtils called getCachedImageById
- replace the drawWellKnownNameImageFromSymbolizer with getCachedImageById inside the Icon section of PrintStyleParser
- Add to the symbolizerToPrintMSStyle function a new argument that is the originalSymbolizer (not parsed symbolizer)
- Pass the not parsed symbolizer as argument of getCachedImageById
- use the symbolizer size as width and height as a fallback only if getCachedImageById returns undefined 

```js
export const getCachedImageById = (symbolizer) => {
    const id = getImageIdFromSymbolizer(symbolizer);
    return imagesCache[id];
}
```

2024-06-06 14:25 UTC, allyoucanmap approved these changes

2024-06-06 14:26 UTC, merged

2024-06-06 14:26 UTC, allyoucanmap commented
@ElenaGallo please test this fix on dev and let us know if we can backport on 2024.01.xx, thanks

2024-06-06 15:49 UTC, ElenaGallo commented
Test passed @mahmoudadel54 please backport to 2024.01.xx. Thanks

2024-06-07 08:23 UTC, mahmoudadel54 commented
> Test passed @mahmoudadel54 please backport to 2024.01.xx. Thanks

Backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/10413