#10414: Remove the list of associated groups of logged in user from the User Details modal window
geosolutions-it/MapStore2 pull request #10415
Opened 2024-06-07 12:29 UTC by mahmoudadel54

## Description
In this PR, handling hiding the group info in the user details modal by adding a cfg in Login plugin 'hideGroupUserInfo' is implemented. If 'hideGroupUserInfo' is configured into Login plugin cfg, 
`{
              "name": "Login",
              "cfg": {
                "toolsCfg": [{"hideGroupUserInfo": true}]
              }
}`
the group info into user details modal will not be shown.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#10414 

**What is the current behavior?**
#10414 

**What is the new behavior?**
If 'hideGroupUserInfo' is configured into Login plugin cfg, the group info into user details modal will not be shown.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-06-12 10:28 UTC, MV88 requested changes
your solutions works only because the user details is the first in the list of tools, but if a project has a custom login plugin this might not work, so I think you have to specify this information as well. Probably it should be mentioned in the migration guidelines because it could be a breaking change in a sense that this configuration may not work there if there are refactors to the login plugin. the index part is import to highlight.

- [ ] please add this entry in the migration guidelnes
- [ ] improve tests

2024-06-25 08:51 UTC, MV88 requested changes
make sure to run locally documentation to check possible syntax errror

2024-06-25 08:51 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
>  ## Migration from 2024.01.00 to 2024.02.00
```suggestion
## Migration from 2024.01.00 to 2024.01.02
```

2024-06-25 08:51 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
> +Recently, we have added the option to hide the `user group info` from the user details modal. To enable this, you have to add a cfg in all `Login` plugin into localConfig like:
```suggestion
Recently, we have added the option to hide the `user group info` from the user details modal. 
To enable this, you have to add a cfg in all `Login` plugin into `localConfig.json` like:
```

2024-06-25 08:51 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
> +  - If the mentioned cfg is put into an index rather than the 1st one, it will not work as expected, so the index should be respected.
```suggestion
  if you have customized the Login plugin and in particular the order of toolsCfg, make sure to override the correct one as the propagation of cfg for the tools is based on index value
```

2024-06-25 08:51 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
> +  - This may not work if the project includes a customized Login plugin.
```suggestion

```

2024-06-25 08:51 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
> +- Important notes should be considered:
```suggestion
!!! note Important notes should be considered:
```

2024-06-27 13:17 UTC, MV88 approved these changes

2024-06-27 13:17 UTC, merged

2024-06-27 15:57 UTC, ElenaGallo commented
@tdipisa even the admin can't see the GroupUserInfo section, is this correct? 

![admin](https://github.com/geosolutions-it/MapStore2/assets/56537133/aa670289-26d4-4e7a-b5e4-98b77440ecf1)

2024-06-27 16:07 UTC, tdipisa commented
> @tdipisa even the admin can't see the GroupUserInfo section, is this correct?
> 
> ![admin](https://private-user-images.githubusercontent.com/56537133/343853166-aa670289-26d4-4e7a-b5e4-98b77440ecf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDQ3MTYsIm5iZiI6MTcxOTUwNDQxNiwicGF0aCI6Ii81NjUzNzEzMy8zNDM4NTMxNjYtYWE2NzAyODktMjZkNC00ZTdhLWI1ZTQtOThiNzc0NDBlY2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE2MDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZjE1ZjA5Y2I1NDYxN2U0NzJjYzNiMWJlODRhZDM1NGVhNDExMzY0OWZiM2FlMmFlNjdhMmY5ZmEyMWFhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5T04Q9_w7-qPPSIHa1nr9jO70Uq8gtU-EVpKeiWN-NM)

I've commented here:
https://github.com/geosolutions-it/MapStore2/issues/10414#issuecomment-2195106822

Something that has not been reported in the ACs. @mahmoudadel54 can you please take a look?

2024-06-27 16:08 UTC, tdipisa commented
> > @tdipisa even the admin can't see the GroupUserInfo section, is this correct?
> 
> I've commented here: [#10414 (comment)](https://github.com/geosolutions-it/MapStore2/issues/10414#issuecomment-2195106822)
> 
> Something that has not been reported in the ACs. @mahmoudadel54 can you please take a look? Is it something we can do simply by config or dev is necessary?

2024-06-27 16:11 UTC, mahmoudadel54 commented
> > @tdipisa even the admin can't see the GroupUserInfo section, is this correct?
> 
> I've commented here: [#10414 (comment)](https://github.com/geosolutions-it/MapStore2/issues/10414#issuecomment-2195106822)
> 
> Something that has not been reported in the ACs. @mahmoudadel54 can you please take a look?

Ok I will take a look for it

2024-06-27 16:14 UTC, mahmoudadel54 commented
> > @tdipisa even the admin can't see the GroupUserInfo section, is this correct?
> 
> I've commented here: [#10414 (comment)](https://github.com/geosolutions-it/MapStore2/issues/10414#issuecomment-2195106822)
> 
> Something that has not been reported in the ACs. @mahmoudadel54 can you please take a look? Can we do that simply by config or dev is necessary for it?

Dev is necessary for it even we put a config for theis requirement

2024-06-27 16:20 UTC, tdipisa commented
@mahmoudadel54 thank you for this check. Let's leave this as it is now since is is not so fundamental and this setup is not the default one.

2024-06-27 16:24 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2024.01.xx

2024-06-27 17:08 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport to 2024.01.xx

backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/10447