fix #10235: Interactive legend in dashboard and geostory
geosolutions-it/MapStore2 pull request #10438
Opened 2024-06-21 14:49 UTC by mahmoudadel54

## Description
In this PR, fixing issue of reset legend filter within map configure panel in geostory is implemented. Now in geostories, if the interactive legend is enabled and set on a new map, it is possible to edit it correctly on the map inline panel.
The issue is mentioned here: https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2176031801

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2176031801

**What is the current behavior?**
https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2176031801

**What is the new behavior?**
In geostories, if the interactive legend is enabled and set on a new map, it is Ok to edit it correctly on the map inline panel without any non expected behavior.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-07-04 09:19 UTC, allyoucanmap requested changes

2024-07-04 09:19 UTC, allyoucanmap commented on web/client/utils/__tests__/GeoStoryUtils-test.js
>                  }
I would avoid to change the test structure.
Here it seems that the expectation is to merge these value so probably we should apply the replacement just for the layer key.

We will need also an additional test for the layers key

2024-07-04 09:19 UTC, allyoucanmap commented on web/client/utils/GeoStoryUtils.js
> +    return updatedMap;
Based on the previous comment I think we should merge all the properties but the layers key that will be overridden

2024-07-24 10:35 UTC, allyoucanmap requested changes
@tdipisa @mahmoudadel54 This fix should take into account also the problem described in this other issue https://github.com/geosolutions-it/MapStore2/issues/10489.
I'm going to change the title of PR and connect it to the new issue

2024-07-29 08:51 UTC, tdipisa commented
> @tdipisa @mahmoudadel54 This fix should take into account also the problem described in this other issue #10489. I'm going to change the title of PR and connect it to the new issue

@mahmoudadel54 can you please proceed as requested above providing an estimate before?

2024-08-08 07:34 UTC, allyoucanmap approved these changes

2024-08-08 07:35 UTC, merged

2024-08-08 07:35 UTC, allyoucanmap commented
@ElenaGallo please test this fix on dev, thanks