Update User Guide - Interactive legend for TOC layers
geosolutions-it/MapStore2 pull request #10477
Opened 2024-07-16 14:54 UTC by ElenaGallo

## Description

 Interactive legend for TOC layers on (Display Layer settings)[https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/layer-settings/#display] section and (Catalog)[https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/catalog/#wmswmts-catalog] section

2024-09-30 16:29 UTC, allyoucanmap requested changes

2024-09-30 16:29 UTC, allyoucanmap commented on docs/user-guide/layer-settings.md
> +    The *Interactive legend* option os available only for the layers added from WMS/CSW and WFS catalog sources.
I think we should mention that this option is experimental. I don't think it's supported by the WFS catalog yet.

```suggestion
    The *Interactive legend* is an experimental option and it is disabled by default. The flag `miscSettings.experimentalInteractiveLegend` inside [localConfig](local-config.md) must be set to true to enable this functionality. The *Interactive legend* is available only for GeoServer WMS layers that support the json format for GetLegendGraphic requests.
```

2024-09-30 16:29 UTC, allyoucanmap commented on docs/user-guide/layer-settings.md
> +* Enable/disable the **Interactive legend**. If this option is enable, filter by legend can be applied by clicking on legend items of this layer from the TOC. An example can be the following one:
```suggestion
* Enable/disable the **Interactive legend**. If this option is enabled, legend entries with an associated valid filter are displayed as toggleable items inside the TOC, an user can click on these legend items to filter the content of the layer. An example can be the following one:
```

2024-09-30 16:29 UTC, allyoucanmap commented on docs/user-guide/layer-settings.md
> +    Any type of filter rather than the legend filter will keep the legend filter beside it.
What do we want to highlight with this note?

2024-10-02 08:07 UTC, allyoucanmap approved these changes

2024-10-02 08:34 UTC, merged

2024-10-02 08:35 UTC, tdipisa commented
@ElenaGallo can you please backport this to 2024.02.xx?