Update Use Guide - ArcGIS Interoperability
geosolutions-it/MapStore2 pull request #10478
Opened 2024-07-16 16:15 UTC by ElenaGallo

## Description

Add ArcGIS service on [Catalog]() section

2024-09-30 15:31 UTC, allyoucanmap requested changes

2024-09-30 15:31 UTC, allyoucanmap commented on docs/user-guide/catalog.md
> +An [**ArcGIS**](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/services-in-arcgis-enterprise.htm) service organize spatial data into functional GIS resources to run on a web
I think we should specify that we are supporting ArcGIS Rest Service (https://developers.arcgis.com/rest/services-reference/enterprise/get-started-with-the-services-directory/). In particular we support MapServer and ImageServer types.

```suggestion
An [**ArcGIS Server Services Directory**](https://developers.arcgis.com/rest/services-reference/enterprise/get-started-with-the-services-directory/) is a RESTful representation of all the services running on an ArcGIS Server site. MapStore allows to add ArcGIS [Map Service](https://developers.arcgis.com/rest/services-reference/enterprise/map-service/) and [Image Service](https://developers.arcgis.com/rest/services-reference/enterprise/image-service/) types through its *Catalog* tool where a specific source type can be configured.
```

2024-09-30 15:31 UTC, allyoucanmap commented on docs/user-guide/catalog.md
> +
We could mention that the url could have different structure
```suggestion

The `URL` could have one of the following structures:

- `https://<catalog-url>/rest/services/`
- `https://<catalog-url>/rest/services/<serviceName>/MapServer`
- `https://<catalog-url>/rest/services/<serviceName>/ImageServer`

```

2024-10-02 08:03 UTC, allyoucanmap approved these changes

2024-10-02 08:36 UTC, merged

2024-10-02 08:36 UTC, tdipisa commented
@ElenaGallo can you please backport this to 2024.02.xx?