#10489: Fix #10489 Problems with GeoStory map configurations merge process
geosolutions-it/MapStore2 pull request #10516
Opened 2024-08-21 14:42 UTC by mahmoudadel54

## Description
This PR fixes the issue that was mentioned in (https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2293383703). The issue was in this PR: https://github.com/geosolutions-it/MapStore2/pull/10438 in editing this part: 

https://github.com/geosolutions-it/MapStore2/blob/7b1e9b4cbdd960297587e28fe1450878567fcfb2/web/client/components/geostory/common/enhancers/map.jsx#L40-L44 

 plus 'createMapObject' method to handle legacy geostory. This editing was missing handling a case of editing layers single propery like layer's title/opacity/visibility ...etc.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2293383703

**What is the current behavior?**
(https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2293383703)

**What is the new behavior?**
The app doesn't crash.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-08-27 10:48 UTC, allyoucanmap requested changes

2024-08-27 10:48 UTC, allyoucanmap commented on web/client/components/geostory/common/enhancers/map.jsx
> +            const layersGroupsHasEmptyItems = (map?.layers || []).includes(undefined) || (map?.groups || []).includes(undefined);
This implementation seems to solve the problem but it introducing a new set of checks for a specific configuration caused from an inconsistency on the way we update layers/groups in the settings panel.

I would like to propose a change inside the [MapEditor](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/geostory/common/MapEditor.jsx#L105) instead. The `onChange` of the Editor component should update the layers or groups key of the map instead to target a specific index of the list of layers/groups. Something like the following code:

```js
<Editor
    closeNodeEditor={closeNodeEditor}
    editNode={editNode}
    map={map}
    onChange={(path, value) => {
        const config = set({ map: { ...map } }, path, value);
        const { layers, groups } = config?.map || {};
        if (path.includes('map.layers[')) {
            onChangeMap('layers', layers);
        } else {
            onChangeMap('groups', groups);
        }
    }}/>
```
By modifying the way we update the layers/groups keys of the map on the setting we are going to align it to the behaviour of the TOC. If we are introducing this change we don't need the `layersGroupsHasEmptyItems` introduced by this PR

2024-09-05 15:58 UTC, allyoucanmap approved these changes

2024-09-05 15:58 UTC, merged

2024-09-05 15:59 UTC, allyoucanmap commented
@ElenaGallo please test this on dev and let us know when we can backport on 2024.02.xx, thanks

2024-09-11 12:17 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2024.02.xx. Thanks

2024-09-11 14:36 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport to 2024.02.xx. Thanks

@ElenaGallo 
backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/10539