Editable fields - get feature field value from user infos
geosolutions-it/MapStore2 pull request #10524
Opened 2024-08-30 10:34 UTC by Gaetanbrl

## Description

> This pull request is link to #10523

**Doc will be added soon.**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
 - [x] Feature

## Issue

**What is the current behavior?**

This is new behavior. See issue to get more details.

#10523

**What is the new behavior?**

- ability to manage field editing independently
- ability to get a field from user info (e.g name get name)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-10-29 09:56 UTC, Gaetanbrl commented
The source branch is now rebase / align with master (https://github.com/geosolutions-it/MapStore2/commit/8e2d4433427ce5b7cf7628c8d51f724f29d2bf18)

2025-02-28 17:03 UTC, MV88 requested changes
please see inline comments

2025-03-31 08:34 UTC, Gaetanbrl commented
Thanks for this review @MV88 .
I've been away for a while, I'll have a look as soon as I can.

2026-01-20 17:55 UTC, tdipisa commented
@Gaetanbrl I'm sorry, this PR is quite old. Do you have plans to re-handle this according to our review above? Otherwise, I would like to close the PR.

2026-04-14 08:28 UTC, Gaetanbrl commented
I don't quite know how to respond; it’s becoming quite a headache. I’ll need to assess the conflicts and estimate the remaining workload in addition to the time already invested... it’s a complex situation.

I'm questioning whether there is at least some interest in this PR on your end.

2026-06-17 08:07 UTC, tdipisa commented
Hi @Gaetanbrl as you told me during our exchange last week, I'm going to close this.

2026-06-17 08:07 UTC, closed without merging