fix: resetting selectedService for catalog while adding background la…
geosolutions-it/MapStore2 pull request #10586
Opened 2024-10-02 13:27 UTC by rowheat02

## Description

While adding the background layer, a backup for the selected catalog service is stored in the backgroundselector store.
And same service is set while closing the Catalog Modal.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#10486
The selected catalog service changes after trying to add a background layer

**What is the new behavior?**

Selected Catalog service remains same even after trying to add background layer

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-10-04 08:33 UTC, offtherailz requested changes
The fix works, but the code have to be written to be more maintainable and readable.

2024-10-04 08:33 UTC, offtherailz commented on web/client/actions/backgroundselector.js
> +}
This action stashes the selected catalog, not a backup of the  background. 
I'd also document to understand what is the parameter accepted (e.g. ID, object....).
So for this action I should use the following:
```suggestion
/**
 * stashes the current selected catalog to restore after catalog close, when opening
 * the catalog for background selection
 * @params ... <--- Insert here the parameter type and name
 */
export function stashSelectedCatalogService(service) {
    return {
        type: STASH_SELECTED_SERVICE,
        service
    };
}
```

2024-10-04 08:33 UTC, offtherailz commented on web/client/epics/backgroundselector.js
> +            addBackupBackground(store.getState().catalog.selectedService),
Use selectors when available  in this case `selectedServiceSelector` in `selectors/catalog`.
This helps future refactors (e.g. internal restructuration of state) without having to find around the code all the `x.y.z` strings.

2024-10-04 08:33 UTC, offtherailz commented on web/client/epics/catalog.js
> +                    [changeSelectedService(state.backgroundSelector.backupBackground), allowBackgroundsDeletion(true)] : [])));
Also in this case, create a selector for that value and use it here.

2024-10-04 08:33 UTC, offtherailz commented on web/client/actions/backgroundselector.js
> +export const ADD_BACKUP_BACKGROUND = 'BACKGROUND_SELECTOR:ADD_BACKUP_BACKGROUND';
```suggestion
export const ADD_BACKUP_BACKGROUND = 'BACKGROUND_SELECTOR:STASH_SELECTED_SERVICE';
```

2024-10-04 15:46 UTC, offtherailz approved these changes

2024-10-04 15:49 UTC, merged

2024-10-04 15:50 UTC, offtherailz commented
@ElenaGallo, could you please test this on  DEV  ? Thank you

2024-10-08 10:53 UTC, ElenaGallo commented
Test passed, @rowheat02 please backport to 2024.02.xx. Thanks