Home and Login Plugins do not appear on the page if the Burger Menu is activated in the context in 2024.01.01 version #10503
geosolutions-it/MapStore2 pull request #10590
Opened 2024-10-03 11:26 UTC by rowheat02

#10503 
In the map of context with plugins **login and home**. More priority has been given to the sidebar which is a hidden plugin in the context map.
Probable introduction of this issue is from PR https://github.com/geosolutions-it/MapStore2/pull/9841/files
Overriding priority while creating the context for those plugins solves the issue.

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

#10503 

**What is the current behavior?**

#10503

**What is the new behavior?**
Docs have been updated showing how to override the priority of the plugin home and login

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-10-04 08:47 UTC, offtherailz requested changes
The proper position for this documentation is in the login's jsdoc, so it will be available in context's configuration (the "?" icon of plugins links to jsdoc.

Please paly also attention to the syntax you are using. 
````
Use ```javascript or ```js instead of "``` JavaScript"
```` 

In order to test it use :  

for mkdocs 

mkdocs serve as a preview


for JSDoc, the utility jsdoc:test

[Here](https://docs.mapstore.geosolutionsgroup.com/en/v2024.01.02/developer-guide/building-and-deploying/#api-and-plugins-documentation-jsdoc) how to

2024-10-04 15:49 UTC, offtherailz requested changes

2024-10-04 15:49 UTC, offtherailz commented on web/client/plugins/Login.jsx
> + * Example of configuration.
Check your PR to prevent lines committed in error, like this.
```suggestion
  * Example of configuration.
```

2024-10-04 15:49 UTC, offtherailz approved these changes

2024-10-04 15:50 UTC, offtherailz commented
@ElenaGallo, could you please test this on  DEV  ? Thank you

2024-10-04 15:58 UTC, merged

2024-10-09 05:56 UTC, rowheat02 commented
@ElenaGallo Did you pass plugin configuration
```
{
    "cfg": {},
    "override": {
        "OmniBar": {
            "priority": 5
        }
    }
}
``` 
on home and login plugin. 
This PR only updated the docs to achieve those two plugins in Omnibar.
<img width="704" alt="image" src="https://github.com/user-attachments/assets/8e447698-cceb-4dc3-9bc3-3827dd1b6de3">

2024-10-09 07:45 UTC, ElenaGallo commented
@rowheat02 ok, thanks. I'll re-test the issue.

2024-10-09 08:57 UTC, ElenaGallo commented
Test passed, @rowheat02 please backport to 2024.02.xx. Thanks