Fix #10641 tooltips for layerinfo
geosolutions-it/MapStore2 pull request #10642
Opened 2024-10-29 17:49 UTC by MV88

## Description

tooltips updated for layer info text

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #10641

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-10-29 17:59 UTC, tdipisa requested changes
@MV88 let's make things clear. The layer filter is this one:
https://docs.mapstore.geosolutionsgroup.com/en/v2024.01.02/user-guide/filtering-layers/#layer-filter

Make sure the tooltip property name is also consistent with the tool "Update layers titles and descriptions" and doesn't conflict with the one of "Layer Filter". Looking at the translation files it seems confusing.

2024-10-30 06:22 UTC, MV88 commented
> @MV88 let's make things clear. The layer filter is this one: https://docs.mapstore.geosolutionsgroup.com/en/v2024.01.02/user-guide/filtering-layers/#layer-filter
> 
> Make sure the tooltip property name is also consistent with the tool "Update layers titles and descriptions" and doesn't conflict with the one of "Layer Filter". Looking at the translation files it seems confusing.

i noticed that the layerinfo was using wrong path, and the correct one was already present.

2024-10-30 08:49 UTC, allyoucanmap approved these changes

2024-10-30 08:52 UTC, tdipisa approved these changes

2024-10-30 08:52 UTC, merged

2024-10-30 09:07 UTC, MV88 commented
@ElenaGallo please test it in DEV