Fix #10695 Handle empty values for and/or/not/nor filters
geosolutions-it/MapStore2 pull request #10696
Opened 2024-11-27 09:51 UTC by offtherailz

## Description
This PR avoids the `<ogc:And>undefined</ogc:And>` in OGC filters that happens when having an empty filter.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#10695 

**What is the new behavior?**

Fix #10695 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-11-27 15:43 UTC, MV88 requested changes
LGTM

2024-11-27 15:43 UTC, MV88 commented on web/client/utils/ogc/Filter/__tests__/operators-test.js
> +        )).toBe('');
can't you have these in one line?

2024-11-27 15:43 UTC, MV88 commented on web/client/utils/ogc/Filter/__tests__/FilterBuilder-test.js
> +        ).toBe("");
can't you have these in one line ?

2024-11-27 15:43 UTC, MV88 commented on web/client/utils/ogc/Filter/operators.js
> +const multiop = (ns, op, content) => op(ns, Array.isArray(content) ? content.join("") : content );
```suggestion
const multiop = (ns, op, content) => op(ns, Array.isArray(content) ? content.join("") : content);
```

2024-11-27 17:03 UTC, offtherailz commented on web/client/utils/ogc/Filter/__tests__/FilterBuilder-test.js
> +        ).toBe("");
```suggestion
        expect(b.and()).toBe("");
        expect(b.or()).toBe("");
        expect(b.not()).toBe("");
        expect(b.nor()).toBe("");
```

2024-11-27 17:03 UTC, offtherailz commented on web/client/utils/ogc/Filter/__tests__/operators-test.js
> +        )).toBe('');
```suggestion
        expect(logical.and("ogc")).toBe('');
        expect(logical.or("ogc")).toBe('');
        expect(logical.not("ogc")).toBe('');
```

2024-11-27 17:08 UTC, MV88 approved these changes

2024-11-27 17:28 UTC, merged

2024-11-27 17:28 UTC, tdipisa commented
@ElenaGallo please check in DEV on deployed and let us know for the backport.

2024-12-02 11:38 UTC, ElenaGallo commented
Test passed, @MV88 please backport. Thanks