Enhancing User Session #10657
geosolutions-it/MapStore2 pull request #10712
Opened 2024-12-04 04:39 UTC by rowheat02

2025-01-14 17:18 UTC, offtherailz requested changes
- [x] The icon of delete is the same of the delete map. It is a pre-existing issue, but is confusing. 
![image](https://github.com/user-attachments/assets/91cd88d2-6421-4913-b0c3-f046bbcb57d6)
I'd suggest clear-brus icon for user session clean (or a custom icon). Let's wait for a confirmation from @tdipisa about this.
![image](https://github.com/user-attachments/assets/8630f901-e64a-49a0-9492-bad59488aebb)

- [x] To be more clear I'd change the window as following:
    - Instead of simple "Waring", insert in the title "Clear user session"
    - The text should be: "Are you sure to remove the current user session? This will restore the original map/context configuration, removing your current changes. Please select what you want to remove and unselect what you want to preserve."  (properly localizing strings).
    - A little more margin between text and tree, to better isolate the parts (or a lightgray border for the tree)
    -  and button on bottom with normal size (they are giant).
Bug:
- [x] Inconsistent selection after closing and re-opening the window (see the video, click on everything, then close and reopen, last items are selected). Same if I save the session.

[screencast-localhost_8081-2025_01_14-17_32_07.webm](https://github.com/user-attachments/assets/79a580ed-c751-4f82-9b16-ca14c1a207c0)

- [x] Visibility messed up on user session clean up/restore (see blue borders on layers, indicating the current seleted background. (Also checking-unchecking layers makes the background layer selection change). ALSO THIS IS PRE-EXISTING.

[bug_background.webm](https://github.com/user-attachments/assets/a4fe6e71-ef3e-4f5b-a568-2f75978dd7e9)
Here a screenshot on dev, same issue: ![image](https://github.com/user-attachments/assets/64ac72d3-a07c-4fe1-9182-07465bb21450)


- [ ] Created a map with annotation  and measure layer. Clean up session just to make sure. Remove measure layer and refresh. I have 2 annotation layers. Please fix this and test better these corner cases, adding unit tests to guarantee this issue not happens. NOTE: looks to be a pre-existing bug. It happens also on DEV. JFI @tdipisa 

https://github.com/user-attachments/assets/2ecbf189-55f9-4423-bc2b-28ccc404263b

- Map uses for test: https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/session_all_plugins/52242 (locally of course).

- [x] As discussed, please update documentation of the plugin with the new logic, fixing old phrases (partially, BurgerMenu...) and adding this to clarify the workflow

````
```mermaid
graph TD
    
    S[Start] --> A
    A[Load Context] -->|Override Map Config| B[Load Map] 
    B --> |Override partially map config| C[Load Session]
    C --> |Save Session| C
    C --> |Clear config| D[Clear Session] 
    D --> |Reload| A
```
    
````

2025-01-14 17:25 UTC, offtherailz commented
For both developers and testers, @rowheat02 MAKE YOU SURE YOU TEST SESSION:  
- Within a context ( `#/context/user_session/`)
- Within a map ('`#/context/user_session/1234`)
- With default viewer ('#/viewer/1234`, tweaking localConfig to add by default UserSession plugin`)· 

This is to @ElenaGallo too, when this issue will be merged in next days.

2025-01-15 09:08 UTC, tdipisa commented
@rowheat02 possibly we should try to address all reported points above. Just let me know how much time these require in your opinion, especially for pre-existing bugs. If the effort is too much we can consider opening a separated issue for them.

2025-01-17 06:53 UTC, rowheat02 commented
Updated the PR:
Tested on default viewer, context, and context map. Seems to be working on all cases.
All pre-existing cases are also solved as mentioned above:  layers-specific cases are solved by new overriding logic. None of them are replicating now.
Here is the basic user session workflow (Mermaid chart was  not rendering on JSdocs build, so putting Mermaid here)
``` mermaid
flowchart TD
    A[Start] --> B[Load Context or default viewer]
    B --> CC{Is UserSession Configured}
    CC --> |Yes| LUS[Load user session]
    ST[(Storage)] --> LUS
    LUS --> C
    B --> |No| C{The URL contains also mapID?}
    C -->|Yes| D[Use Map from map resource]
    C -->|No| E[Use Map from context resource]
    D --> F[Check User Session Configuration]
    E --> F
    F --> G{Is User Session saved?}
    G -->|Yes| H[Apply Configuration of the session to the map]
    H --> I
    G -->|No| I[User Interactions]
    I --> |Reset| M[Indicate parts to reset]
    M --> |Save session partally| ST
    I --> |Save at regular interval| ST
```

2025-01-21 08:22 UTC, rowheat02 commented
The fix for the pre-existing issue https://github.com/geosolutions-it/MapStore2/issues/10713 is also pushed here.

2025-02-19 07:04 UTC, rowheat02 commented
For recent translation conflict:
@offtherailz It's strange that resourcesCatalog changes were inside drawlocal also in data.sk-SK and data.sk-SE. Probably there were a lot of changes to the translation files.
resourcesCatalog was also on the last with some missing keys. 
So, I merged both objects and put it at the last which makes sense compared to other translation files like data.en-US.

2025-02-28 11:46 UTC, offtherailz approved these changes
Works well for me. Just fix the translations files and we can merge.

2025-03-03 07:51 UTC, rowheat02 commented
@offtherailz Conflicts resolved for translation files.

2025-03-03 09:59 UTC, merged