Fix #10631 New MapStore Home Page
geosolutions-it/MapStore2 pull request #10731
Opened 2024-12-19 14:00 UTC by allyoucanmap

## Description

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2025-01-16 17:04 UTC, offtherailz reviewed
# Home page


## Home page - Featured
- [ ] How to make maps features/unfeatured? I coudn't find how to.
- Featured has the main purpose of putting some items on top of the page. If this list have to be paginated, maybe a "carousel" that auto-present featured items is more indicated to browse pages.
- [ ] Featured are filtered too, but here graphically it looks that filter applies only on contents. I don't is a little unclear to me, but it's opinable.
![image](https://github.com/user-attachments/assets/7a0bdea9-c982-48e3-ace7-4a0fff40858d)
- [x] Italian and french translation broken 
![image](https://github.com/user-attachments/assets/e3e706e2-7611-46fa-bc28-894a23eea946)
- [ ] Change  "View resource properties" --> "Open resource properties" , or simply "open properties".
![image](https://github.com/user-attachments/assets/25b0d00d-5c31-4686-b495-841b95bf6427)



## Home - Grid view
- [ ] Sticking the pagination to the bottom of the window gives the illusion that there are no more rows, but they are present, scrolling down. Personally I'd perfer a continuous scrolling, istead of pagination. To solve this misunderstanding, you could put the scroolbar on bottom, without sticky effect, or clearely indicate how many items per pages you loaded.
![image](https://github.com/user-attachments/assets/c8385956-9f0a-46a5-b904-3e62ad37cc4a)
- [x] The icon for advertized in yellow is not readable (too small). You can use black color 
![image](https://github.com/user-attachments/assets/dcae1ef3-ab56-45e0-ad12-a22e49466658) 
![image](https://github.com/user-attachments/assets/2405f23a-9f22-4b0f-b1ae-75a043c001a6)
- [x] The map context indcator shows the cursor to be clickable, but is not clickable. We should indicate better the meaning in the tooltip. ("This map uses the context 'demo_context' ").
![image](https://github.com/user-attachments/assets/279f6092-4722-45d8-8469-bf3f305b1d35)
- [ ] The icon of the user shows the cursor clickable, but is not (if click, nothing happens) only if I click on the user name the resources are filtered by creator. A tooltip should indicate that clicking on the name "filter by user". Also the user 
    - The information of the creator should maybe be hidden to users that are no logged in, as well as the application hides the created by and the modified by options.
- [ ] Is not clear the role of the user in the card (creator, owner...). Ideally I expect to have the owner, but it looks to be the creator. Now they are the same, but when the ownership can be changed, also this need to be keept aligned (probably now is not possible to filter by owner).  A tooltip on the user icon may clarify this.



## Home - Tabular view
- [x] Default Name column is too big
![image](https://github.com/user-attachments/assets/ebe8ce62-4d65-4628-b66a-ed8c759c37c9)
I'd suggest something like this: 
![image](https://github.com/user-attachments/assets/0065db0e-0055-4f41-9ccf-6e2335241095)
- [ ] columns Modified and Created by are a little unconsistent.  The information to display in couples are usually "Created by" and "Created at" or "Last modified at" and "Last modified at". Probably you wanted to indicate "Last modified" and "Owner".  It could be cool to allow to select teh columns to show via UI.
- [x] Modified column is too small, increase a little the size to show the full date, or use a more compact format for the date. 
- [x] When date is not present, do not show a clock with empty text, but "N/A", "Unknown".
- [ ] Menus are a little misaligned, reduce the text length may help.
![image](https://github.com/user-attachments/assets/d7cc3325-bafa-426d-b2dc-1e6761355d69)


# Home - Filters
- [ ] Maybe its a minor thing, but could be good to avoid this condition when apply a maps by context filter and not including maps, by disabling that tool (and not applying) when map is not selected.
![image](https://github.com/user-attachments/assets/4d5735c7-102d-443a-8c6c-949ff74f4022)


# Map
- [ ] Old contexts may display like this: (e.g. `http://localhost:8081/#/context/session_all_plugins`

![image](https://github.com/user-attachments/assets/7471d51f-4d97-46a0-ad3c-3e5e64a8d8cd) 
[session_all_plugins-context.json](https://github.com/user-attachments/files/18442946/session_all_plugins-context.json)


- [ ] Please use tooltips on top bar properties, save, save as items. 
- [ ] The multi-floppy is usually the icon of save all, not "Save as...". Looking on internet, I see that the "Save As..." functinality is indicated with a floppy with a pencil, or a a floppy with "...". Something like this: 
![image](https://github.com/user-attachments/assets/78178675-dafd-4826-a5e4-ba0715f2706d)
- [ ] While loading, save button shows changes. It should be disabled and not show changes until loaded.
- [ ] When I change something on the map, both save and save as buttons show modified indicator. I think that only one should show it (if saved, save, if not saved,only save as button is present, so only save as button should show the indicator).
- [ ] Creating a new map from home page, I'm allowed to leave without saving. 
- [ ] I noticed this difference opening same context/map locally or on dev ) notice gian legend on left) `/demo_context/46500`
![image](https://github.com/user-attachments/assets/8c1522ae-5816-4b47-9b10-338734f19cd1)

# Doc
- [ ] Do we need to migrate old contexts somehow?
- [ ] Need to update migration guidelines indicating the changes to apply on local config (monitored state, plugins).
- [ ] I noticed that many things has not been removed. What is the policy we want to use?
     - Deprecate: in this case, we need to indicate the plugins deprecated, and sooner deleted, with old components that are not used anymore.
     - Delete: in this case we should remove the plugins at all, so the depending project are forced to migrate.
- [ ] JSDoc should be updated accordingly, documenting new home page plugins and marking as deprecated the others.

# Config
- [ ] PluginsConfig should be updated with new plugins, to compose context with new plugins and settings.

## Other issues, to check on geostore.
- [ ] Creator filter do not work, and also first page shows 11 results, but they look to be geostore problems.
- [ ] Sort by do not look workling yet

2025-01-24 10:48 UTC, allyoucanmap commented
@axl8713 could you help me to fix the problem in the test-back-end check?
https://github.com/geosolutions-it/MapStore2/actions/runs/12946955404/job/36112504186?pr=10731

2025-01-24 17:31 UTC, allyoucanmap commented
@tdipisa here I reported what discussed and agreed (cc @offtherailz)

> How to make maps features/unfeatured? I coudn't find how to.

This can be done from the Resource details panel, there is a checkbox for admin users

![image](https://github.com/user-attachments/assets/410096a1-7f6a-42ee-9628-5702335e2c1e)

> Featured has the main purpose of putting some items on top of the page. If this list have to be paginated, maybe a "carousel" that auto-present featured items is more indicated to browse pages.

I’m going to open an issue to keep track of this

> Featured are filtered too, but here graphically it looks that filter applies only on contents. I don't is a little unclear to me, but it's opinable.

An idea could be to introduce a global search visible centered with an inline filter button

> Sticking the pagination to the bottom of the window gives the illusion that there are no more rows, but they are present, scrolling down. Personally I'd perfer a continuous scrolling, istead of pagination. To solve this misunderstanding, you could put the scroolbar on bottom, without sticky effect, or clearely indicate how many items per pages you loaded.

For the moment we agreed to keep this as is

> The multi-floppy is usually the icon of save all, not "Save as...". Looking on internet, I see that the "Save As..." functinality is indicated with a floppy with a pencil, or a a floppy with "...". Something like this:

For the moment I restored the old icon, I’m going to open an issue to review this icon and the open properties icon

>  I noticed this difference opening same context/map locally or on dev ) notice gian legend on left)

This happens because the dev instance has the interactive legend activated

> Need to update migration guidelines indicating the changes to apply on local config (monitored state, plugins).
> JSDoc should be updated accordingly, documenting new home page plugins and marking as deprecated the others.

Documentation will be managed in a separate issue

> I noticed that many things has not been removed. What is the policy we want to use?
> Deprecate: in this case, we need to indicate the plugins deprecated, and sooner deleted, with old components that are not used anymore.
> Delete: in this case we should remove the plugins at all, so the depending project are forced to migrate.

For the moment I marked the deprecated plugins, I’m going to open an issue to remove the unused plugins and code

> PluginsConfig should be updated with new plugins, to compose context with new plugins and settings.

Here we should evaluate which new plugins should be included in the context (probably BrandNavbar and ResourceDetails), opening an issue to investigate this

2025-01-24 17:43 UTC, tdipisa commented
@offtherailz we are ready for a new review. Further PRs will be opened for the agreed rest according to what reported by @allyoucanmap above. Thank you.

2025-01-27 13:32 UTC, allyoucanmap commented
@tdipisa new issues opened and connected to the epic

2025-01-28 15:59 UTC, offtherailz requested changes
Testing the final version with GeoStore I noticed some **grave** instability that blocks the testing of all the components (e.g. in contexts). 


- [ ] New context are not accessible to the owner (probably an error on geostore, or during save: error 500 internal server error. message is: `No message body writer has been found for class it.geosolutions.geostore.core.model.Resource, The URL `http://localhost:8081/rest/geostore/misc/category/name/CONTEXT/resource/name/fgh`
ContentType: application/json` ) the resource can be anyway deleted.
[RecordedVideo.webm](https://github.com/user-attachments/assets/53572033-f13a-4a66-907f-e6a06226e73b)
- [ ] See the video above, the error is written with HTML as plain text 
![image](https://github.com/user-attachments/assets/5e163c8a-012c-44bb-8927-30c340de446b)


## Other minor issues
- [x] Import/Export close is partially hidden.
![image](https://github.com/user-attachments/assets/cce8d823-d59f-4ff5-bf5a-3430fa29d191)

2025-01-28 16:05 UTC, tdipisa commented
Thank you @offtherailz it would be good if you @allyoucanmap can have a look asap maybe with also @axl8713 to quickly investigate and unblock the state of this.

2025-01-28 16:47 UTC, tdipisa commented
@offtherailz this PR should fix the above

2025-01-28 17:34 UTC, offtherailz commented
ok. Now it works. For the rest of the issues, you can decide if procede after merge. 
Allowing me to create contexts, I noticed, apart from the issues above, also that:
- [ ]  context with burger menu are not working anymore. If we don't want to support it anymore, let's remove it the burger menu once for all
- [ ] It should be possible to add the new plugin for top bar in `pluginConfig.json`, maybe added by default.

2025-01-30 09:16 UTC, allyoucanmap commented
@offtherailz I fixed the burger menu problem
>  It should be possible to add the new plugin for top bar in pluginConfig.json, maybe added by default.

for this there is a dedicated issue https://github.com/geosolutions-it/MapStore2/issues/10781

2025-01-30 11:50 UTC, offtherailz approved these changes
It looks working very well now (apart for the separated issues already known).

2025-01-31 10:23 UTC, merged