C125-148: Form control internalization
geosolutions-it/MapStore2 pull request #5215
Opened 2020-05-05 13:02 UTC by dsuren1

## Description
Allow input type=number field to display the number based on locale to denote the decimalSeparator and thousandSeparator. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
**What is the current behavior?**
Input field of type=number doesn't display locale-based result

**What is the new behavior?**
https://github.com/geosolutions-it/austrocontrol-C125/issues/148

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
https://www.w3.org/International/wiki/Locale-based_forms#Tests
https://www.ctrl.blog/entry/html5-input-number-localization.html
Implementation of input type=number with locale differs from browser to browser and also differs in Android. i.e Chrome supports only (.) dot as decimal separator while Firefox supports comma and dot as separators for type=number. 
And the implementation of these entirely depends on the browser and the author, it is highly unreliable to depend on input type=number to achieve this behavior. 

Hence the developed approach implements an input field of  type=number for user input and displays the locale result in input field of type=text. This way we can display the locale based result while maintaining consistency across various browsers and mobile devices.

2020-05-18 07:05 UTC, dsuren1 commented
Hi @offtherailz 
Kindly check my sandbox example implementing,
- Formatting and parsing (both in the current language)
- step (arrows, like in the original number type)
- Handle type (integer, decimal) and limits, number of digits... (min/max)

with the combination of **[react-numeric-input](https://www.npmjs.com/package/react-numeric-input)** library for input field and format/parse with @brightspace-ui/intl library.
Best thing about react-numeric-input it allows both format and parse while maintaining the input field as number with spinners
https://codesandbox.io/s/wispy-paper-c86lo?file=/src/App.js

2020-05-18 12:56 UTC, offtherailz commented
Both the implementation are good. To avoid to include a dependency only for this purpose i should proceed for the native implementation

You can at anytime replace the NumberParser implementation with the `brightspace-ui/intl` one in the future (if you need more features or to avoid maintainence) i think in a transparent way, 
 Make you sure to keep :
- the existing options (maxNumberOfDigits ...) available and all properties and handlers as the normal input type="number"
- Check how does it fit with react-bootstrap (error states for instance) and FeatureEditor inputs NumberEditor

2020-09-04 09:54 UTC, offtherailz requested changes
_note: I did this test aligning the branch with master
- [x] When I edit numeric field in feature grid (open feature grid on state, turn on edit mode, double click on numeric field) I hav ethis error and Ops screen
```
webpack:///./web/client/components/app/StandardRouter.jsx?:135 TypeError: inputNode.focus is not a function
    at EditorContainer.setTextInputFocus (webpack:///./node_modules/react-data-grid/dist/react-data-grid.js?:3804)
    at EditorContainer.componentDidMount (webpack:///./node_modules/react-data-grid/dist/react-data-grid.js?:3454)
    at commitLifeCycles (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:21964)
    at commitLayoutEffects (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:25288)
    at HTMLUnknownElement.callCallback (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:362)
    at Object.invokeGuardedCallbackDev (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:411)
    at invokeGuardedCallback (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:466)
    at commitRootImpl (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:25024)
    at unstable_runWithPriority (webpack:///./node_modules/scheduler/cjs/scheduler.development.js?:815)
    at runWithPriority$2 (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:12188)
    at commitRoot (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:24865)
    at finishSyncRender (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:24251)
    at performSyncWorkOnRoot (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:24223)
    at eval (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:12238)
    at unstable_runWithPriority (webpack:///./node_modules/scheduler/cjs/scheduler.development.js?:815)
    at runWithPriority$2 (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:12188)
onError @ webpack:///./web/client/components/app/StandardRouter.jsx?:135
```
- [x] Maybe is a good idea to format also the numbers in table with a formatter in the table with the same style (I se 12.34 instead of 12,34 in italian but when I edit I could see 12,34 that is misleading)
- [x] As wel as I try to edit geometry details in query panel (North input), I have this error, ops screen:
```
react_devtools_backend.js:2273 TypeError: Cannot read property 'value' of undefined
    at Object.onChange (GeometryDetails.jsx:187)
    at onChange (IntlNumberFormControl.jsx:141)
    at NumericInput._invokeEventCallback (index.js:469)
    at NumericInput.componentDidUpdate (index.js:179)
    at commitLifeCycles (react-dom.development.js:21980)
    at commitLayoutEffects (react-dom.development.js:25288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:362)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:411)
    at invokeGuardedCallback (react-dom.development.js:466)
    at commitRootImpl (react-dom.development.js:25024)
    at unstable_runWithPriority (scheduler.development.js:815)
    at runWithPriority$2 (react-dom.development.js:12188)
    at commitRoot (react-dom.development.js:24865)
    at finishSyncRender (react-dom.development.js:24251)
    at performSyncWorkOnRoot (react-dom.development.js:24223)
    at eval (react-dom.development.js:12238) "
    at ErrorBoundary (webpack:///./node_modules/react-error-boundary/dist/commonjs/ErrorBoundary.js?:36:5)
    at div
    at Router (webpack:///./node_modules/react-router/es/Router.js?:33:5)
    at ConnectedRouter (webpack:///./node_modules/connected-react-router/esm/ConnectedRouter.js?:56:7)
    at ConnectedRouterWithContext (webpack:///./node_modules/connected-react-router/esm/ConnectedRouter.js?:154:25)
    at Connect(ConnectedRouterWithContext) (webpack:///./node_modules/react-redux/es/components/connectAdvanced.js?:151:37)
    at IntlProvider (webpack:///./node_modules/react-intl/lib/index.es.js?:802:9)
    at Localized (webpack:///./web/client/components/I18N/Localized.jsx?:52:5)
    at Theme (webpack:///./web/client/components/theme/Theme.jsx?:108:5)
    at SideEffect(Theme) (webpack:///./node_modules/react-side-effect/lib/index.js?:62:9)
    at Connect(SideEffect(Theme)) (webpack:///./node_modules/react-redux/es/components/connectAdvanced.js?:151:37)
    at div
    at StandardRouter (webpack:///./web/client/components/app/StandardRouter.jsx?:88:5)
    at Connect(StandardRouter) (webpack:///./node_modules/react-redux/es/components/connectAdvanced.js?:151:37)
    at DragDropContext(Connect(StandardRouter)) (webpack:///./node_modules/react-dnd/lib/DragDropContext.js?:81:5)
    at Provider (webpack:///./node_modules/react-redux/es/components/Provider.js?:21:24)
    at StandardApp (webpack:///./web/client/components/app/StandardApp.jsx?:132:5)"
```
- [x] Annotations editor hides last digit of seconds. Maybe this will need a re-check with this pending PR:
https://github.com/geosolutions-it/MapStore2/pull/5776
![image](https://user-images.githubusercontent.com/1279510/92224832-a7781980-eea2-11ea-9dd6-2c608314814b.png)
- [x] Timeline settings: some issues with style:
![image](https://user-images.githubusercontent.com/1279510/92225851-1d30b500-eea4-11ea-850f-736446815d13.png)
- [ ] Legend input in Print options should be only integer, but allows to insert decimals
maybe inside the new styler
- [ ] Please prefer, where possible css precendence rules to !important if you are not overriding existing libraries

- [ ] I Didn't tested 
    - [ ] Measure editor
    - [ ] Dwithin editor (is it used anymore?)
    - [ ] Rules editor
    - [ ] components/style/TextStyler and Text (does it exists or is used anymore?) @allyoucanmap 
For these, we need to check if everything is ok, and / or if they can be removed.

2020-09-28 09:00 UTC, offtherailz commented on web/client/components/I18N/IntlNumberFormControl.jsx
> +class IntlNumberFormControl extends React.Component {
```suggestion
/**
 * Localized Numeric Input. It provides an numeric input value that uses separators (eg. ",",".") as they
 * are used in the current selected language.
 * @prop {string|number} value a numeric value
 * @prop {string|number] defaultValue a value to use as default
 * @prop {function} onChange handler of change event. the argument of this handler is the current value inserted.
 * @prop {number} step the step when you click on arrows (up, down) of the input
 * @prop {function} onBlur event handler on blur event
 */
class IntlNumberFormControl extends React.Component {
```

2020-09-28 09:02 UTC, offtherailz commented on web/client/components/I18N/IntlNumberFormControl.jsx
> +/**
```suggestion
/*
```

2020-09-28 09:34 UTC, offtherailz approved these changes

2020-09-28 09:35 UTC, merged