Settings and Paragraph sections
geosolutions-it/MapStore2 pull request #5906
Opened 2020-09-21 08:43 UTC by ElenaGallo

## Description

Updated the Story Settings section and the Paragraph Section

## Other useful information
Read the Docs [link]()

2020-09-22 12:29 UTC, MV88 requested changes
in paragraph section there is a button image that is not loading
![image](https://user-images.githubusercontent.com/11991428/93881456-3a0c1b80-fcdf-11ea-8116-a7e3e5286d53.png)


by looking at some big images in the doc, i see them as blurred, not nitid. Is it just me?

2020-09-22 12:29 UTC, MV88 commented on docs/user-guide/paragraph-section.md
> +The editor can write a test clicking on the text content and customize it through the [Text Editor Toolbar](text-editor-toolbar.md). A possible result of adding and formatting the text can be the fol
```suggestion
The editor can write a text by clicking on the text content and customize it through the [Text Editor Toolbar](text-editor-toolbar.md). A possible result of adding and formatting the text can be the following:
```

2020-10-08 14:37 UTC, tdipisa requested changes

2020-10-08 14:37 UTC, tdipisa commented on docs/user-guide/story-setting.md
> + * The *Font Family* to choose the default text font present in the whole story: clicking on the search bar a dropdown menu opens to allow selecting the desired font (*Inherit*, *Arial*, *Georgia*, *
We should put a note here (with a link to the related configration in dev guide) to notify that the list of available fonts families can be customized by configuration file.

2020-10-08 14:37 UTC, tdipisa commented on docs/user-guide/story-setting.md
> +* The **Overlay** to choose the default background and text color of the *contents* present in the [Title Section](title-section.md#content) and in the [Immersive Section](immersive-section.md#conten
* The **Overlay** to choose the default background and text color of overlay *contents* ...

Use a better image for the color picker button

2020-10-08 14:37 UTC, tdipisa commented on docs/user-guide/story-setting.md
> +* The **Theme** to choose the default background and text color and the default font of the whole story: clicking on the *Change Color* button <img src="../img/button/color-picker.jpg" class="ms-docb
Use a better image for the color picker button

2020-10-08 14:37 UTC, tdipisa commented on docs/user-guide/story-setting.md
> +* The *Shadow* of the *contents* present in the [Title Section](title-section.md#content) and in the [Immersive Section](immersive-section.md#content): enabling or disabling the shadow:
* The **Shadow** of overlay *contents* present in the [Title Section](title-section.md#content) and in the [Immersive Section](immersive-section.md#content): enabling or disabling the shadow

2020-10-08 14:37 UTC, tdipisa commented on docs/user-guide/story-setting.md
> +* The **Links** to choose the default color of the hyperlink that may be present in the *Text Contents*: clicking on the *Change Color* button <img src="../img/button/color-picker.jpg" class="ms-docb
* The color of **Links**. The story editor can choose the default color of the hyperlink that may be present in the *Text Contents*: clicking on the *Change Color* button <img src="../img/button/color-picker.jpg" class="ms-docbutton"/> a color picker appears to allow selecting the desired color.

Use a better image for the color picker button

2020-10-08 14:37 UTC, tdipisa commented on docs/user-guide/story-setting.md
> +* The *Font Size* of the title: clicking on the search bar a dropdown menu opens to allow selecting the desired size (*14 px*, *16 px*, *18 px*, *24 px*, *28 px*).
The **Font Size** of the title: ...

2020-10-09 15:46 UTC, ElenaGallo commented
@tdipisa in reference to [this](https://github.com/geosolutions-it/MapStore2/pull/5906#pullrequestreview-493402727) comment, if the images of the Story Settings section and the Paragraph Section are now fine I open a new issue to change the blurred images in all the docu

2020-10-12 10:50 UTC, tdipisa requested changes

2020-10-12 10:50 UTC, tdipisa commented on docs/user-guide/story-setting.md
Remove the final :

It is better the following at the end:

... to enable or disable the shadow.

2020-10-12 10:50 UTC, tdipisa commented on docs/user-guide/story-setting.md
> +* The color of **Links**. The story editor can choose the default color of the hyperlink that may be present in the *Text Contents*: clicking on the *Change Color* button <img src="../img/button/colo
remove the final : 

...color picker appears to allow selecting the desired color.

2020-10-12 10:52 UTC, tdipisa commented
@ElenaGallo I've reviewed it without looking at a final build in RtD: the doc of this PR in RtD is not yet updated. Please do that for the next review.

2020-10-13 17:14 UTC, tdipisa requested changes
Did you update the build in RdD? If yes, this image mentioned by @MV88 [here](https://github.com/geosolutions-it/MapStore2/pull/5906#pullrequestreview-493402727) is still broken @ElenaGallo.

2020-10-14 08:40 UTC, ElenaGallo commented
@tdipisa The RdD has been updated and the broken icon has been fixed with [this](https://github.com/geosolutions-it/MapStore2/issues/5948) PR

2020-10-16 09:42 UTC, merged