Fix Font size problems on the story settings panel(#5904)
geosolutions-it/MapStore2 pull request #5907
Opened 2020-09-21 09:23 UTC by AGMETEOR

## Description
Fixes bug described in issue #5904 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#5904 

**What is the new behavior?**
Font size is disabled when title is disabled.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2020-09-21 09:25 UTC, AGMETEOR commented
@ElenaGallo I have pushed a fix in this PR.

2020-09-22 08:15 UTC, allyoucanmap requested changes

2020-09-22 08:15 UTC, allyoucanmap commented on web/client/components/geostory/builder/Settings.jsx
>                          onChange={event => onUpdateSettings("storyTitleFontSize", event.value)}
If you click the x inside the select input an error show up in console

![image](https://user-images.githubusercontent.com/19175505/93858343-4763de80-fcbc-11ea-9527-56d8cadf42ac.png)

I think it's enough to set the `clearable` prop of react-select to false or check when event is undefined

2020-09-24 14:51 UTC, allyoucanmap approved these changes

2020-09-24 14:51 UTC, merged