Measurement edit and store via annotation
geosolutions-it/MapStore2 pull request #5942
Opened 2020-09-28 14:57 UTC by dsuren1

## Description
This PR adds the feature of editing and storing measurement via annotation. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
#5941 

**What is the new behavior?**
- User can navigate to the measurement component from annotation to perform editing of measurement. Edit is restricted to the type of measurement added. 
- User can save the measurement and export the result back to annotation to be saved. (Update)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2020-10-01 08:45 UTC, MV88 requested changes
@tdipisa i think that there is a missing part in the requirements that could be added or that can be added in the future. 
You cannot style differently the various measures you do, just edit geom. it this part of a future improvement?

@dsuren1  the code seems well written and covered by tests. please have a look at my comments to see if I misjudged something 

### BUGS
> The edit mode of measure will not allow to switch between area, bearing or line, it will allow to only edit the existing measurement type and save or close

- [ ] When you go to the measure tool from the annotation, what you can do is just add more measures or clear them, not edit via a selection or so. 
- [ ] When you have multiple measures the type of measure tool are enabled, but no editing is possible

- [ ] when i edit  multiple measures annotation and clear them all, and draw a new one i can see no longer the save button, but i can add as new annotation while in reality i was coming from edit mode of annotation. 

- [ ] if i continue from previous point and add as new i have duplication of annotation the old one and the new one has the same name

- [ ] when i edit an annotation via measurement and i clear measures and close the measure tool or just close the measure tool, the other annotation are not showed again. to show them again i need to select one from the annotation list and go back to the list

- [ ] when importing [this (rename as JSON)](https://github.com/geosolutions-it/MapStore2/files/5310565/measurement.annotations.with.non.measure.ann.json.TXT) exported annotations their style is highlighted. is this intended?
![image](https://user-images.githubusercontent.com/11991428/94786682-90f5ad00-03d1-11eb-9007-35130dec500f.png)

2020-10-01 08:45 UTC, MV88 commented on web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
> +                        const features = editProperties?.type === 'Measure' && this.props.editing.features.filter(f=> f.geometry.type !== 'Point');
can this type be a constant and replace all the usage of the string "Measure"?
like in utils or so put
export const MEASURE_TYPE = "Measure";

2020-10-01 08:45 UTC, MV88 commented on web/client/translations/data.it-IT.json
> +            "saveMeasure": "Salva la misurazione nell'annotazione",
i think is better to use plural by default, please review also other translations

```suggestion
            "saveMeasure": "Salva le misure nell'annotazione",
```

2020-10-01 08:45 UTC, MV88 commented on web/client/translations/data.en-US.json
> +            "saveMeasure": "Save measurement to annotation",
```suggestion
            "saveMeasure": "Save measurements to annotation",
```

2020-10-01 08:45 UTC, MV88 commented on web/client/translations/data.es-ES.json
> +            "editMeasurement": "Editar medida",
```suggestion
            "editMeasurement": "Editar Medida",
```

2020-10-01 08:45 UTC, MV88 commented on web/client/translations/data.it-IT.json
> +            "editMeasurement": "Modifica misurazione",
```suggestion
            "editMeasurement": "Modifica Misura",
```

2020-10-01 09:36 UTC, dsuren1 commented
Thanks @MV88  :)

Kindly find below the answers that should help with the review 
 
> * [ ]  When you go to the measure tool from the annotation, what you can do is just add more measures or clear them, not edit via a selection or so.
> * [ ]  When you have multiple measures the type of measure tool are enabled, but no editing is possible

For this to work, we need to add this config. As this config is project specific, I didn't add this to Mapstore
`{
                "name": "Measure",
                "cfg": {
                  "defaultOptions": {
                    "showAddAsAnnotation": true,
                    "showCoordinateEditor": true
                  }
                }
            }`
> * [ ]  when i edit  multiple measures annotation and clear them all, and draw a new one i can see no longer the save button, but i can add as new annotation while in reality i was coming from edit mode of annotation.

Yes, when you clear, you can only add measure as new annotation. Else you can save the measure as annotation

> * [ ]  if i continue from previous point and add as new i have duplication of annotation the old one and the new one has the same name

It might seem to be duplicate (coz of the name, as this is generated based on the measurement type selected) but the id is new and this is a new annotation

> * [ ]  when i edit an annotation via measurement and i clear measures and close the measure tool or just close the measure tool, the other annotation are not showed again. to show them again i need to select one from the annotation list and go back to the list

I will look into this.

> * [ ]  when importing [this (rename as JSON)](https://github.com/geosolutions-it/MapStore2/files/5310565/measurement.annotations.with.non.measure.ann.json.TXT) exported annotations their style is highlighted. is this intended?
>   ![image](https://user-images.githubusercontent.com/11991428/94786682-90f5ad00-03d1-11eb-9007-35130dec500f.png)

The annotation json has highlight property set to true in it

@MV88  Kindly let me know thoughts

2020-10-01 09:46 UTC, MV88 commented
> Thanks @MV88 :)
> 
> Kindly find below the clarifications that should help with the review
> 
> > * [ ]   When you go to the measure tool from the annotation, what you can do is just add more measures or clear them, not edit via a selection or so.
> > * [ ]   When you have multiple measures the type of measure tool are enabled, but no editing is possible
> 
> For this to work, we need to add this config. As this config is project specific, I didn't add this to Mapstore
> `{ "name": "Measure", "cfg": { "defaultOptions": { "showAddAsAnnotation": true, "showCoordinateEditor": true } } }`

ok, i did not knew it, but this is still weird, probably we should have that flag set to true as default? @tdipisa 

> > * [ ]   when i edit  multiple measures annotation and clear them all, and draw a new one i can see no longer the save button, but i can add as new annotation while in reality i was coming from edit mode of annotation.
> 
> Yes, when you clear, you can only add measure as new annotation. Else you can save the measure as annotation

@tdipisa is this intended ?
i think this is still not clear. when i delete all measures it should not be supposed to create a new annotation, just edit the one 
i think it matters if the measure tool is opened by itself or from annotation plugin.

> > * [ ]   if i continue from previous point and add as new i have duplication of annotation the old one and the new one has the same name
> 
> It might seem to be duplicate (coz of the name, as this is generated based on the measurement type selected) but the id is new and this is a new annotation

no no this was being duplicated, please check it out

> > * [ ]   when i edit an annotation via measurement and i clear measures and close the measure tool or just close the measure tool, the other annotation are not showed again. to show them again i need to select one from the annotation list and go back to the list
> 
> I will look into this.
 
ok

> > * [ ]   when importing [this (rename as JSON)](https://github.com/geosolutions-it/MapStore2/files/5310565/measurement.annotations.with.non.measure.ann.json.TXT) exported annotations their style is highlighted. is this intended?
> >   ![image](https://user-images.githubusercontent.com/11991428/94786682-90f5ad00-03d1-11eb-9007-35130dec500f.png)
> 
> The annotation json has highlight property set to true in it

but when i export it i have no highlight selection active because the mouse in on the export all annotations button.

2020-10-01 10:59 UTC, tdipisa commented
@dsuren1 @MV88 before doing further steps on this I would like to review the tool thogether with @dsuren1.

2020-10-07 09:43 UTC, tdipisa commented
@MV88 this PR is ready for a new review. Thank you.

2020-10-08 09:04 UTC, MV88 requested changes
Hi @dsuren1 

i have found some small problems

- [ ] When i go from annotation to measure tool and then i close the measure tool the draw interaction remains active

- [ ] in the coordinate editor of measure tool the the tooltips for apply changes the tooltips remain visible even if the button is disabled
![image](https://user-images.githubusercontent.com/11991428/95437105-e3484800-0954-11eb-9bf0-3a53419ea178.png)
You can see how @vlt1 has resolved it recently by using a CustomOverlayTrigger

- [ ] there is a problem where you can end up drawing a measure and you can lose the save button 
  - open measure and draw a line
  - add as annotation and edit that line
  - deselect line tool (it remains active and cleares all the measures)
  - deselect again and reselect it or another one
  - draw something --> you see the add as new annotation --> you should seethe save button

@tdipisa as @dsuren1  has suggested me, we can remove the possibility to delesect a tool in the measure tool this will prevent this problem and if you want to clear measures you have the button or the coordinate editor

2020-10-08 09:38 UTC, tdipisa commented
> @tdipisa as @dsuren1 has suggested me, we can remove the possibility to delesect a tool in the measure tool this will prevent this problem and if you want to clear measures you have the button or the coordinate editor

I agree with this

2020-10-09 10:03 UTC, MV88 approved these changes
nice job

2020-10-09 10:05 UTC, merged