#5772: Fixed opacity issues in printing
geosolutions-it/MapStore2 pull request #5972
Opened 2020-10-05 09:30 UTC by offtherailz

## Description
This PR fixes this issue: https://github.com/geosolutions-it/MapStore2/issues/5772#issuecomment-703503849
Moreover fixes other minor issues found in WMS/OSM/Vector layers and printing (opacity = 0 becomes 1).
Added unit tests for all the use cases about opacity

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2020-10-05 14:27 UTC, mbarto requested changes

2020-10-05 14:27 UTC, mbarto commented on web/client/utils/PrintUtils.js
> +                "opacity": layer.opacity || (layer.opacity === 0 ? 0 : 1.0),
Maybe we can extract a function for this repeated check?

2020-10-06 08:44 UTC, mbarto approved these changes

2020-10-06 08:52 UTC, tdipisa commented
@offtherailz can you please backport this to 2020.02.xx? Thank you.

2020-10-06 08:52 UTC, merged