Enable multiple highlighting for OL DrawSupport tool
geosolutions-it/MapStore2 pull request #6107
Opened 2020-10-26 13:26 UTC by AGMETEOR

## Description

This PR enables mutiple highlighting of features by the DrawSupport tool

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe: Enhancement

## Issue

**What is the current behavior?**

#6079 

**What is the new behavior?**

Highlighting multiple features

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2020-10-29 16:49 UTC, MV88 requested changes
Hi @AGMETEOR would be possible to add some more unit tests?

The functionality seems good

2020-10-29 16:49 UTC, MV88 commented on web/client/components/map/openlayers/DrawSupport.jsx
> +                        pre.push({...curr.geometry, properties: curr.properties});
in this case this .push is fine, but be aware that it mutates the pre array, and it cannot be used inside reducers for example
return [...pre, {...curr.geometry, properties: curr.properties}];

2020-11-04 10:30 UTC, tdipisa commented
@AGMETEOR is it ready for a new review?

2020-11-04 11:27 UTC, MV88 approved these changes
LGTM

2020-11-04 11:29 UTC, merged