#6156 WPS Download client
geosolutions-it/MapStore2 pull request #6175
Opened 2020-11-10 09:20 UTC by vlt1

## Description
WPS execute generic implementation with async support and new Download and DownloadEstimator process support. Also existing WPS processes were converted to use the new implementation. Since I'm going to do #6157 immediately I'm going to make all requested changes in the pr for #6157 that will contain both this and ui.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#6156 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

2020-11-10 13:45 UTC, offtherailz requested changes
Hi, 
it looks very good :+1:  . Can you please
- [ ] solve conflicts (and check if things are still working, they refactored the all the utils files to use import/export syntax)
- [ ] document the parts I asked
- [ ] write unit tests for base cases (they are important to verify the functionalities are maintained)
Thank you

2020-11-10 13:45 UTC, offtherailz commented on web/client/observables/wps/common.js
> +import url from 'url';
Can you document these methods to clarify their usage parameters etc ? It could be very useful for future usage.

2020-11-10 13:45 UTC, offtherailz commented on web/client/observables/wps/execute.js
> +export const executeProcessXML = (processIdentifier, dataInputsXML, responseFormXML) =>
Also documenting this, describing the parameters could be very useful.

2020-11-13 16:47 UTC, offtherailz commented
@vlt1 any news on this?

2020-11-17 13:53 UTC, vlt1 commented
closed in favor of #6204

2020-11-17 13:53 UTC, closed without merging