#6168: Filter feature selection in feature grid is disabled when advanced search is closed
geosolutions-it/MapStore2 pull request #6178
Opened 2020-11-10 13:20 UTC by AGMETEOR

## Description

This PR fixes the issue where when the Advanced Search is opened > then feature editor gets automatically closed > then Advanced Search closed, the map can nolonger handle clicks that were added by the `handleClickOnMap` epic

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6168 

**What is the new behavior?**

The map still handles clicks that update filter even when Advanced Search is opened and closed.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2020-11-10 16:48 UTC, MV88 requested changes
it seems the click is not working yet
can you check again ?

![6168 not resolved](https://user-images.githubusercontent.com/11991428/98704391-e207a200-237c-11eb-8fe9-5403a9c23435.gif)

2020-11-10 16:48 UTC, MV88 commented on web/client/epics/featuregrid.js
> +                    // action$.switchMap(() => Rx.Observable.zip([action$.ofType(CLOSE_FEATURE_GRID_CONFIRM), action$.ofType(CLOSE_FEATURE_GRID)])),
please remove this comment

2020-11-11 07:14 UTC, AGMETEOR commented
> it seems the click is not working yet
> can you check again ?
> 
> ![6168 not resolved](https://user-images.githubusercontent.com/11991428/98704391-e207a200-237c-11eb-8fe9-5403a9c23435.gif)

@MV88 I can confirm it works. Please check again.

2020-11-11 15:43 UTC, MV88 approved these changes
apparently a fail to pull the changes made me testing the old code. 

actually it is indeed working. so i'll approve

2020-11-11 15:43 UTC, merged