WPS based Data Export
geosolutions-it/MapStore2 pull request #6204
Opened 2020-11-17 11:19 UTC by vlt1

## Description
WPS based data export implementation. Contains WPS download client.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#6144 
#6156 
#6157 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

2020-11-17 11:20 UTC, vlt1 commented
I will now proceed with adding docs and tests first for #6156 then for #6157

2020-11-18 11:44 UTC, offtherailz commented
@vlt1 can you solve the conflicts ? (we migrated syntax from require to import) they should be very easy to solve.

2020-11-20 08:46 UTC, offtherailz commented on web/client/translations/data.it-IT.json
> +            "tileHeight": "Altezza piastrella",
```suggestion
            "tileWidth": "Larghezza tile",
            "tileHeight": "Altezza tile",
```

2020-11-20 09:46 UTC, offtherailz requested changes
- [ ] see my inline comments
- [ ] when WPS is missing, so using ordinary WFS service the download doesn't work anymore (the `typeName` is sent as `undefined` to the server)
```xml
<wfs:GetFeature service="WFS" version="2.0" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"><wfs:Query typeNames="undefined" ></wfs:Query></wfs:GetFeature>
```
- [ ] Actually if I have WPS I have this list of formats, that is a big limitation over the normal WFS download list. 
![image](https://user-images.githubusercontent.com/1279510/99782999-23851380-2b1a-11eb-9f39-d6ed28d3d46c.png) 

the normal list is this. 

![image](https://user-images.githubusercontent.com/1279510/99783261-7c54ac00-2b1a-11eb-82d0-60fac18457a5.png).  

Moreover, proposing these 4 formats for every layer maybe confusing, because only a sub-set of them is available, depending on the feature type. @giohappy is this the desired behaviour ? 


Minor things:
- [ ] Instead of display "no results found" if the download list is empty, we should show something more clear, like. "Export list is empty"
- [ ] Maybe the two plugins should be merged in one single plugin (the ExportResultsList can not live without download and vice-versa) to simplify the management. 
- [ ] Maybe the download status button should not be always present, but only when I have some downloads in the list.
![image](https://user-images.githubusercontent.com/1279510/99783373-a3ab7900-2b1a-11eb-8e3d-7c43ae33a790.png)

2020-11-20 09:46 UTC, offtherailz commented on web/client/product/plugins.js
> +        VersionPlugin: require('../plugins/Version'),
```suggestion
        VersionPlugin: require('../plugins/Version').default,
```

2020-11-20 09:56 UTC, vlt1 commented
> Actually if I have WPS I have this list of formats, that is a big limitation over the normal WFS download list.

The formats in WPS list are the ones that actually work with WPS.

> Moreover, proposing these 4 formats for every layer maybe confusing, because only a sub-set of them is available, depending on the feature type.

How do I determine if a particular format is available for a specific layer?

2020-11-20 10:04 UTC, offtherailz commented
Thanks @vlt1 for clarification. @tdipisa is this acceptable or should we somehow allow to switch to "WFS only mode" or disable WPS option with a flag? 
One more question for @vlt1 : where the list is stored, to recover it in a second time after browser reload?

2020-11-20 12:09 UTC, tdipisa commented
@vlt1 few more comments below.

**1.** 
>Actually if I have WPS I have this list of formats, that is a big limitation over the normal WFS download list.

At the moment there is no direct way in GeoServer to retrieve the list of mime types supported by the WPS Download process (**this could be an interesting improvement to do in GeoServer in my opinion**). The supported mime types list can be also related to eventual additional extensions in GeoServer (like DXF). For this reason, now we need a default configuration list of mime types defined for the download plugin in MapStore. This configuration must be different for vector and raster layers. Below the list we can use for the default configuration in MapStore:

Vector layers (**a proper label need to be associated to all of them in the MS UI**):

```
- text/xml; subtype=wfs-collection/1.0
- text/xml; subtype=wfs-collection/1.1
- application/wfs-collection-1.0
- application/wfs-collection-1.1
- application/zip
- text/csv
- application/json
```

Raster layers (**a proper label need to be associated to all of them in the MS UI**):

```
- image/tiff 
- application/arcgrid
- image/png
- image/jpeg
```

**2.**
When activating the MS tool for the Download process, we have to check if the layer is a raster layer or a vector layer and then provide only the corresponding list of formats (one of the above lists depending on the layer).

At the moment there is no clean way to understand if a layer is a vector or a raster. Available options are the following ones:

**Option 1**
a. While activating the MS tool, perform a WCS GetCapabilities request to see if the layer is reported there: if yes, the layer is a raster layer
b. If the layer is not reported by GeoServer in the WCS GetCapabilities output, perform a second WFS GetCapabilities request to see if the layer is reported there: if yes, the layer is a vector layer

_**The limitation here are:**_
- Possible performance issues 
- The WCS and WFS can be disabled in GeoServer (in this case the MS tool should inform the user that the Download is not possible) 

**Option 2**
a. While adding a layer from the MS Catalog tool (WMS source), check if the keyword WPS is present and put this information in the layer state so that MS is able to reconize if the layer is a raster or not and so provide the corresponding mime types list accordingly.

_**The limitation here are:**_
- This is a weak check because usually the keyword WPS is automatically set for raster layers by GeoServer, but the keyword can be removed/changed from the GeoServer layer configuration panel

Providing a better way to check if a layer is vector or raster could be a really interesting improvement for GeoServer.
**For the moment, in my opinion, we should opt for Option 2** (as I already told you @vlt1).

**3.**
The download tool must not be available in some cases (e.g. for local vector layers like annotations). Also for this we have to do a preventive check to enable the tool only for WFS/WMS layers (this is an information we have in MS).

2020-11-24 10:12 UTC, offtherailz commented on web/client/plugins/LayerDownload.jsx
> + * @prop {string} defaultSrs Deafult selected srs
```suggestion
 * @prop {string} defaultSrs Default selected srs
```

2020-11-24 10:13 UTC, offtherailz approved these changes
I think is very good. :+1:

2020-11-24 10:34 UTC, merged