#4150: Enable the Identify tool for Map widgets in dashboards
geosolutions-it/MapStore2 pull request #6232
Opened 2020-11-23 13:36 UTC by AGMETEOR

## Description

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2020-12-14 16:03 UTC, MV88 commented
@AGMETEOR please solve conflicts

2020-12-14 16:36 UTC, AGMETEOR commented
> @AGMETEOR please solve conflicts

@MV88 done

2020-12-14 17:44 UTC, MV88 requested changes
@AGMETEOR please check again the pr and the following comments

- [ ] gfi is never working for me
- [ ] on existing dashboard it is disabled, (so if not defined or null it should active imho)

2020-12-15 10:14 UTC, MV88 approved these changes

2020-12-15 10:15 UTC, merged