#6358 include missing plugins in pluginsConfig
geosolutions-it/MapStore2 pull request #6383
Opened 2021-01-12 09:47 UTC by MV88

## Description

Added some of the missing plugins to pluginsConfig.json 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature - config update
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6358

**What is the new behavior?**

those plugins now appear
![image](https://user-images.githubusercontent.com/11991428/104297727-7c8e7980-54c3-11eb-966a-166790aa96f9.png)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-01-12 09:58 UTC, offtherailz commented
I think they should be orgainzed like this:
- [ ] `ExportDataResults` should be hidden and a dependency of `LayerDownload` (hope to merge them soon)
- [ ] `SearchByBookmark` maybe children of `SearchBar`
- [ ] `Swipe` should be children of `TOC`
What do you think matteo?

2021-01-12 14:31 UTC, offtherailz reviewed
It should work, but I think they should be orgainzed like this:
- [ ] `ExportDataResults` should be hidden and a dependency of `LayerDownload` (hope to merge them soon)
- [ ] `SearchByBookmark` maybe children of `SearchBar`
- [ ] `Swipe` should be children of `TOC`
What do you think @MV88 ?

2021-01-12 14:34 UTC, MV88 commented
> It should work, but I think they should be orgainzed like this:
> 
> * [ ]  `ExportDataResults` should be hidden and a dependency of `LayerDownload` (hope to merge them soon)
> * [ ]  `SearchByBookmark` maybe children of `SearchBar`
> * [ ]  `Swipe` should be children of `TOC`
>   What do you think @MV88 ?

thanks, i'll have a look

2021-01-14 17:30 UTC, offtherailz requested changes
the 2 pluginsConfig should be syncronized (the one in template and the one in web/client/

2021-01-15 11:25 UTC, offtherailz commented on project/standard/templates/pluginsConfig.json
> +    },
I think this remained there in error, isn't it?

2021-01-15 11:31 UTC, offtherailz approved these changes

2021-01-15 11:31 UTC, offtherailz commented
Thank you, please backport this to the stable branch

2021-01-15 11:52 UTC, merged

2021-01-19 09:39 UTC, ElenaGallo commented
@MV88 the PR passed the test on dev, please backport this to the stable branch.