Minor improvements to module federation, removing more warnings
geosolutions-it/MapStore2 pull request #6422
Opened 2021-01-19 11:08 UTC by offtherailz

## Description
This PR adds minor improvements to module federation:

- Update proj4 version to avoid warning about export
- add SVG to set of files to import (to avoid build error due to import of some parts of MapStore like "AnnotationUtils".
- remove warnings about lodash (noticed when used).
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-01-21 10:42 UTC, MV88 requested changes
probably is better to add all the shared libs with required version or with requiredVersion: "false"

2021-02-22 17:07 UTC, offtherailz commented
@MV88 we could discuss what libs should be shared and check which ones can be shared with version ( I remember some of them had some issues, for this reason there is that separation).

2021-03-05 08:43 UTC, MV88 approved these changes

2021-03-05 09:18 UTC, merged

2021-03-05 10:10 UTC, tdipisa commented
@offtherailz can you please backport this to 2021.01.xx?