#6452: Custom plugin documentation url for plugin config
geosolutions-it/MapStore2 pull request #6454
Opened 2021-01-25 13:00 UTC by dsuren1

## Description
This commit adds possibility to specify custom documentation url for plugins/extensions imported in Context creator 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

## Issue

**What is the current behavior?**
#6452 

**What is the new behavior?**
The user can specific custom documentation url via **docUrl** props in plugin config. So the custom documentation url will be used in place of default Mapstore documentation url
```
plugins: [
 {
    title: "Plugin title",
    ....
    docUrl: "some_url",
    .....
 }
]
``` 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-01-25 13:30 UTC, offtherailz requested changes
very good :+1: 
- [ ] Can you please document the new configuration in `context-editor-config.md`. As well as it is documented, we can merge.

2021-01-25 13:45 UTC, offtherailz approved these changes

2021-01-25 15:26 UTC, merged

2021-01-25 15:28 UTC, tdipisa commented
@ElenaGallo please let us know as soon as tests on DEV are ok so that we will proceed with the needed backport to 2021.01.xx.

2021-01-26 09:24 UTC, ElenaGallo commented
Test done on DEV. @dsuren1 please, backport the pr to the stable branch