#6495 fix for widgets width when adding them on the map viewer
geosolutions-it/MapStore2 pull request #6500
Opened 2021-02-01 16:02 UTC by MV88

## Description

The fix seems weird, but i tried to compared the widgets when it is added and when it comes back from maximize.. 
and one difference was the presence of those flags in the dataGrid.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6495

**What is the new behavior?**

the initial width of a widget card is 213px which is the requested one
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-02-10 10:07 UTC, allyoucanmap requested changes
I tested this locally and it does not to seem to solve the issue. It seems the widget on map is using two different widthProvider switching them with the `useDefaultWidthProvider` prop. When the WidgetView is in normal state (not maximize) the `useDefaultWidthProvider` is set to true so we are using the [WidthProvider](https://github.com/STRML/react-grid-layout/blob/1.2.0/lib/components/WidthProvider.jsx) of the react-data-grid library that seems to listen only on the mount event and the window resize event. Lately we updated the [resize listener](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/layout/enhancers/gridLayout.jsx#L27) we are using to check for the container width with a different library to avoid the issue to compute also the space of the scrollbar but this new resize detector seems to return undefined width on the first renders. This behaviour is generating a wrong CSS [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Widgets.jsx#L87-L96) and probably when empty the react-grid-layout WidthProvider does not compute the right width on mount while after tirggering the maximize  or resize event we reset the WidthProvider and get the right size of the container.

I think we could approach this width a direct control on the width also for the normal view of the widgets as we are doing with the maximize props https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Widgets.jsx#L60-L100

What do you think @MV88 @offtherailz ?

2021-02-12 09:24 UTC, MV88 commented
@tdipisa this pr also fixes this problem by showing only text when an empty text widget has been added

https://user-images.githubusercontent.com/11991428/107750541-7850b880-6d1c-11eb-9896-00b35ff6ff3f.mp4

2021-02-18 12:04 UTC, allyoucanmap approved these changes

2021-02-18 12:05 UTC, allyoucanmap commented
> @tdipisa this pr also fixes this problem by showing only text when an empty text widget has been added
> 
>  empty.text.widget.problem.mp4

@tdipisa  I approved the PR, let me know if I can merge it or not

2021-02-18 12:07 UTC, merged

2021-02-18 12:08 UTC, tdipisa commented
@ElenaGallo please test this in DEV as soon as deployed and let us know if we can backport to 2021.01.xx

2021-02-18 14:57 UTC, ElenaGallo commented
@MV88 please backport this Pr to the stable branch