#6561: SearchServicesConfig toggle button is visible in the search bar even if the plugin is not in localConfig
geosolutions-it/MapStore2 pull request #6562
Opened 2021-02-22 12:01 UTC by allyoucanmap

## Description

This PR makes pluggable the toggle button of SearchServicesConfig.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#6561

**What is the new behavior?**

The toggle button is removed together with the plugin

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

## Other useful information

2021-02-25 15:39 UTC, MV88 requested changes
please see my question.

The PR is a good a example and a starting point on how plugins or part of them (components, buttons, menu items) can be plugged in other containers :)

2021-02-25 15:39 UTC, MV88 commented on web/client/plugins/SearchServicesConfig.jsx
> +            target: 'button',
do we need a name here?

2021-02-26 09:09 UTC, MV88 commented on web/client/plugins/SearchServicesConfig.jsx
> +            target: 'button',
so here the name of the component if not specified is inherited from the plugin

2021-02-26 09:14 UTC, MV88 approved these changes

2021-03-01 08:42 UTC, MV88 approved these changes

2021-03-01 10:00 UTC, merged

2021-03-01 10:01 UTC, MV88 commented
this will need a backport when release 2021.01.01 is out

2021-03-05 09:59 UTC, tdipisa commented
@ElenaGallo can you please check this and let us know if we can proceed with the backport to 2021.01.xx?

2021-03-05 13:08 UTC, ElenaGallo commented
@allyoucanmap test done, please backport this PR to the stable branch, thx.