5110: The loading gear and the counter problem on Map Widget Panel
geosolutions-it/MapStore2 pull request #6668
Opened 2021-03-18 12:31 UTC by MuhweziDeo

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

#5110 

**What is the current behavior?**
The loading gear and the counter is aligned on the bottom bar

**What is the new behavior?**
The loading gear is not aligned whit the counter

## Breaking change

**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-03-25 14:49 UTC, offtherailz requested changes

2021-03-25 14:49 UTC, offtherailz commented on web/client/themes/default/less/loaders.less
> +    margin: 8px 8px 0 4px;
here you are chaning the global inline loader.
```suggestion
```
This has not effect

2021-03-25 14:49 UTC, offtherailz commented on web/client/themes/default/less/widget.less
> +                    display: flex;
Please align the loader to the right, and proper center vertically both the text and the loader.
The height of the footer should not change when loader appears.

2021-03-26 11:38 UTC, offtherailz requested changes
It works well. 
- [x] padding of 5px for catalog footer is not needed, please remove.
- [x] Please move the inline style in less files.

2021-03-31 10:19 UTC, MuhweziDeo commented
> I simplified your changes. @MuhweziDeo please check the changes and do a final test.

@offtherailz This works the same as before just tested it. Thanks

2021-04-02 12:29 UTC, offtherailz approved these changes

2021-04-02 12:29 UTC, merged