#6682 Fix infinite loading in map templates
geosolutions-it/MapStore2 pull request #6683
Opened 2021-03-22 10:26 UTC by offtherailz

## Description
When the list of allowed templates is empty, the UI doesn't turn off loading spinner. This fix loads the empty results array and turn off loading spinner, when no template is allowed.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6682

**What is the new behavior?**
The users see an empty view instead of an infinite loading spinner

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-03-22 11:45 UTC, MV88 requested changes
can you see why other tests are failing?
see [here](https://travis-ci.org/github/geosolutions-it/MapStore2/builds/763918175)

2021-03-22 15:46 UTC, MV88 approved these changes

2021-03-22 15:49 UTC, merged

2021-03-22 15:50 UTC, MV88 commented
@ElenaGallo please test this in DEV and let us know if we can backport to 2021.01.xx

2021-03-23 14:45 UTC, ElenaGallo commented
@offtherailz test done, please backport this to the stable branch. Thank you