#6721 avoid errors for localized titles in splitMapAndLayers function
geosolutions-it/MapStore2 pull request #6725
Opened 2021-04-01 09:48 UTC by offtherailz

## Description
The issue was cause by a `replace` function called on an object. the issue can be solved by modifying a little the function to avoid this error.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6721

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-04-02 08:39 UTC, MV88 requested changes
only one little thing 
the rest is good

2021-04-02 08:39 UTC, MV88 commented on web/client/utils/__tests__/LayersUtils-test.js
> +            expect(layers).toExist();
```suggestion
            expect(map).toBeTruthy();
            expect(layers).toBeTruthy();
```

2021-04-02 08:54 UTC, MV88 approved these changes

2021-04-02 08:56 UTC, merged

2021-04-08 11:09 UTC, tdipisa commented
@ElenaGallo please test this in DEV and let us know if we canbackport to 2021.01.xx.

2021-04-08 12:53 UTC, ElenaGallo commented
@offtherailz test done, please backport this to the stable branch. Thank you