6723: Error creating circle annotation
geosolutions-it/MapStore2 pull request #6737
Opened 2021-04-02 13:18 UTC by MuhweziDeo

… @turf/circle

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## 6723

**What is the current behavior?**
MapStore crashes before having the chance to enter a radius while entering Lat and Lng

#<6723>

**What is the new behavior?**
It should be possible to enter coordinates before entering a radius without throwing an error.

#### how the issue was resolved
I found that the package https://www.npmjs.com/package/@turf/turf causes the app to crash at this line https://github.com/geosolutions-it/MapStore2/blob/master/web/client/reducers/annotations.js#L158. It's my guess that `circle` needs the radius. Without radius it causes the app to crash. So wrapping it a `try-catch solves the problem

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-04-08 09:41 UTC, MV88 requested changes
Hi @MuhweziDeo 

is there a way to avoid the problem instead doing this try catch just to prevent the app from crashing. also in the catch you are not doing anything and the console is not helping the user.

can we use a very little value for radius if not defined so even it it is drawn then it is not visible
please make a few tries and let me know

i would

2021-04-08 11:13 UTC, MuhweziDeo commented
> Hi @MuhweziDeo
> 
> is there a way to avoid the problem instead doing this try catch just to prevent the app from crashing. also in the catch you are not doing anything and the console is not helping the user.
> 
> can we use a very little value for radius if not defined so even it it is drawn then it is not visible
> please make a few tries and let me know
> 
> i would

Okay let try that thanks

2021-04-08 14:49 UTC, MV88 requested changes
can you add a unit test?

2021-04-08 14:49 UTC, MV88 commented on web/client/reducers/annotations.js
> +                // this try catch prevents the app from crashing when there is no radius maybe we can use a default value for radius incase action.radius === undefined
```suggestion

```

2021-04-08 15:01 UTC, MuhweziDeo commented on web/client/reducers/annotations.js
> +                // this try catch prevents the app from crashing when there is no radius maybe we can use a default value for radius incase action.radius === undefined
okay

2021-04-13 15:09 UTC, MV88 approved these changes

2021-04-13 15:09 UTC, merged

2021-04-13 15:09 UTC, MV88 commented
@ElenaGallo can you please test this in DEV?

2021-04-14 14:23 UTC, ElenaGallo commented
@MuhweziDeo test done, please backport this PR to the stable branch. Thank you