#6314: Add standard project scripts to @mapstore/project
geosolutions-it/MapStore2 pull request #6738
Opened 2021-04-02 20:52 UTC by MV88

## Description

This Draft PR completes the implementations needed to make the [@mapstore/project](https://github.com/geosolutions-it/mapstore-project) work.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6314

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [ ] No

## Other useful information

2021-04-06 17:10 UTC, MV88 commented
@mbarto @offtherailz can you do a final check, i have tested this in a local container and it was working

2021-04-07 07:25 UTC, allyoucanmap approved these changes

2021-04-09 09:35 UTC, offtherailz commented on web/client/test-resources/mergeConfigs/02_austro_stateVars.patch.json
> +    },
Do not quote existing services in tests

2021-04-09 09:35 UTC, offtherailz commented on web/client/test-resources/mergeConfigs/02_austro_stateVars.patch.json
> +[
do not quote customer names

2021-04-09 09:41 UTC, offtherailz requested changes
Personally I didn't tested, but to parallelize the work, I leave my comments ( I leave my colleques the testing phase)

need to document
- [ ] new paths (directories changes, updating existing documentation)
- [ ] patch system 
- [ ] changes, if any, with back-end configs (I've seen adding ldap files, spring security, so update also this part if needed)
- [ ] build variables, possibly
- [ ] migration, if any

Remove from tests reference to austro or any existing service (also geo-solutions ones, if possible)

2021-04-21 08:17 UTC, allyoucanmap approved these changes

2021-04-21 09:21 UTC, offtherailz requested changes
I reviewed only the documentation. Please apply my suggestions where possible.

2021-04-21 09:21 UTC, offtherailz commented on docs/developer-guide/mapstore-migration-guide.md
> +See [this](https://github.com/geosolutions-it/MapStore2/pull/6738/files) pr for more details
```suggestion

During this release MapStore changed a lot the project system. The first phase of this migration has been identified by [this](https://github.com/geosolutions-it/MapStore2/pull/6738/files) pull request. In this PR we are supporting the backward compatibility as much as possible. Anyway this migration guidelines will change accordingly to the new system soon. 
```

2021-04-21 09:21 UTC, offtherailz commented on docs/developer-guide/mapstore-migration-guide.md
> +- **web/pom.xml**
```suggestion
Back-end has been reorganized 
In particular: 
- all the java code has been moved from `web/src/` to the `java/` and `product/` directories (and `release`, already existing).
- `mapstore-backend` has been renamed into `mapstore-services`.

Check the changes in pom.xml to update. (future evolution of the project will avoid you to keep your own copies of the pom files as much as possible, for this reasons these migration guidelines will change soon.)

- **pom.xml**
- **java/web/pom.xml**
```

2021-04-21 16:41 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
> +**Some key files have been moved to `configs` folder like:**
yes they needs to be moved or the app will not work and when writing them i am using the vs code preview

2021-04-22 07:34 UTC, allyoucanmap approved these changes

2021-04-22 08:17 UTC, merged