#6729: Aeronautical field limit max input for fields
geosolutions-it/MapStore2 pull request #6753
Opened 2021-04-08 14:09 UTC by dsuren1

## Description
This PR limits the aeronautical fields to max value of each field, so the auto formatting of the fields won't happen on typing values greater than the respective fields' max limit

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**
#6729 

**What is the new behavior?**
- Each field in the aeronautical coordinates is limited to its max field value. (ex: Degrees - 89/179, minutes and seconds to 59), such that it prevents auto formatting of the fields value on typing
- The auto format happens when user switches from decimal to aeronautical to allow conversion

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-04-13 13:12 UTC, MV88 requested changes
i have found a way to trigger auto formatting also after having switched to aeronatical
see here, where i keep inserting 9 in decimal positions

https://user-images.githubusercontent.com/11991428/114558224-bf025680-9c6a-11eb-80ca-87fe18dad059.mp4

2021-04-15 13:59 UTC, MV88 approved these changes

2021-04-15 13:59 UTC, merged

2021-04-15 13:59 UTC, MV88 commented
@ElenaGallo you can test

2021-04-15 15:47 UTC, ElenaGallo commented
Test done, @dsuren1 please backport this to the stable branch.