#6804 fix catalog crash for specific names
geosolutions-it/MapStore2 pull request #6805
Opened 2021-04-23 16:34 UTC by MV88

## Description

fixes the problem of adding services with particular names

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6804 

**What is the new behavior?**

no crash happen and the service is added

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-04-29 12:38 UTC, offtherailz requested changes
Investigating a little I noticed that this `getMessageById` is present with the only purpose of localizing string for "Default Background".

See https://github.com/geosolutions-it/MapStore2/pull/4343/files#diff-8563d597ea4e72ceda8010f755ca595b2b47cb058b203266a6308763a9ce880eR365

We don't want to localize in general the catalog title or we may encounter some issues due to strings mistmatch).

So a fix is simply to localize only the default_empty_background service entry, leaving untouched the rest. 

something like 
```javascript
startKeys.map( localize here).concat(
   other services.map (...this time don't localize)
)
```

2021-04-30 09:41 UTC, offtherailz approved these changes

2021-04-30 09:46 UTC, tdipisa commented
@ElenaGallo please test this is dev and let us know for the backport.

2021-04-30 09:46 UTC, merged

2021-04-30 10:12 UTC, ElenaGallo commented
Test done, @MV88 please backport this PR