#6892 Fix geometry type bug in wfs layer style panel
geosolutions-it/MapStore2 pull request #6893
Opened 2021-05-21 04:13 UTC by dhlambert

## Description
Adds a conditional to the `SimpleVectorTileEditor` to fail gracefully with an error message when the geometry type is not supported.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [X] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6892

**What is the new behavior?**

Rather than crashing the application a message is shown to the user saying that the style editor is not supported for the geometry type.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-06-03 10:32 UTC, dsuren1 commented
Thanks for the contribution @dhlambert. Let me review it and get back with feedback if any.

2021-06-03 12:01 UTC, dsuren1 requested changes
Fix works fine. Thanks.

However, it would be nice if you could add some unit test cases, to support the fix, for `SimpleVectorStyleEditor` component [here](https://github.com/geosolutions-it/MapStore2/tree/master/web/client/plugins/tocitemssettings/__tests__)

2021-06-04 01:32 UTC, dhlambert commented on web/client/plugins/tocitemssettings/SimpleVectorStyleEditor.jsx
> +        </React.Fragment>);
Thanks for the review @dsuren1 . I'll fix those things up.

2021-06-08 22:38 UTC, dhlambert commented
Hi @dsuren1, those review changes should be fixed now. 

I'm not a native speaker of those additional languages listed but I've attempted to add those localized strings as suggested. I've been able to get some assistance in translating de-DE and it-IT, but es-ES and fr-FR have been translated using Google translate, is this ok? Feel free to update if necessary.

2021-06-09 12:42 UTC, dsuren1 commented
Thanks @dhlambert.
I have made some small changes to unit test cases to align with the app's practices.

2021-06-09 12:53 UTC, dsuren1 approved these changes

2021-06-09 13:53 UTC, merged

2021-06-09 13:54 UTC, dsuren1 commented
Hi @ElenaGallo 
This [issue ](https://github.com/geosolutions-it/MapStore2/issues/6892)is ready for testing in DEV

2021-06-09 15:42 UTC, ElenaGallo commented
The test passed, @dhlambert please backport this PR to the stable branch, the 2021.01.xx . Thank tyou