#6871 fixing the visibility of map detail panel which toggling 3D
geosolutions-it/MapStore2 pull request #6903
Opened 2021-05-25 08:04 UTC by QSafariallahkheili

## Description

It solves the conflict between tutorial and detail panel
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6871

**What is the new behavior?**

It solves the conflict between tutorial and detail panel when toggling on 3D
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-05-25 09:11 UTC, MV88 requested changes
there is a problem also when you open directly the cesium viewer and not only when passing to 3D from 2D

if you open directly this url the problem of the conflict is still present
http://localhost:8081/?debug=true#/viewer/cesium/34133

@QSafariallahkheili 
in the epic **storeDetailsInfoEpic** when we choose to dispatch the openDetailsPanel we first need to check if a tutorial is in progress by checking its state
some something like

```js
const isTutorialRunning = store.getState().tutorial.run;
return Rx.Observable.of(
                            detailsLoaded(mapId, details.value, detailsSettings),
                            ...(detailsSettings.showAtStartup && !isTutorialRunning ? [openDetailsPanel()] : [])
                        );
``

please try to replicate what i'm reporting and then try the suggested fix

2021-05-25 09:11 UTC, MV88 commented on web/client/actions/details.js
> +export const openDetailsPanel = () => {
can you revert this change since its not needed?

2021-05-25 09:11 UTC, MV88 commented on web/client/epics/globeswitcher.js
> +            // two actions are called after toggling to 3D
this comment is superflous, please remove it
```suggestion
            // two actions are called after toggling to 3D
```

2021-05-25 09:11 UTC, MV88 commented on web/client/epics/tutorial.js
> +export const openDetailsPanelEpic = (action$, store) =>
can you try to add a unit test for this?

2021-05-27 08:17 UTC, MV88 approved these changes

2021-05-27 08:19 UTC, MV88 requested changes
there are tests that are failing,
can you check them locally?

you can run  first time "npm test"

and see which tests are failing and why

2021-05-27 13:03 UTC, MV88 approved these changes

2021-05-27 13:04 UTC, merged

2021-06-04 09:43 UTC, ElenaGallo commented
@QSafariallahkheili a note after testing this issue:

If the tutorial is opened from the Options menu (it does not open at startup), the Details tool will also open

**How to rerpoduce**
- Open 
- Click on 3D 
- Close the Tutorial
- Click on Options menu
- Click on Tutorial
- Click Next to the end of the tutorial


*Current Reuslt*
Opening the tutorial from the Options menu should not open the details tool as well