#6871 - Auto-opening of details panel
geosolutions-it/MapStore2 pull request #6973
Opened 2021-06-11 15:28 UTC by QSafariallahkheili

## Description
solves the auto-opening of details panel when toggling 3D

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6871 

**What is the new behavior?**
See the description

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-06-14 15:29 UTC, MV88 commented
@QSafariallahkheili the build is failing because of some tests,
can you please check the log of travis [here](https://travis-ci.org/github/geosolutions-it/MapStore2/jobs/774284096#L2859)

```
Firefox 89.0 (Linux x86_64) details epics tests test closeDetailsPanel FAILED
	Expected 'SET_CONTROL_PROPERTY' to be 'TOGGLE_CONTROL'
	assert@webpack://mapstore2/./node_modules/expect/lib/assert.js?:29:9
	toBe@webpack://mapstore2/./node_modules/expect/lib/Expectation.js?:70:28
	@webpack://mapstore2/./web/client/epics/__tests__/details-test.js?:104:72
```

2021-06-15 06:37 UTC, MV88 requested changes

2021-06-15 06:37 UTC, MV88 commented on web/client/epics/__tests__/details-test.js
> +    it.('test closeDetailsPanel', (done) => {
```suggestion
    it('test closeDetailsPanel', (done) => {
```

2021-06-16 12:27 UTC, MV88 approved these changes

2021-06-16 12:27 UTC, merged

2021-06-16 12:28 UTC, MV88 commented
@ElenaGallo please test in DEV

@QSafariallahkheili please prepare the backport to 2021.01.xx

2021-06-17 12:25 UTC, ElenaGallo commented
@QSafariallahkheili test done, the PR can be backported. Thanks

2021-06-18 07:35 UTC, tdipisa commented
@QSafariallahkheili can you please backport this to stable branch?