#6853 Fix crash when using an unescaped template
geosolutions-it/MapStore2 pull request #7008
Opened 2021-06-22 10:12 UTC by MV88

## Description

The problem was related to the name of the feature attributes, especially if they contained a - like `${ properties.data-name }`
the crash happened inside template of lodash here
https://github.com/geosolutions-it/MapStore2/blob/b7b366d7d35491f659e4946dec800faff7cca887/web/client/components/data/identify/viewers/TemplateViewer.jsx#L19
So what i did is to prevent the crash with a try catch and to use square bracket notation if it finds a minus inside templates segments

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6853

**What is the new behavior?**

no crash
the minus properties are managed correctly even if already escaped

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-06-24 09:28 UTC, offtherailz requested changes
I suggest to 
- [ ] improve the hints about the correct syntax to use in the template. adding `${properties.id}, the name is ${properties['attribute-name'] 
![image](https://user-images.githubusercontent.com/1279510/123239279-80491200-d4df-11eb-8549-308d39d1839a.png)

- [ ] show an error in case of usage of `properties.attribute-name`.

This helps in the future to support `-` for operations, for instance, instead of supporting names like `properties.attribute-name` that are not compliant with any template language.

The correct syntax to use is `properties['attribute-name']`
 @giohappy

2021-06-24 09:28 UTC, offtherailz commented on web/client/utils/TemplateUtils.js
> +        if (varReplaced.indexOf("-") !== -1) {
I should not do this, but improve error messages and add a suggestion about the correct syntax.

2021-06-24 09:28 UTC, offtherailz commented on web/client/components/data/identify/viewers/TemplateViewer.jsx
> +                html = "There was an error parsing the template, please check if the template contains a minus -, like ${ properties.data-array } ";
localize this message

2021-06-24 13:14 UTC, offtherailz commented on web/client/translations/data.it-IT.json
> +            "templateError": "Si è verificato un errore durante l'applicazione del formato del modello alle informazioni restituite dal server, controlla il formato del modello",
```suggestion
            "templateError": "Si è verificato un errore durante l'applicazione del template alle informazioni restituite dal server, controlla il template.",
```

2021-06-24 13:16 UTC, offtherailz commented on web/client/translations/data.en-US.json
> +            "templateError": "There was an error applying the template format to the information returned by the server, please check the template",
```suggestion
            "templateError": "There was an error applying the template to the information returned by the server, please check the template",
```

2021-06-24 13:17 UTC, offtherailz commented on web/client/translations/data.es-ES.json
> +            "templateError": "Hubo un error al aplicar el formato de la plantilla a la información devuelta por el servidor, verifique la plantilla",
```suggestion
            "templateError": "Hubo un error al aplicar la plantilla a la información devuelta por el servidor, verifique la plantilla",
```

2021-06-24 13:17 UTC, offtherailz commented on web/client/translations/data.fr-FR.json
> +            "templateError": "Une erreur s'est produite lors de l'application du format du modèle aux informations renvoyées par le serveur, veuillez vérifier le modèle",
```suggestion
            "templateError": "Une erreur s'est produite lors de l'application du modèle aux informations renvoyées par le serveur, veuillez vérifier le modèle",
```

2021-06-24 13:18 UTC, offtherailz commented on web/client/translations/data.de-DE.json
> +            "templateError": "Beim Anwenden des Vorlagenformats auf die vom Server zurückgegebenen Informationen ist ein Fehler aufgetreten. Bitte überprüfen Sie die Vorlage",
```suggestion
            "templateError": "Beim Anwenden der Vorlage auf die vom Server zurückgegebenen Informationen ist ein Fehler aufgetreten. Bitte überprüfen Sie die Vorlage",
```

2021-06-24 13:54 UTC, offtherailz approved these changes
The code is ok for me. Anyway I can not replicate the error message. Please check if the error message is effectively shown.
Approved by my side.

2021-06-24 15:09 UTC, merged

2021-06-24 15:10 UTC, tdipisa commented
@ElenaGallo please test this in DEV and let us know if we can backport.

2021-06-25 08:13 UTC, ElenaGallo commented
@MV88 test passed, please backport this PR to the stable branch