Remove floppy save icon #6879
geosolutions-it/MapStore2 pull request #7028
Opened 2021-06-24 16:59 UTC by MuhweziDeo

## Description

This introduces an option to hide save Icon in TocItemSettings 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

## Issue

**What is the current behavior?**
There is no way to hide the save Icon in TOCItemSettings
#<issue>

**What is the new behavior?**
Introduces a prop to hide the save icon maybe its just enough to remove setting a default value for onSave
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-06-25 07:39 UTC, tdipisa commented
@MuhweziDeo I saw this in description:

2021-06-25 07:51 UTC, offtherailz commented
Moreover @MuhweziDeo I think we should remove also the prompt shown when you edit something, than click on "X" that asks you to confirm save. 
![image](https://user-images.githubusercontent.com/1279510/123390164-e8106300-d59a-11eb-9745-da8250b727bf.png)

Agree @tdipisa ?

2021-06-25 07:56 UTC, MuhweziDeo commented
> @MuhweziDeo I saw this in description:
> 
> > This introduces an option to hide save Icon in TocItemSettings
> 
> It is not needed here to introduce a config option to hide the button. It need to be completely removed by making transparent the update of the app state when the user change something in layer settings. See my comment [here](https://github.com/geosolutions-it/mapstore2/issues/6879#issuecomment-844000343) in the issue.

My bad got you now

2021-06-25 08:29 UTC, offtherailz commented
So summarising:
 - Remove the save button
 - Remove the `tocItemsSettings` enhancer that takes care of saving the old values to restore them (incuded the parts about the confirm modal on close), and remap methods if needed.

Ok @MuhweziDeo ?

2021-06-25 10:31 UTC, MuhweziDeo commented
> So summarising:
> 
> * [ ]  Remove the save button
> * [ ]  Remove the `tocItemsSettings` enhancer that takes care of saving the old values to restore them (incuded the parts about the confirm modal on close), and remap methods if needed.
> 
> Ok @MuhweziDeo ?

ok let me update my implementation

2021-06-28 14:52 UTC, dsuren1 commented on web/client/components/TOC/enhancers/tocItemsSettings.js
> +        onClose: ({ onUpdateInitialSettings = () => {}, onHideSettings = () => {} }) => (forceClose, tabsCloseActions = []) => {
```suggestion
        onClose: ({ onUpdateInitialSettings = () => {}, onHideSettings = () => {} }) => (tabsCloseActions = []) => {
```
I think `forceClose` is not required anymore. Also kindly make changes in TOCItemSettings `onClose` call and corresponding unit tests in `tocItemSettings`

2021-06-28 14:58 UTC, dsuren1 commented on web/client/components/TOC/enhancers/tocItemsSettings.js
> -            onUpdateOriginalSettings({});
I think `onUpdateOriginalSettings` should be called to reset on `onClose` too

2021-06-28 15:00 UTC, dsuren1 requested changes
Looks fine to me. However I have few minor changes requested as above. Kindly see to it

2021-06-29 10:38 UTC, dsuren1 approved these changes
LGTM

2021-06-29 10:39 UTC, merged

2021-06-29 10:41 UTC, dsuren1 commented
Hi @ElenaGallo. This issue is ready for testing in DEV