#6993: GeoCarousel section for geostory
geosolutions-it/MapStore2 pull request #7095
Opened 2021-07-12 08:39 UTC by dsuren1

## Description
This PR adds commits to implement new feature section in Geostory called 'GeoCarousel'

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
#6993 

**What is the new behavior?**
Refer the issue for detailed behavior (#6993 & https://github.com/geosolutions-it/MapStore2/issues/6993#issuecomment-874031648)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-07-13 09:11 UTC, allyoucanmap requested changes
Some layout issues:

- [ ] in edit mode the scrollbar in the text box does not work

https://user-images.githubusercontent.com/19175505/125422122-38f759ea-04c0-412d-8362-c320ac8a1b97.mp4

- [ ] Somehow the title is not centered in the cover section
- PR branch:

![image](https://user-images.githubusercontent.com/19175505/125422352-1b1133bf-4104-421e-a442-2ffcaa8da076.png)

  - dev
  
![image](https://user-images.githubusercontent.com/19175505/125423888-bca17b59-0629-4c42-8ecf-f9d330b5cd94.png)

2021-07-14 06:15 UTC, dsuren1 commented on package.json
> +    "react-items-carousel": "2.8.0",
react-swipeable doesn't seems to support multiple items per view ([Ref](https://github.com/oliviertassinari/react-swipeable-views/issues/185)). That's why I went with a simple multiple item view carousel lib with swipeable feature in it.

2021-07-14 06:15 UTC, dsuren1 commented on web/client/components/geostory/builder/SectionsPreview.jsx
> -                    // visible: type !== 'immersive',
It is a removed line

2021-07-14 06:19 UTC, dsuren1 commented on web/client/components/geostory/contents/Column.jsx
> +        ...overrideTools
I agree. It was lame of me to not use overridetools props instead :)  I will modify the overridetools props to a function and modify the paragraph section accordingly

2021-07-14 06:20 UTC, dsuren1 commented on web/client/components/geostory/contents/carousel/Carousel.jsx
> +                {editable && <ContentToolbar bsStyle={'primary'} addDisabled={!isMapBackground || disableAddItem()}
Agreed. I just referred the screenshot in the issue and went with primary, sure, I will use default instead.

2021-07-14 06:21 UTC, dsuren1 commented on web/client/components/geostory/contents/carousel/Carousel.jsx
> +                <Carousel
I will make the no of items responsive according to container width

2021-07-14 06:28 UTC, dsuren1 commented on web/client/components/geostory/contents/ContentToolbar.jsx
> +        disabled: editMap || addDisabled,
This requirement was a feedback requested later during the development. Kindly refer to this comment https://github.com/geosolutions-it/MapStore2/issues/6993#issuecomment-874031648

2021-07-14 06:33 UTC, dsuren1 commented
> * [ ]  in edit mode the scrollbar in the text box does not work

The scrollbar appears only in view mode for the whole section content, as I thought during edit, it will make the modification space limited when showing a scrollbar in each inner content of section and making the editing process constraints. Kindly let me your thoughts?

2021-07-14 07:27 UTC, allyoucanmap commented on web/client/components/geostory/builder/SectionsPreview.jsx
> -                    // visible: type !== 'immersive',
you are right, sorry

2021-07-15 08:03 UTC, allyoucanmap approved these changes
> The scrollbar appears only in view mode for the whole section content, as I thought during edit, it will make the modification space limited when showing a scrollbar in each inner content of section and making the editing process constraints. Kindly let me your thoughts?

In my opinion the layout of sections should be consistent between edit and view mode as much as possible. If we allow this section to extend we get this behaviour that should be avoided for this kind of section:


https://user-images.githubusercontent.com/19175505/125750055-4826b377-74ff-4be4-a804-59bf1d835f26.mp4

We will fix this in a separated issue with the following improvements:

- [ ] scrollbar also in edit mode (maybe we need to introduce a different class because now is using the immersive one)

![image](https://user-images.githubusercontent.com/19175505/125751756-dec80f66-772f-4e8a-8480-392ad03dfc72.png)


- [ ] if the title is missing the popup should not be visible

![image](https://user-images.githubusercontent.com/19175505/125751806-e206bc84-5a1f-444a-ad14-d9c7d441ce05.png)

- [ ] improve the draw marker UX with some message to explain that a user need to click on the map

![image](https://user-images.githubusercontent.com/19175505/125751972-ad2521ea-df6a-4ea6-82df-62c6ee8074d1.png)

2021-07-15 08:03 UTC, merged

2021-07-15 08:04 UTC, allyoucanmap commented
please @dsuren1 backport this improvement on the branch https://github.com/geosolutions-it/MapStore2/tree/geonode-mapstore-client-2.1.x