#7108, #7119: Improve Geocarousel section
geosolutions-it/MapStore2 pull request #7130
Opened 2021-07-21 08:43 UTC by allyoucanmap

## Description

This PR improve the carousel sections of GeoStory by:

- refactoring the json structure to centralize the map configuration
- refactoring the carousel menu to align it to the navigation menu behaviours and avoid compressed cards
- fix bugs listed here https://github.com/geosolutions-it/MapStore2/issues/6993#issuecomment-880806131
- add icon for this type of section

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#7108
#7119

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

## Other useful information

2021-07-21 11:45 UTC, allyoucanmap commented on web/client/translations/data.en-US.json
> +            "carouselPlaceMarkerInfo": "Click anywhere on the map to place or reposition the marker",
```suggestion
            "carouselAddMapInfo": "Add a map background",
            "carouselAddItemInfo": "Add a new marker location for the selected content",
            "carouselPlaceMarkerInfo": "Click on the map to add a new marker",
```

cc @tdipisa

2021-07-21 12:02 UTC, allyoucanmap commented on web/client/translations/data.de-DE.json
> +            "carouselPlaceMarkerInfo": "Klicken Sie auf eine beliebige Stelle auf der Karte, um die Markierung zu platzieren oder neu zu positionieren",
```suggestion
            "carouselAddMapInfo": "Hinzufügen einer Hintergrundkarte",
            "carouselAddItemInfo": "Neue Markierung für das ausgewählte Karussellelement hinzufügen",
            "carouselPlaceMarkerInfo": "Klicken Sie auf die Karte, um eine neue Markierung hinzuzufügen",
```

2021-07-21 12:02 UTC, allyoucanmap commented on web/client/translations/data.es-ES.json
> +            "carouselPlaceMarkerInfo": "Haga clic en cualquier lugar del mapa para colocar o reposicionar el marcador",
```suggestion
            "carouselAddMapInfo": "Agregar un mapa de fondo",
            "carouselAddItemInfo": "Agregar un nuevo marcador para el elemento de carrusel seleccionado",
            "carouselPlaceMarkerInfo": "Haga clic en el mapa para agregar un nuevo marcador",
```

2021-07-21 12:02 UTC, allyoucanmap commented on web/client/translations/data.fr-FR.json
> +            "carouselPlaceMarkerInfo": "Cliquez n'importe où sur la carte pour placer ou repositionner le marqueur",
```suggestion
            "carouselAddMapInfo": "Ajouter un fond de carte",
            "carouselAddItemInfo": "Ajouter un nouveau marqueur pour l'élément de carrousel sélectionné",
            "carouselPlaceMarkerInfo": "Cliquez sur la carte pour ajouter un nouveau marqueur",
```

2021-07-21 12:02 UTC, allyoucanmap commented on web/client/translations/data.it-IT.json
> +            "carouselPlaceMarkerInfo": "Fare clic in un punto qualsiasi della mappa per posizionare o riposizionare l'indicatore",
```suggestion
            "carouselAddMapInfo": "Aggiungi una mappa di sfondo",
            "carouselAddItemInfo": "Aggiungi un nuovo marker per l'elemento del carosello selezionato",
            "carouselPlaceMarkerInfo": "Clicca sulla mappa per aggiungere un nuovo marker",
```

2021-07-22 09:42 UTC, dsuren1 requested changes
Hi @allyoucanmap 
Changes with respect to draw support and background works fine. 
However I did see few change in behavior with respect to carousel card component update which needs to looked into and possibly needs a fix

- Clicking on carousel card again with map's zoom and position changed, doesn't reset to it's initial position when marker added (is this behavior replaced with map fit feature now ?) cc @tdipisa @allyoucanmap 
- Adding new item, the carousel widget is not scrolled to the added item
![Scrollcontent](https://user-images.githubusercontent.com/26929983/126613418-832c6861-b82c-4aad-9736-e153cc051bc7.gif)
- Scroll event on carousel card item is propagated to other components
![Mousescroll](https://user-images.githubusercontent.com/26929983/126615408-e842a1bf-1073-43d3-bfac-487f899aa9b2.gif)
- Also carousel item navigation with arrow keys is missing in the new geo carousel widget
- Infocard position is misaligned due to recent change
![2021-07-22 14_43_30-](https://user-images.githubusercontent.com/26929983/126615853-a771eb42-285e-4bb6-b45e-167368e97ff1.jpg)
- After deleting an item in carousel, unable to select other items after the deleted item in list
![deleteItem](https://user-images.githubusercontent.com/26929983/126616871-9d8d0179-554d-4640-82ca-c1b080661c73.gif)
- Selecting the card's footer toolbar icons, triggers card selection too (Is this behavior fine?  cc @tdipisa) 
![autoSelection](https://user-images.githubusercontent.com/26929983/126618091-dcefdcbc-b9e5-47d1-8dd6-6ce1564da2b6.gif)

2021-07-22 13:29 UTC, allyoucanmap commented
Hi @dsuren1,
thanks for the review
done all fixes but these two:

> Clicking on carousel card again with map's zoom and position changed, doesn't reset to it's initial position when marker added (is this behavior replaced with map fit feature now ?) cc @tdipisa @allyoucanmap

yes, the new behaviour follow the fit feature workflow

> Also carousel item navigation with arrow keys is missing in the new geo carousel widget

The issue was referring to the arrows in the UI so for now we don't need an implementation for keyboard

2021-07-23 10:19 UTC, dsuren1 requested changes
> * Selecting the card's footer toolbar icons, triggers card selection too (Is this behavior fine?  cc @tdipisa)
Happens with delete icon (Edit doesn't trigger the selection )
- Popup support needs to be disabled when drawing, as it interferes with the draw displaying popup after placing the marker
- Small cosmetic, just so we know, in mobile view having two geocarousel section one after another, displays the second carousel widget partially in the bottom
![2021-07-23 15_24_03-MapStore HomePage](https://user-images.githubusercontent.com/26929983/126768749-4eb02e13-69e3-409a-9bd7-363bdebab0ad.jpg)

Apart from these, the fixes works fine.

2021-07-23 12:26 UTC, allyoucanmap commented
> Small cosmetic, just so we know, in mobile view having two geocarousel section one after another, displays the second carousel widget partially in the bottom

@dsuren1 done apart of this. Now the implementation uses position sticky so it's the default behaviour I would discuss before with @tdipisa but I don't think is a blocker. We will open a new issue if needed

2021-07-23 12:37 UTC, dsuren1 commented
LGTM :)

2021-07-23 12:38 UTC, dsuren1 approved these changes

2021-07-23 12:45 UTC, merged