#7117: Updated migration guidelines.
geosolutions-it/MapStore2 pull request #7252
Opened 2021-08-30 14:21 UTC by offtherailz

## Description
I updated the migration guidelines for projects. Didn't experienced a migration yet, only reorganized the reported breaking changes accordingly to most recent changes. 

Please let me know from your experience of migrating project if I have to add something.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Documentation

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-08-30 14:26 UTC, MV88 requested changes
geostore version update needs to be added ?

2021-08-30 14:36 UTC, offtherailz commented
mmm... I didn't think about it . 
Maybe "check changes in `pom.xml`" includes it. Did anybody migrated to master yet (e.g. c040 or more)?

2021-08-30 14:59 UTC, MV88 commented
> mmm... I didn't think about it .
> Maybe "check changes in `pom.xml`" includes it. Did anybody migrated to master yet (e.g. c040 or more)?

not yet, yes you are right

2021-09-03 10:37 UTC, offtherailz commented on docs/developer-guide/mapstore-migration-guide.md
> +- `geostore` version used is `1.7.0` on release `2021.02.00` (`1.8-SNAPSHOT` on `master` branch)
```suggestion
- `geostore` version used is `1.7.0` on release `2021.02.00`
```

2021-09-06 09:43 UTC, offtherailz commented
If you approve @MV88 we can merge

2021-09-09 15:48 UTC, MV88 approved these changes

2021-09-09 15:49 UTC, merged

2021-09-09 15:49 UTC, MV88 commented
@offtherailz can you backport  to 2021.02.xx ?