#5905 Prevent crash when configured background has no source/name
geosolutions-it/MapStore2 pull request #7257
Opened 2021-08-31 16:55 UTC by tonym3nsa

## Description
App crashes whenever creating a new map that has a default background without a source and/or a name

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [X] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#5905 

**What is the new behavior?**

The app does not crash when selecting a default background with no source and/or name
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-09-01 15:09 UTC, MV88 requested changes
@tonym3nsa can you revert the formatting made to localConfig.json and new.json?

in general i agree to format them and keep them formatted, 
but this project has no forced rules here and maybe we can create a separate PR for this

let's  discuss this together in the chat, or we can schedule a quick meeting
i would discuss with the

2021-09-01 15:09 UTC, MV88 commented on web/client/configs/localConfig.json
> -    "proxyUrl": {
please avoid to format this file, maybe we can format it in a separate PR

2021-09-01 15:09 UTC, MV88 commented on web/client/configs/new.json
>    "version": 2,
the same applies, here, let's discuss with the team if we need to create a PR that formats the json files
please revert format changes here

2021-09-06 16:29 UTC, MV88 approved these changes

2021-09-06 16:29 UTC, merged

2021-09-06 16:33 UTC, MV88 commented
@tonym3nsa please prepare the backport for 2021.02.xx

@ElenaGallo please test this in DEV

2021-09-14 12:31 UTC, ElenaGallo commented
Test passed, @tonym3nsa please backport this PR to 2021.02.xx. Thank you