#7090 Fix dropdown that displays uuid instead of labels
geosolutions-it/MapStore2 pull request #7269
Opened 2021-09-02 15:38 UTC by tonym3nsa

## Description

The Layer Settings dropdown displays the groups' uuid instead of displaying the label names.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [X] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#7090 

**What is the new behavior?**

Dropdown displays label names instead of uuid

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-09-06 16:56 UTC, MV88 requested changes
@tonym3nsa 
- If you try to open this map http://localhost:8081/?debug=true#/viewer/openlayers/10358
- and you go an open the states layer settings
- you will get this
![image](https://user-images.githubusercontent.com/11991428/132246343-63f34d0b-1a8c-420d-bbd7-bbd68b57aa68.png)

i think you don't need to change flattenGroups method with something different

if you change flattenGroups to this
```
export const flattenGroups = (groups, idx = 0, wholeGroup = false) => {
    return groups.filter((group) => group.nodes).reduce((acc, g) => {
        acc.push(wholeGroup ? g : {label: g.title.replace(/\./g, '/').replace(/\${dot}/g, '.'), value: g.id});
        if (g.nodes.length > 0) {
            return acc.concat(flattenGroups(g.nodes, idx + 1, wholeGroup));
        }
        return acc;
    }, []);
};
```
you will get this
![image](https://user-images.githubusercontent.com/11991428/132246835-7c2a4ca6-2210-4ab9-8ce7-c8874c6edc9d.png)


please check again and modify unit tests and maybe remove the formatGroupList method
also check if flattenGroups is used elsewhere and if this breaks something else

2021-09-15 10:43 UTC, MV88 approved these changes

2021-09-15 10:43 UTC, merged

2021-09-15 10:43 UTC, MV88 commented
@ElenaGallo please test in DEV

@tonym3nsa please backport to 2021.02.xx

2021-09-16 12:36 UTC, ElenaGallo commented
Test passed, @tonym3nsa please backport this to 2021.02.xx