#7037 Fix group title returning as undefined even though it's present
geosolutions-it/MapStore2 pull request #7291
Opened 2021-09-09 17:16 UTC by tonym3nsa

## Description

Fix group titles that wrongly display their respective group names after a context page is refreshed
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
**What is the current behavior?**

#7037 

**What is the new behavior?**

Group titles are displayed instead of the group names after the context page is refreshed
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-09-15 12:28 UTC, MV88 approved these changes

2021-09-15 12:29 UTC, MV88 requested changes

2021-09-15 12:29 UTC, MV88 commented on web/client/utils/LayersUtils.js
> + * @param {array} array of objects
if you have to uses arrays of object as type you have to do like this
```suggestion
 * @param {object[]} array of objects
```

2021-09-15 12:29 UTC, MV88 commented on web/client/utils/LayersUtils.js
> + * @returns {array} flattened array
```suggestion
 * @returns {object[]} flattened array
```

2021-09-15 12:29 UTC, MV88 commented on web/client/utils/LayersUtils.js
> + * @param {array} groups groups of map
```suggestion
 * @param {object[]} groups groups of map
```

2021-09-15 14:25 UTC, MV88 approved these changes

2021-09-15 14:26 UTC, merged

2021-09-16 12:52 UTC, ElenaGallo commented
Test passed, @tonym3nsa please backport this to 2021.02.xx