#7233 Update versions for 2021.02.xx
geosolutions-it/MapStore2 pull request #7312
Opened 2021-09-16 10:10 UTC by offtherailz

## Description
This PR updates the pom.xml files with the stable versions of libs and fixes the versions of `mapstore-services`, `mapstore-war` etc...

2021-09-16 16:54 UTC, offtherailz commented
Maybe we should split this in two:
- Fix versions of dependencies
- Fix versions of modules (and deploy on maven.geo-solutions.it) the versions.
What do you think @mbarto

2021-09-20 08:42 UTC, mbarto requested changes
I found a typo. Except for that, it looks good.

2021-09-20 08:42 UTC, mbarto commented on project/custom/templates/web/pom.xml
> +      <artifactId>mapstore-service</artifactId>
```suggestion
      <artifactId>mapstore-services</artifactId>
```

2021-09-21 08:27 UTC, mbarto approved these changes

2021-09-21 08:33 UTC, offtherailz commented
Thank you. Copying by hand, maybe passed to me.

2021-09-21 09:55 UTC, merged