Making Dockerfile workable standalone
geosolutions-it/MapStore2 pull request #7467
Opened 2021-10-21 13:43 UTC by krishnaglodha

## Description

Docker file at this moment can't be built right away

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - Bugfix

## Issue

**What is the current behavior?**

1.  ERROR [mother 2/4] ADD ./.placeholder /mapstore/
2. cp: -r not specified; omitting directory '/usr/local/tomcat/docker/'

**What is the new behavior?**

1. Now Dockerfile has a  MAPSTORE_WEBAPP_SRC set as https://github.com/geosolutions-it/MapStore2/releases/latest/download/mapstore.war which will download the war and use it 
2. Dockerfile by default will not have GEOSTORE_OVR_OPT="-Dgeostore-ovr=file://${CATALINA_BASE}/conf/${OVR}" since we are not sure if user is using postgres setup

2021-11-08 15:18 UTC, randomorder requested changes

2021-11-08 15:18 UTC, randomorder commented on Dockerfile
> +ARG MAPSTORE_WEBAPP_SRC="https://github.com/geosolutions-it/MapStore2/releases/latest/download/mapstore.war"
please revert this change @krishnaglodha 

users will download / build the mapstore version they need. If they are looking for an "up and running" solution they will pull the image from the docker hub as stated in the [quickstart in the README](https://github.com/geosolutions-it/MapStore2#quick-start)

2021-11-08 15:18 UTC, randomorder commented on Dockerfile
> +COPY newext.json /data/configs/new.json
by default we want to use the default version of the file
```suggestion
# COPY newext.json /data/configs/new.json 
```

2021-11-08 15:18 UTC, randomorder commented on Dockerfile
> +# VOLUME [ "${DATA_DIR}" ]
why is this commented out?

2021-11-08 15:18 UTC, randomorder commented on Dockerfile
> +ENV JAVA_OPTS="${JAVA_OPTS} ${GEOSTORE_OVR_OPT} -Ddatadir.location=${DATA_DIR}"
GEOSTORE_OVR_OPT

Is commented out and then used two lines later

Is there a copy of the "geostore-ovr" file in the datadir?

2021-11-08 15:18 UTC, randomorder commented on Dockerfile
> +# RUN cp ${CATALINA_BASE}/docker/${OVR} ${CATALINA_BASE}/conf
if we are using the datadir for the datadir now, why not copy the file in there?

2021-11-09 08:42 UTC, krishnaglodha commented on Dockerfile
> +ARG MAPSTORE_WEBAPP_SRC="https://github.com/geosolutions-it/MapStore2/releases/latest/download/mapstore.war"
done

2021-11-16 16:26 UTC, randomorder commented on Dockerfile
> +# VOLUME [ "${DATA_DIR}" ]
```suggestion
VOLUME [ "${DATA_DIR}" ]
```

2021-11-16 16:36 UTC, randomorder commented on README.md
> +For using docker, copy the generated <i>mapstore.war</i> to docker folder
```suggestion
```

2021-11-17 13:21 UTC, randomorder approved these changes

2021-11-17 13:29 UTC, merged