#7432 Empty feature grid when switching between layers
geosolutions-it/MapStore2 pull request #7495
Opened 2021-11-03 08:41 UTC by DavidQuartz

## Description

The feature grid queries each new layer selected correctly and displays results.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#7432 

**What is the new behavior?**

The feature grid lists records of the layer selected when querying layer after layer after layer

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
The bug was caused by how optimization was executed when `isDescribeLoaded` returns true in 'createInitialQueryFlow' and  'featureTypeSelectedEpic' epics.

2021-11-03 08:56 UTC, offtherailz requested changes

2021-11-03 08:56 UTC, offtherailz commented on web/client/epics/featuregrid.js
> +    // }
Do not commit commented code, we have GIT to keep memory of changes.
```suggestion
```

2021-11-03 08:56 UTC, offtherailz commented on web/client/epics/wfsquery.js
> +                return Rx.Observable.of(featureTypeLoaded(action.typeName, info), changeSpatialAttribute(geometry), Rx.Scheduler.async);
```suggestion
                return Rx.Observable.of(featureTypeLoaded(action.typeName, info), changeSpatialAttribute(geometry), Rx.Scheduler.async); // async scheduler is needed to allow invokers of `FEATURE_TYPE_SELECTED` to intercept `FEATURE_TYPE_LOADED` action as response.
```

2021-11-03 08:56 UTC, offtherailz commented on web/client/epics/__tests__/wfsquery-test.js
> +        const mockStore = {
```suggestion
        const mockState = {
```

2021-11-03 08:56 UTC, offtherailz commented on web/client/epics/__tests__/wfsquery-test.js
> +            mockStore
```suggestion
            mockState
```

2021-11-03 08:56 UTC, offtherailz commented on web/client/epics/__tests__/wfsquery-test.js
> +            }, mockStore);
```suggestion
            }, mockState);
```

2021-11-03 08:56 UTC, offtherailz commented on web/client/epics/__tests__/wfsquery-test.js
> +            ], async(actions) => {
I think `async` is not necessary

2021-11-03 08:56 UTC, offtherailz commented on web/client/epics/__tests__/wfsquery-test.js
> +            testEpic(featureTypeSelectedEpic, 1, [
```suggestion
            testEpic(featureTypeSelectedEpic, 2, [
```
You espect 2 actions before to run the test callback (4th arg)

2021-11-03 10:00 UTC, offtherailz commented on web/client/epics/__tests__/wfsquery-test.js
> +            mockState
This may fail, because it is a test for the vector use case.

2021-11-03 10:04 UTC, offtherailz requested changes

2021-11-03 10:04 UTC, offtherailz commented on web/client/epics/__tests__/wfsquery-test.js
> +            mockState.layers.flat = wmsLayer;
Changing test data on the fly is dangerous for maintainance. Please do a copy of it.

2021-11-03 10:26 UTC, offtherailz approved these changes

2021-11-03 10:50 UTC, merged

2021-11-04 17:19 UTC, ElenaGallo commented
Test passed, @DavidQuartz please backport to 2021.02.xx. Thanks