Map infobox styling issue fixes. Resolves #7083
geosolutions-it/MapStore2 pull request #7497
Opened 2021-11-04 08:19 UTC by alexander-fedorenko

- Making map information details have same styling when it's opened as sidebar panel and as a modal window.
- Unifying component used to wrap content, using "DockPanel" for map infobox instead of "Dock"

## Description
Improve styling of the map information modal/sidebar panel.
Adds proper margins to the images so that text wont stick to them from the right side.
Changes left/right margins of the elements to use rem units instead of em to make margins equal for headers and regular text.
Replaces map details sidebar dock with the component that is already in use for catalog and few other plugins.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [x] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#7083 

**What is the new behavior?**
Proper margins for text heading, images and other elements in the content.
Shared code-base for the map details information container (DockPanel component)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
-

2021-11-04 12:01 UTC, MV88 requested changes
Seems good overall, please checkout out my comments

Also can you see if you can improve this tiny margin right problem in the preview of the homepage card?
![image](https://user-images.githubusercontent.com/11991428/140309456-375a850a-f242-4911-8479-5322cc2f7da3.png)

2021-11-04 13:24 UTC, alexander-fedorenko commented on web/client/components/details/DetailsPanel.jsx
> +                style={{height: 'calc(100% - 30px)'}}
Got back selector value, it was available via dockStyle property, but I removed it eventually after checking MapCatalog plugin as a reference.
Also resolved margin issue that appears on preview of the details.

2021-11-04 13:55 UTC, MV88 approved these changes
LGTM

2021-11-04 13:57 UTC, merged

2021-11-04 13:57 UTC, MV88 commented
@ElenaGallo please test in DEV

2021-11-05 11:03 UTC, ElenaGallo commented
Test passed, @alexander-fedorenko please backport to 2021.02.xx. Thanks