#7474: The GeoCasousel section and the Paragraph section are not highlighted in the navigation toolbar
geosolutions-it/MapStore2 pull request #7512
Opened 2021-11-08 09:40 UTC by DavidQuartz

## Description

This PR handles the geocarousel section of the issue and does not include a fix for the Paragraph section. The problem with the Paragraph section may require a separate issue to be opened as explained in [this comment](https://github.com/geosolutions-it/MapStore2/issues/7474#issuecomment-962968653).

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#7474 

**What is the new behavior?**

The Geocarousel section is highlighted in the Navigation bar as expected when set as current page

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-12-02 11:11 UTC, allyoucanmap requested changes

2021-12-02 11:11 UTC, allyoucanmap commented on web/client/selectors/geostory.js
> +export const currentPositionSelector = state => {
Please add test for the new selectors

2021-12-03 09:00 UTC, allyoucanmap approved these changes

2021-12-03 09:01 UTC, allyoucanmap commented
@ElenaGallo moving this on test, please let us know when we can backport it

2021-12-03 09:01 UTC, merged

2021-12-03 13:56 UTC, ElenaGallo commented
Test passed, @DavidQuartz please backport to 2021.02.xx. Thanks