#7287: Debounce attribute filter evaluation and validation
geosolutions-it/MapStore2 pull request #7522
Opened 2021-11-09 15:09 UTC by dsuren1

## Description
This PR adds debounce to attribute filter and validation causing inconsistent widget state

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**
#7287 

**What is the new behavior?**
- Entering incorrect expression in Number filter will not cause the widget to go into invalid state
- Incorrect expression will be evaluated and allow filtering only upon correct expression
- Debounce the filter expression input by 1 sec for consistency

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-11-10 09:13 UTC, offtherailz requested changes
Seems to be good. 2 Observations. 

- [x] Applying the debounce to the AttributeFilter make the feature grid of the main map (that uses the same filter) very slow, because it is already debounced on itself. Applying this debounce on an upper level in the dashboard could avoid to influence the main feature grid. I personally think that can be avoided at all. to avoid complicating things. @dsuren1 please check if it is possible to debounce the onChange handler of the widget, instead of the component's one.
- [x] debounce time in any case can be reduced to 500 ms, to speed up a little bit the things. 
- [x] `onChange` handlers have to be tested anyway. They are the main interface provided by the component (see comments)

2021-11-10 09:13 UTC, offtherailz commented on web/client/components/data/featuregrid/filterRenderers/__tests__/NumberFilter-test.jsx
> -    it('Test NumberFilter onChange', () => {
For this and all the tests, onChange handler call have to be tested.

2021-11-10 17:12 UTC, tdipisa commented
@dsuren1 please proceed with this accordingly asap.

2021-11-12 17:13 UTC, offtherailz approved these changes

2021-11-12 17:13 UTC, merged

2021-11-12 17:13 UTC, offtherailz commented
Please @ElenaGallo test on dev instance

2021-11-17 16:22 UTC, ElenaGallo commented
Test passed, @offtherailz please backport to 2021.02.xx