Fix #7504 - applied media query to reduce modal size when screen size < 768px
geosolutions-it/MapStore2 pull request #7530
Opened 2021-11-10 16:21 UTC by ale-cristofori

## Description
This is a less/css change to reduce the fixed size of the modal window displaying the QR code from 500px to 300px when the browser detects a screen size change.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features) N/A
- [ ] Docs have been added / updated (for bug fixes / features)  N/A

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
When users displays the share modal from the home page the modal window shows but not entirely on small screens. This prevents the close button placed on the top right of the modal to display, users won't be able to close the modal on vertical, only if they rotate the screen.

#<issue>
[7504](https://github.com/geosolutions-it/MapStore2/issues/7504). 

**What is the new behavior?**
When users displays the share modal from the home page the modal window shows entirely on small screens in vertical mode. The close button placed on the top right of the modal is displayed correctly, users will be able to close the modal.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-11-16 14:14 UTC, ale-cristofori commented
drafting this PR since I am realising there are a few unit tests failing because of the component change.

2021-11-22 09:53 UTC, offtherailz requested changes
Here some issues:

- [x] Too much white space in desktop version for share
![image](https://user-images.githubusercontent.com/1279510/142838943-7d591012-8d34-478d-ab30-b2588de2e8db.png)
- [ ] horizontal scrollbar appears 
![image](https://user-images.githubusercontent.com/1279510/142839069-c4fad712-a39d-4f48-a8e0-6fe89541727d.png)
- [ ] In content (tested on stories and map, maybe also dashboard) the window snaps to the bottom
![image](https://user-images.githubusercontent.com/1279510/142840144-40e363f7-4442-4875-9ec3-0e17d568c12b.png)

2021-12-06 13:51 UTC, offtherailz requested changes
I don't like it at all. I see that now it has fixed height. 
![image](https://user-images.githubusercontent.com/1279510/144855879-ce6d2cd2-c9a1-4fe7-b1fc-048bba34f7b2.png)

I suggest to proceed this way. 
- **With**: provide max-min with position with media-selector, after a certain size, width is 90% and left: 5%. It seems to be ok, more or less.
- Modal footer not necessary.
- **height**: `max-height: 70%` (100% -15%*2, 15 is the top.) to the `share-win modal-dialog-container` ( I see 60, that is not correct)

This should be more or less the final result.
https://user-images.githubusercontent.com/1279510/144857681-53417605-ed8d-4c1b-8d65-2edc3cb35cbd.mp4

2021-12-06 16:08 UTC, ale-cristofori commented
@offtherailz requested changes have been applied.

2021-12-09 16:59 UTC, tdipisa commented
@offtherailz please review it.

2021-12-13 15:26 UTC, offtherailz approved these changes

2021-12-13 15:26 UTC, merged

2021-12-13 15:27 UTC, offtherailz commented
@
@ElenaGallo, could you please test this on  DEV ? Thank you

2021-12-14 11:23 UTC, ElenaGallo commented
Test passed, @ale-cristofori please backport to 2021.02.xx. Thanks

2021-12-14 11:44 UTC, ale-cristofori commented
> Test passed, @ale-cristofori please backport to 2021.02.xx. Thanks

On it 💨