Issue #7523 -  Geocarousel improve markers viz
geosolutions-it/MapStore2 pull request #7545
Opened 2021-11-15 09:58 UTC by ale-cristofori

## Description
This RP aims at putting into place improvements for the visualisation of marker items for the GeoCarousel layout, within the geostories functionality.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Improvement request from customer

## Issue
**What is the current behavior?**

When items on the map were too close to each other it was rather difficult to distinguish the selected one from those that were not, this was due to two main issues:

1. The colour of the selected marker did not change, the selected one was added a 'chevron' icon above.
2. The selected item z index did not change and it was not drawn on top of the unselected markers, thus it was sometimes hidden by other markers making it difficult to see. 

**What is the new behavior?**
In response to the issues described above fix were applied as follows:

1. The colour of the selected item now is different then the non-selected ones, whenever an item is selected its colour changes to red.
2. The highlighted/selected items layer is now separated from the unselected/non-highlighted one. The highlighted markers layer is added on top the non-highlighted items one and its z index is higher, as a consequence the selected items will always be drawn on top of non-selected ones. See below

![7523_1](https://user-images.githubusercontent.com/14953970/141760989-f91171ed-6bac-4d8d-87da-7c86082d7025.JPG)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-11-18 17:21 UTC, offtherailz requested changes
Looks good, I only changed the style of the highlighted marker from `red` to `green`. I think is more quite color to show the current active. Red has a warning effect. 
I think you can apply my suggestions inline and re-request my review, so we can merge

2021-11-18 17:21 UTC, offtherailz commented on web/client/components/geostory/layouts/sections/GeoCarousel.jsx
> +        iconColor: 'red',
```suggestion
        iconColor: 'green',
```
green is more understandable.
![image](https://user-images.githubusercontent.com/1279510/142463762-e7548051-70e4-4342-83ba-b9a7b143bcb6.png)

2021-11-18 17:21 UTC, offtherailz commented on web/client/plugins/GeoStory.jsx
> + *           // -> 'purple', 'violet', 'pink', 'green-dark', 'green', 'green-light' or 'black'
```suggestion
 *       "iconColor": "green", // 'orange', 'orange-dark', 'orange', 'yellow', 'blue-dark', 'blue', 'cyan', ->
 *           // -> 'purple', 'violet', 'pink', 'green-dark', 'red', 'green-light' or 'black'
```

2021-11-18 17:21 UTC, offtherailz commented on web/client/utils/__tests__/GeoStoryUtils-test.js
> +            iconColor: 'red',
```suggestion
            iconColor: 'green',
            iconShape: 'circle'
        };
        const contents = [
            {id: 'cd29a263-d36a-4459-8821-8dce4c761bcc'},
            {id: 'ef332a5b-3405-4f33-b470-5673cc146fea'}
        ];
        const content = {id: 'cd29a263-d36a-4459-8821-8dce4c761bcc'};
        const contentId = 'cd29a263-d36a-4459-8821-8dce4c761bcc';
        const feature = {
            type: 'Feature',
            geometry: {},
            properties: {}
        };
        const markerStyle = getContentsFeatureStyle(defaultMarkerStyle, contents, content, contentId, feature);
        expect(markerStyle).toEqual({
            iconColor: 'green',
```

2021-11-18 17:21 UTC, offtherailz commented on web/client/utils/GeoStoryUtils.js
> +
```suggestion

/**
 * Applies to the contents style passed the iconText (1, 2, 3), merges the default marker style with the specific feature style and adds the `highlighted` flag.
 */
```

2021-11-18 22:52 UTC, ale-cristofori commented
@offtherailz, thanks for the suggestions, I applied the changes using the inline commits, is now ready to be re-reviewed.

2021-11-19 13:05 UTC, offtherailz approved these changes

2021-11-19 13:05 UTC, merged

2021-11-19 13:06 UTC, offtherailz commented
@ElenaGallo, could you please test this on  DEV  ? Thank you

2021-11-23 09:39 UTC, ElenaGallo commented
Test passed, @ale-cristofori please backport to 2021.02.xx. Thanks