User Guide - Add catalog Catalog tool for Dashboard
geosolutions-it/MapStore2 pull request #7580
Opened 2021-11-18 17:41 UTC by ElenaGallo

## Description

Add Catalog tool on Adding Widgets section

## Other useful information
Related to #7543 
Read the docs [link]()

2021-11-19 14:49 UTC, MV88 requested changes
just a note

2021-11-19 14:49 UTC, MV88 commented on docs/user-guide/adding-widgets.md
> +
```suggestion
* In dashboards as soon as the user selects the widget type, a panel appears to select the layer from which the widget will be created. [MapStore](https://mapstore.geosolutionsgroup.com/mapstore/#/) allows you to choose between CSW, WMS and WMTS GeoSolutions Services, present by default, or by accessing WMS, WFS, CSW, WMTS and TMS Remote Services as explained in the [Managing Remote Services](catalog.md#managing-remote-services) section

```

2021-11-19 14:49 UTC, MV88 approved these changes

2021-12-09 17:03 UTC, tdipisa commented
@ElenaGallo please backport to 2021.02.xx

2021-12-09 17:03 UTC, merged