7594 charts widget color coded classification
geosolutions-it/MapStore2 pull request #7630
Opened 2021-12-06 08:47 UTC by ale-cristofori

## Description
This PR designs a new functionality, allowing users to set their own colour coded attribute classifications and labels for bar and pie chart widgets. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
From the catalog load a layer on the that supports WFS and WPS services.
Open the TOC and select the widget button (bar chart icon on the toolbar).
On the Widget TOC dialog select Chart and subsequently Bar Chart or Pie Chart.

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-12-06 17:29 UTC, offtherailz requested changes
Quite impressive :rocket: 

Only a couple of things: 
- [ ] The legend for pie should be grouped, as well as for bar charts.
![screenshot-localhost_8081-2021 12 06-18_21_32](https://user-images.githubusercontent.com/1279510/144892158-1f3159fb-5a40-44e1-a5e3-339a28a5831c.png)
- [ ] Custom entry, when selected, should show a button on the side to open configuration window (without selecting again "Custom" entry, that is not intuitive). Handle it outside the color ramp selector, if possible. 
- [ ] "Custom" entry should be colored, if possible, with the colors selected.

2021-12-10 08:45 UTC, offtherailz commented
Ok, please investigate a little on that, but if you find is not feasible, you can stop. I'll review this in the meanwhile. Thank you.

2021-12-10 08:46 UTC, offtherailz commented
Ah, please. Fix the unit tests

2021-12-17 14:23 UTC, offtherailz requested changes
Good. I like it a lot. I've only some changes to apply: 


- [x] If I hit `cancel` the customization is partially cleared (default color keept, other colors removed). This is not what I expect from a "cancel" button, but more from a "clear" button. Because I do several customization in that window, I'd prefer to not having the cancel button at all. So please remove it.
- [x] Pie chart
   - [x] Title of the legend should not be shown, as for the original pie chart (we can allow sooner or later to insert it)
   - [x]  Do not write the value in the pie section (You can not control the size of these string, so they can become very big or not readable. We can allow it in the future, as an option, but now please disable).
- [ ] Legends: 
   - [ ] Legend text is a little ugly sometimes.
![image](https://user-images.githubusercontent.com/1279510/146554485-267e7bdc-f5e4-4293-8cd7-3b7f0fb38098.png). The main problem is related to the fixed `<label1> - <label2>` format. When the strings are empty, you may have a `-` appended. 

Moreover you can have charts when the classification attribute is the same of the group-by attribute. 
![image](https://user-images.githubusercontent.com/1279510/146556397-fdbbae03-d43f-4e19-8a0b-f7e7641c2946.png) In this case the first value before the '-' is a repetition, we should allow users to completely override the entire label. A good idea good idea would be using `${}` as replacement. For lines you will have a similar issue with `count(ATTR) - test` where `count(ATTR)` is redundant. I suggest you change this behaviour, setting a custom label a template. `${legendValue}` can be used as a placeholder for the legend value label, that can be the attribute name (pie) or the legend label (chart). In the legend you will simply replace it with string `.replace()` function. 

Examples: 

- Pie: 
   - "`${legendValue}` (Mountain)" --> Arizona (Montain)
   - "Mountain" --> Mountain"
 - Bar: 
    - "`${legendValue}` - Mountain" --> SUM(PERSONS) - Mountain
         - *Setting legend label="persons" --> persons - Mountain
- [ ] Add an hint to suggest these how to use the placeholder in the color customization window

2021-12-17 14:43 UTC, offtherailz commented on web/client/configs/localConfig.json
> +        }],
```suggestion
         },
      {
        "urlPattern": "http(s)?\\:\\/\\/gs-stable\\.geo-solutions\\.it(\\:443|\\:80)?\\/geoserver/.*",
        "authkeyParamName": "authkey",
        "method": "authkey"
    }],
```

2021-12-21 10:11 UTC, offtherailz commented on web/client/configs/localConfig.json
> +    }],
```suggestion
        }],
```

2021-12-21 10:13 UTC, offtherailz commented on web/client/translations/data.en-US.json
> +                        "defaultCustomLabel": "Default Custom Label",
```suggestion
                        "defaultCustomLabel": "Default Label",
```

2021-12-21 10:13 UTC, offtherailz commented on web/client/translations/data.es-ES.json
> +                        "defaultCustomLabel": "Etiqueta predeterminada personalizada",
```suggestion
                        "defaultCustomLabel": "Etiqueta predeterminada",
```

2021-12-21 10:13 UTC, offtherailz commented on web/client/translations/data.fr-FR.json
> +                        "defaultCustomLabel": "Étiquette par défaut personnalisée",
```suggestion
                        "defaultCustomLabel": "Étiquette par défaut",
```

2021-12-21 10:13 UTC, offtherailz commented on web/client/translations/data.it-IT.json
> +                        "defaultCustomLabel": "Etichetta di Default personalizzata",
```suggestion
                        "defaultCustomLabel": "Etichetta di Default",
```

2021-12-21 10:17 UTC, offtherailz commented on web/client/translations/data.de-DE.json
> +                        "defaultCustomLabel": "Benutzerdefiniertes Standardlabel",
```suggestion
                        "defaultCustomLabel": "Standardlabel",
```

2021-12-21 10:18 UTC, offtherailz approved these changes

2021-12-21 10:34 UTC, merged

2022-01-10 16:34 UTC, ElenaGallo commented
@ale-cristofori after my test I only notice a small improvement to make if possible:

there should be the option to delete the first value in the Class Color on the *Custom Colors Settings* panel.

*Current Result*
The Delete option is not present for the first value
![1 1](https://user-images.githubusercontent.com/56537133/148802367-e46eef2a-11bb-4571-87d2-d18a64a349be.png)

*Expected Result*
The Delete option is present for the first value as is the case for subsequent values
![1 2](https://user-images.githubusercontent.com/56537133/148802379-81c15e5b-30e2-411d-a76d-e8edfa7dd09b.png)

2022-01-11 08:43 UTC, tdipisa commented
@ElenaGallo please put this comment in the related issue

2022-01-11 08:45 UTC, ale-cristofori commented
> @ale-cristofori after my test I only notice a small improvement to make if possible:
> 
> there should be the option to delete the first value in the Class Color on the _Custom Colors Settings_ panel.
> 
> _Current Result_ The Delete option is not present for the first value ![1 1](https://user-images.githubusercontent.com/56537133/148802367-e46eef2a-11bb-4571-87d2-d18a64a349be.png)
> 
> _Expected Result_ The Delete option is present for the first value as is the case for subsequent values ![1 2](https://user-images.githubusercontent.com/56537133/148802379-81c15e5b-30e2-411d-a76d-e8edfa7dd09b.png)

Hi @ElenaGallo , that is intentional, to avoid users removing all items from the form, thus removing chart styles. It could be made more 'clever,  so that the the first line cannot be removed if it is the only one ( the remanining one)

2022-01-11 08:47 UTC, tdipisa commented
> Hi @ElenaGallo , that is intentional, to avoid users removing all items from the form, thus removing chart styles. It could be made more 'clever, so that the the first line cannot be removed if it is the only one ( the remanining one)

yes indeed