#5560 Properly check if "navigator.geolocation" is available in browser.
geosolutions-it/MapStore2 pull request #7670
Opened 2021-12-15 22:36 UTC by alexander-fedorenko

## Description
Properly check if "navigator.geolocation" is available in browser.
It will be undefined if geolocation is disabled in browser configuration flags.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#5560

**What is the new behavior?**
No error is thrown to the console log. Geolocation button behaves like if user denied the request to get geolocation.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-12-17 08:59 UTC, MV88 requested changes
hi @alexander-fedorenko please check my comment

2021-12-17 08:59 UTC, MV88 commented on web/client/components/mapcontrols/locate/LocateBtn.jsx
> +            if (typeof navigator.geolocation !== 'undefined') {
what about this?
```suggestion
            if (navigator.geolocation) {
```

or this

```suggestion
            if (navigator?.geolocation?.getCurrentPosition) {
```

2022-01-07 16:06 UTC, MV88 approved these changes
LGTM

2022-01-07 16:07 UTC, merged

2022-01-07 16:07 UTC, MV88 commented
@ElenaGallo Please test in DEV

2022-01-11 09:57 UTC, ElenaGallo commented
Test passed, @alexander-fedorenko please backport to stable branch.