Update release.md
geosolutions-it/MapStore2 pull request #7678
Opened 2021-12-17 11:33 UTC by offtherailz

## Description
Update of release procedure with snapshot

2021-12-20 11:10 UTC, offtherailz commented on docs/developer-guide/release.md
> +- [ ] Update the version of java modules on the release branch to a stable, incremental version. (use mvn version commands)
```suggestion
- [ ] Update the version of java modules on the release branch to a stable, incremental version.
    - [ ] Run `mvn versions:set -DnewVersion=<VERSION> -DprocessAllModules -DgenerateBackupPoms=false` to update package version, where <VERSION> is the version of the java packages (e.g. `1..2.2`).
    - [ ] Manually update project pom templates to use `mapstore-services` of `<VERSION>`
```

2021-12-20 11:31 UTC, offtherailz commented on docs/developer-guide/release.md
> +    - [ ] Run `mvn versions:set -DnewVersion=<VERSION> -DprocessAllModules -DgenerateBackupPoms=false` to update package version, where <VERSION> is the version of the java packages (e.g. `1..2.2`).
```suggestion
    - [ ] Run `mvn versions:set -DnewVersion=<VERSION> -DprocessAllModules -DgenerateBackupPoms=false` to update package version, where <VERSION> is the version of the java packages (e.g. `1.2.2`).
```

2022-01-07 16:50 UTC, MV88 requested changes
just one thing

2022-01-07 16:51 UTC, MV88 approved these changes

2022-01-07 18:03 UTC, merged

2022-01-07 18:03 UTC, MV88 commented
@offtherailz please backport