#7696 WMTS layer feature info bugfix
geosolutions-it/MapStore2 pull request #7699
Opened 2021-12-27 19:06 UTC by alexander-fedorenko

## Description
Right now WMTS layer feature info is failed to show properly when user clicks on the map.
This PR resolves the issue.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#7696 

**What is the new behavior?**
Feature info is properly displayed at the sidebar.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-01-07 15:49 UTC, MV88 requested changes

2022-01-07 15:49 UTC, MV88 commented on web/client/utils/mapinfo/wmts.js
> +                tilematrix: matrixIds[Math.round(props.map.zoom)].identifier,
can you add a unit test for this change?

2022-01-17 09:16 UTC, MV88 approved these changes

2022-01-17 09:16 UTC, merged

2022-01-17 09:21 UTC, MV88 commented
@ElenaGallo please test in DEV

2022-01-17 16:44 UTC, ElenaGallo commented
@alexander-fedorenko When adding a WMTS layer for the first time, the gray error page appears

Error on console: 
> TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Ie (mapstore2.js?e93acc4719e43bc5e1fa:2:2589528)
    at mapstore2.js?e93acc4719e43bc5e1fa:2:2590185
    at Array.filter (<anonymous>)
    at mapstore2.js?e93acc4719e43bc5e1fa:2:2590174
    at mapstore2.js?e93acc4719e43bc5e1fa:2:8934485
    at mapstore2.js?e93acc4719e43bc5e1fa:2:8933908
    at mapstore2.js?e93acc4719e43bc5e1fa:2:8934616
    at Function.mapToProps (mapstore2.js?e93acc4719e43bc5e1fa:2:8933908)
    at r (mapstore2.js?e93acc4719e43bc5e1fa:2:8411934)
    at mapstore2.js?e93acc4719e43bc5e1fa:2:8412747
    at mapstore2.js?e93acc4719e43bc5e1fa:2:8412924
    at n.r.selectDerivedProps (mapstore2.js?e93acc4719e43bc5e1fa:2:8410208)
    at n.i.renderWrappedComponent (mapstore2.js?e93acc4719e43bc5e1fa:2:8410825)
    at Fs (mapstore2.js?e93acc4719e43bc5e1fa:2:7917401)
    at ol (mapstore2.js?e93acc4719e43bc5e1fa:2:7900142)
    at nl (mapstore2.js?e93acc4719e43bc5e1fa:2:7900067)

**How to Reproduce**

- Clean the cache
- Open MapStore
- Login as admin
- Click on New Map
- Click on Options > Catalog
- Select a WMTS service
- Add a layer on TOC

*Current Result*
The gray error page appears

2022-01-18 11:08 UTC, ElenaGallo commented
Hi @alexander-fedorenko ,I can no longer reproduce the issue.

2022-01-20 09:10 UTC, alexander-fedorenko commented
@ElenaGallo I will create backport if problem cannot be reproduced

2022-01-20 09:28 UTC, ElenaGallo commented
@alexander-fedorenko this morning the problem occurred again. Look at the gif below and try to reproduce it with incognito: 
![error_wmts](https://user-images.githubusercontent.com/56537133/150311362-2b4fd634-bc8f-48a4-a0ed-a22fe9a0acb5.gif)

2022-01-20 09:54 UTC, alexander-fedorenko commented
@ElenaGallo This problem is irrelevant to the changes introduced by this PR. I can reproduce this behavior on production with activated throttling in browser tools. The issue is that layers list is not loaded correctly, and here is the workflow to reproduce it:
1. Open any instance of mapstore.
2. Open catalog and switch to the service that has autoload feature active (layers are getting loaded once service is selected).
3. While loading is in progress - quickly switch to any other service that has no autoload feature active.
4. One request is complete - you will get list of empty layer entries, without titles, descriptions etc.
5. Attempt to add any of these layers lead to error.