#6916 - Added tooltips to the numerous elements listed in the issue.
geosolutions-it/MapStore2 pull request #7704
Opened 2021-12-30 01:48 UTC by alexander-fedorenko

## Description
Added tooltips to the numerous elements listed in the issue.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6916

**What is the new behavior?**
Elements will have translatable tooltips.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-01-07 15:38 UTC, MV88 requested changes
hi @alexander-fedorenko 

please have a look at my comments

for Future PRs ignore locales outside than the 5 supported ones and 
focus translations for these ones
- it
- en
- fr
- de
- es

2022-01-10 20:39 UTC, alexander-fedorenko commented on web/client/plugins/manager/ManagerMenu.jsx
> +const DropdownButtonT = tooltip(DropdownButton);
Thanks, renamed it

2022-01-10 20:40 UTC, alexander-fedorenko commented on web/client/test-resources/data.es-ES.json
> +        "backgroundSwitcher":{
Changes are reverted

2022-01-17 09:09 UTC, MV88 approved these changes

2022-01-17 09:09 UTC, merged

2022-01-17 09:10 UTC, MV88 commented
@ElenaGallo please test in DEV