Issue #7712 - Redux devtools chrome extension upgrade to v3.0.0 won't work in MS2
geosolutions-it/MapStore2 pull request #7713
Opened 2022-01-10 14:49 UTC by ale-cristofori

Applies changes to Debug.jsx and StateUtils.js replacing `window.devToolsExtension` (deprecated)
with `window.__REDUX_DEVTOOLS_EXTENSION__`

## Description
This PR solves a bug for a breaking change in the Redux Devtools upgrade to v3.0.0
deprecating the `window.devToolsExtension` variable in the store creation 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
Run MS2 in a local dev server with npm start.
On Chrome Go to http://localhost:8081/?debug=true.
Observe the redux Devtools icon is disabled and an error message will appear in the console.
#7712 

**What is the new behavior?**
Run MS2 in a local dev server with npm start.
On Chrome Go to http://localhost:8081/?debug=true.
Observe the redux Devtools icon is now enabled and it is possible to debug the Redux store/workflow.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-01-10 14:50 UTC, MV88 approved these changes

2022-01-10 16:08 UTC, MV88 requested changes
i was going to approve, but maybe we can add this
to help debug more actions, default is 50

```js
window.__REDUX_DEVTOOLS_EXTENSION__({
            maxAge: 150
        })
```

@offtherailz do you agree?

2022-01-10 17:39 UTC, offtherailz commented
@MV88 I remember it can be configured in the chrome extension UI. It is the same in the most recent one?

2022-01-11 08:59 UTC, MV88 commented
> chrome extension UI

i'll check again, but if you make it configurable is no harm, imho

2022-01-11 09:00 UTC, MV88 commented
> > chrome extension UI
> 
> i'll check again, but if you make it configurable is no harm, imho

2022-01-11 09:35 UTC, MV88 commented
Yes it's possible from the settings UI of the extension

https://user-images.githubusercontent.com/11991428/148917766-44f8d815-cbc5-447c-9386-91c7c0db60d5.mp4

merging this

2022-01-11 09:36 UTC, MV88 approved these changes

2022-01-11 09:36 UTC, merged

2022-01-11 10:36 UTC, MV88 commented
@ElenaGallo this is testable locally

2022-01-12 13:14 UTC, MV88 commented
@ale-cristofori please backport to 2021.02.xx

2022-01-12 13:31 UTC, ElenaGallo commented
Test passed, @ale-cristofori please backport to 2021.02.xx.