Update requirements.md
geosolutions-it/MapStore2 pull request #7725
Opened 2022-01-12 15:13 UTC by offtherailz

## Description
This PR adds to documentation requirements for database and system requirements, beause is not clearly indicated. 

I retrieved the information from here:

http://training.mapstore.geosolutionsgroup.com.s3-website-eu-west-1.amazonaws.com/administration/basics.html#requirements

Anyway I know recent changes to support higer versions of postgres.  @randomorder and @tdipisa can you please check if they are updated. @tdipisa you can also indicate if you want to backport this doc or not.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-01-12 15:17 UTC, randomorder requested changes
bumped the requirements a bit here are the Min reqs from our Docs
https://training.mapstore.geosolutionsgroup.com/administration/basics.html#requirements

2022-01-12 15:17 UTC, randomorder commented on docs/developer-guide/requirements.md
> +| Processor | 1 Core  | 2 Core      |
```suggestion
| Processor | 2 Core  | 2 Core      |
```

2022-01-12 15:17 UTC, randomorder commented on docs/developer-guide/requirements.md
> +| Memory    | 1 GB    | 2 Gb        |
```suggestion
| Memory    | 2 GB    | 4 GB        |
```

2022-01-14 14:39 UTC, tdipisa commented on docs/developer-guide/requirements.md
> +| Postgres | [link](https://www.postgresql.org/)                | 9.6     | 11          | 11         |
The answer is yes, the reference issue is https://github.com/geosolutions-it/MapStore2/issues/7272. @offtherailz no need to backport this.

2022-01-14 14:40 UTC, lpasquali commented on docs/developer-guide/requirements.md
> +| Postgres | [link](https://www.postgresql.org/)                | 9.6     | 11          | 11         |
I agree that also for the auth encryption defaults (more secure than "hackable" md5) we should recommend pg13

2022-01-21 12:00 UTC, tdipisa approved these changes

2022-01-21 12:00 UTC, merged