Issue #7734 improvements to charts widgets
geosolutions-it/MapStore2 pull request #7742
Opened 2022-01-14 09:55 UTC by ale-cristofori

## Description
This PR contains changes that took onboard code review suggestions for #7594 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [x] Feature
 - [x] Code style update (formatting, local variables)
 - [x] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
Within code review of #7594  some issues were raised and enhancements suggested.
1. Replace ColorClassModal classification form input from text box to drop down autocomplete.
2. Bring dropdown menu for classification options in foreground since it was partially hidden by the component on opening.
3. Provide preset (random) colours when users add a new classification rule on ColoClassModal.
4. Include a `cancel` button on the ColoClassModal component asking users for confirmation if some classified values are not completed.
5. Add more margin around the radio button input to chose between `stacked` or `grouped` bar chart type in the Advanced Chart Options section.
6. Solve part of the issue raised with #6217 making more visible the separation lines between slices in pie charts.

**What is the new behavior?**
all changes described above have been applied see [here](https://github.com/geosolutions-it/npa-cgg/issues/214#issuecomment-1010002788) for a complete detailed description of the fixes.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-01-17 17:02 UTC, offtherailz requested changes
- [ ] I can not see any visible difference between grouped and stacked. ![image](https://user-images.githubusercontent.com/1279510/149807689-e0fafccf-a2ed-4ddc-95c0-164cb66bb9cd.png)
- [ ] Close and save do exactly the same operation most of the times (no confirm for exit for changes).

https://user-images.githubusercontent.com/1279510/149810553-63a37827-4f43-4c7b-af14-9df5ac7bbe65.mp4


- [ ] close seems to work only on first edit, but if you close before to change something, the interface becomes inconstistent (no colors, no way to add them). 

https://user-images.githubusercontent.com/1279510/149810336-2af140a1-1066-402f-bf3b-2a20f1988a75.mp4
- [ ] I don't remember if for this we decided it was the correct value for `${legendValue}`: ![image](https://user-images.githubusercontent.com/1279510/149808907-b961623a-1a28-489d-ad2a-bb6107050924.png). Anyway it looks a little hard to understand. `legendValue` evokes the value, more than the default label. Maybe two different placeholders is better.

2022-01-18 13:29 UTC, tdipisa commented
> * Tooltip should contain, if possible, the labels for each color in the tooltip.

2022-01-18 13:47 UTC, ale-cristofori commented
@ale-cristofori @tdipisa @offtherailz, we had an internal meeting where we clarified and discussed the way ahead for the last comments on the ticket.

>  _I can not see any visible difference between grouped and stacked._
This was clarified during the call and is due to how the data is classified in the first place when designing the bar chart parameters. If data cannot be unaggregated any further than the `X Attribute`, which might be the unique identifier for a data set (for states dataset the `STATE_NAME` attribute for example) then there will be no difference between grouped and stacked because data items cannot be grouped or represented as aggregated. That is why in this case we won't be able to see any difference between `stacked` and `grouped`

2022-01-19 09:33 UTC, ale-cristofori commented on web/client/translations/data.en-US.json
> +              "stackedBarChart": "Gestapelt",
fixed in latest commit

2022-01-19 09:33 UTC, ale-cristofori commented on web/client/components/style/ThemaClassesEditor.jsx
> +            /** field classes without preset values - text input  */
fixed in the last commit

2022-01-20 15:04 UTC, offtherailz commented
@ale-cristofori you should fix missing translation for mandatory languages to make the test run and the check pass

2022-01-21 17:32 UTC, offtherailz approved these changes

2022-01-24 08:38 UTC, merged