Streetview panorama options
geosolutions-it/MapStore2 pull request #7783
Opened 2022-01-26 16:58 UTC by offtherailz

## Description
This PR adds the possibility to customize the panorama options. This have to be configured in every plugin's configuration. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-01-26 17:49 UTC, MV88 requested changes
@offtherailz 
maybe you can add a unit test
otherwise feel free to merge

2022-01-26 17:49 UTC, MV88 commented on web/client/plugins/StreetView/selectors/streetView.js
> +export function panoramaOptionsSelector(state) {
you want to add a unit test here?

2022-01-27 10:00 UTC, MV88 approved these changes

2022-01-27 10:17 UTC, merged

2022-01-27 10:17 UTC, MV88 commented
@ElenaGallo please test in DEV

2022-01-27 10:18 UTC, MV88 commented
@offtherailz which is the associated issue?

2022-01-27 10:28 UTC, offtherailz commented
Created and associated. thanks

2022-01-27 14:22 UTC, ElenaGallo commented
Test passed, @offtherailz please backport to 2021.02.xx. Thanks