drop TILED arg from wms printing queries (#7809)
geosolutions-it/MapStore2 pull request #7811
Opened 2022-02-01 10:35 UTC by landryb

TILED is vendor-specific, and triggers exceptions with mapproxy
when requesting HEIGHT & WIDTH that dont match the cache tile size.

## Description
Fix printing WMS layers coming from mapproxy

 this can be tested before/after when adding a WMS layer:

- from https://tiles.craig.fr/ortho/service - warning, single tile option needs to be used in layer properties otherwise layer wont load/display, server returns `Invalid request: invalid tile format, use mixed` because of default `TILED=true` behaviour - if removed as done by this PR, then printing the ortho layer works
- from https://tiles.craig.fr/pci/service - triggers `Invalid request: invalid tile size (use 256x256)` exception serverside.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#7809 - printing WMS layers coming from mapproxy fails because `TILED=true` triggers exceptions, either because the requested `HEIGHT` and `WIDTH` dont match the cache tile size or the requested format doesnt match the cache format.

**What is the new behavior?**
printing WMS layers coming from mapproxy succeeds, tested with both ortho and pci.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] MAYBE
 - [] No

Maybe, because from my understanding `TILED=true` triggers a vendor-specific behaviour in geoserver/geowebcache ?

Ideally, `TILED=true` should only be added if the remote is geoserver/gwc, but at that point i have no idea if that's an information we can get (and trust) from capabilities document.

## Other useful information

Interoperability is hard.

2022-02-02 13:18 UTC, offtherailz approved these changes
Generally speaking, tiled option in GeoServer is used to get WMS requests from tile cache, if they match the gridset. Otherwise the response is provided anyway, with some special headers specifying the esit and reason of cache failure
I understood that MapProxy uses the same parameter name with a different behavior, and rises exception so it can be removed (it is only a cache support optimization). 
Anyway the layers has also a tiled parameter, that is used on map. 
If you had to disable it for the layer, maybe is a good idea to read it from the layer object and use it if present (and / or true).

2022-02-02 13:41 UTC, landryb commented
> Anyway the layers has also a tiled parameter, that is used on map. If you had to disable it for the layer, maybe is a good idea to read it from the layer object and use it if present (and / or true).

Well, the tiled parameter is on by default on all layers (and i havent found a way to disable that per server in the ms2 config), and it works fine when displaying layers that dont have a '*mixed*' cache format (eg the layer from https://tiles.craig.fr/pci/service). `TILED=true` is used along `HEIGHT=256` and `HEIGHT=256` so mapproxy is fine with that, which isnt the case when querying the server for the image to print (which might be 'against' TILED spec, which is a vendor extension anyway..).

For layers that use a `*mixed*` cache format (eg layers from https://tiles.craig.fr/ortho/service), using `TILED=true` (so, the default) breaks layer display (and also printing).

2022-02-22 08:46 UTC, tdipisa requested changes
I don't think we can approve this PR as it is @offtherailz. I completely understand the @landryb point of view and of course we can probably do something to improve the interoperability with MapProxy in this case. 
In order to find an automatic way to set the TILED property to true/false depending on the layer source is something we have to investigate. Therefore a dedicated issue should be opened for this. For the moment, and especially for 2022.01.00, what we can do is just to make it configurable globally (default for MapStore is true). What do you think @offtherailz?

2022-02-22 09:19 UTC, landryb commented
well you already have a way to know if you're talking to geoserver in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/LayersUtils.js#L25 - though i think it'd be much nicer to check for vendor extensions in capabilities. Fwiw my geoserver is on https://ids.craig.fr/wxs/ for various reasons, it's a bit awkward to expect geoserver to be at `/geoserver/`...

As for TILED itself, making it globally configurable would be a valid workaround for now :)

2022-02-22 11:27 UTC, tdipisa commented
> well you already have a way to know if you're talking to geoserver in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/LayersUtils.js#L25 - though i think it'd be much nicer to check for vendor extensions in capabilities. Fwiw my geoserver is on https://ids.craig.fr/wxs/ for various reasons, it's a bit awkward to expect geoserver to be at `/geoserver/`...
> 

I can understand your concern about this but unfortunately, as far as I know, there isn't a clean/stable way implemented so far in GeoServer (eg. a kind of declaration or something similar) to understand that the capabilities are effectively coming from a GeoServer. Therefore some development GeoServer side should be necessary for this (at least for new GeoServer versions). 
One way could be also to delegate the user to declare this through the MS UI (for example when the user define a source in the Catalog tool). Long story short, we haven't made a decision on this yet.
Feel free anyway to contribute to this if you want/can (even if only with your ideas) and thank you so much in any case for your feedback.

> As for TILED itself, making it globally configurable would be a valid workaround for now :)

Do you have in mind or do you have the possibility to contribute for this? Otherwise I'm going to close this PR for now. Thank you again.

2022-02-22 12:59 UTC, landryb commented
> > As for TILED itself, making it globally configurable would be a valid workaround for now :)
> 
> Do you have in mind or do you have the possibility to contribute for this? Otherwise I'm going to close this PR for now. Thank you again.

I dont think i have enough knowledge of the platform right now to implement that in a short timeframe.. but that might be something we can fund.

2022-02-22 13:33 UTC, closed without merging

2022-02-22 16:47 UTC, landryb commented
> there isn't a clean/stable way implemented so far in GeoServer (eg. a kind of declaration or something similar) to understand that the capabilities are effectively coming from a GeoServer.

another possibility would be to look for `GEOSERVER` under `/Service/KeywordList/Keyword` in `GetCapabilities` as it's a default config in geoserver and i doubt many service administrators change that..

2022-02-24 13:46 UTC, landryb commented
> > there isn't a clean/stable way implemented so far in GeoServer (eg. a kind of declaration or something similar) to understand that the capabilities are effectively coming from a GeoServer.
> 
> another possibility would be to look for `GEOSERVER` under `/Service/KeywordList/Keyword` in `GetCapabilities` as it's a default config in geoserver and i doubt many service administrators change that..

replying to myself on a closed issue, also checking for the presence of `updateSequence` attribute to the toplevel `WMS_Capabilities` XML element would be another idea to figure out if the remote is geoserver.