Issue #7907 - Undefined colorCatefories results
geosolutions-it/MapStore2 pull request #7908
Opened 2022-03-04 11:55 UTC by ale-cristofori

This commit contains code that falls back to empty array if
no entry `classification` or `rangeClassification` is found
in the autocolorOptions object, despite the chart being marked
as classified, the inconsistency may be there for charts created
before the dual (strings, numbers) classification was introduced

## Description

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-03-04 15:01 UTC, offtherailz approved these changes

2022-03-04 15:01 UTC, offtherailz requested changes
Need a unit test to prove that it works

2022-03-04 16:01 UTC, ale-cristofori commented
> Need a unit test to prove that it works

Included unit tests

2022-03-07 10:08 UTC, offtherailz approved these changes

2022-03-07 10:08 UTC, merged