Issue #7853 - fix regression that allowed heading, pitch, roll input numbers to exceed given range
geosolutions-it/MapStore2 pull request #7927
Opened 2022-03-08 11:54 UTC by tonym3nsa

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#7853 

**What is the new behavior?**

Heading, pitch and roll input do not allow numbers that exceed their given ranges
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-03-08 14:18 UTC, dsuren1 requested changes
Hi @tonym3nsa 
I noticed the issue mentioned by @tdipisa [here](https://github.com/geosolutions-it/MapStore2/pull/7913#issuecomment-1061702800) is happening again.

When changing the orientation of the map with 3d map tools
- [ ] The orientation value is updated incorrectly Ex: roll exceeding the range
- [ ] The orientation value is not in degrees but in radian

Please check this gif for the steps to reproduce
![share_3d_radian](https://user-images.githubusercontent.com/26929983/157255565-1b1de0e8-62c1-43c9-a8bc-9dcf2ced38f7.gif)

2022-03-08 14:18 UTC, dsuren1 commented on web/client/components/share/SharePanel.jsx
>              !isEqual(this.props?.viewerOptions?.orientation, newProps.viewerOptions?.orientation)) {
I think you need to revisit this condition and below code changes.

Maybe you can remove this condition and skip the state update of orientation fields from [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/share/SharePanel.jsx#L195-L197), as you are doing it explicitly below

2022-03-09 11:54 UTC, tonym3nsa commented
@tdipisa @dsuren1 So, at this point, I'm able to limit heading, pitch, and the roll value using SharePanel and once the map is rotated using Cesium navigation, I return either the minimum value or maximum value depending on which value is exceeded. However, the rotation of the map using the compass doesn't seem that it can be stopped by minimum and maximum - I've checked on Cesium and Cesium navigation's documentation with no success - that may require further investigation.

2022-03-09 12:46 UTC, dsuren1 requested changes
@tonym3nsa 
This is what I observed.
- [x] The value is limited when it exceeds the range, using 3d map compass, and shown in the share panel 
- [ ] The only issue now I see is everytime I use compass, the values are shown in **radian** in the share panel or sometimes **both** ex: _roll in **degress** and heading in **radian**_, which is confusing and it needs to be fixed.
![2022-03-09 18_02_53-MapStore HomePage](https://user-images.githubusercontent.com/26929983/157444262-fac4eb5c-1846-4478-8579-44f1f92e475d.jpg)

@tdipisa 
I don't see any customization support for the **3d map compass tool** to limit it's rotations. So, an issue to investigate applying limits on the compass is not necessary, as we are showing only values within range in share panel. Let me know your thoughts.

2022-03-09 12:51 UTC, dsuren1 commented
@tonym3nsa 
A small advice, please make sure to add new commits to the PR whenever you are making changes and don't force push as it makes difficult to track the modifications done

2022-03-09 13:38 UTC, tonym3nsa commented
> @tonym3nsa This is what I observed.

> * [ ]  The only issue now I see is everytime I use compass, the values are shown in **radian** in the share panel or sometimes **both** ex: _roll in **degress** and heading in **radian**_, which is confusing and it needs to be fixed.

@dsuren1 Thanks. Trying to confirm if those values are radians or degrees. Will revert shorty

2022-03-09 13:38 UTC, tonym3nsa commented
> @tonym3nsa A small advice, please make sure to add new commits to the PR whenever you are making changes and don't force push as it makes difficult to track the modifications done

thanks

2022-03-09 13:39 UTC, tonym3nsa commented
> @tonym3nsa A small advice, please make sure to add new commits to the PR whenever you are making changes and don't force push as it makes difficult to track the modifications done

thanks

2022-03-09 14:34 UTC, dsuren1 commented
> @dsuren1 I have reason to believe those figures are in degrees and not radians. For example, look at the below image. The radian value dispatched by the `CHANGE_MAP_VIEW `action (that gets the radian value from cesium) is similar to the values you mentioned are in radians. Or maybe I may be misunderstanding you - please let me know.
> 
> ![Screenshot 2022-03-09 at 2 11 50 PM png-mh](https://user-images.githubusercontent.com/1873416/157459846-ba8e4243-73e7-4fb3-8f5c-a5f1e5beb3cc.png)

Hi @tonym3nsa, Yes. The values are in degress. The reason for the confusion is the decimal places.

2022-03-09 14:35 UTC, dsuren1 approved these changes

2022-03-09 14:35 UTC, merged

2022-03-09 16:26 UTC, ElenaGallo commented
@tonym3nsa @dsuren1 thank you, tests passed. @tonym3nsa please backport to 2022.01.00.

2022-03-09 16:56 UTC, tdipisa commented
@ElenaGallo the backport is to 2022.01.xx. There are no branches with name 2022.01.00