set params endpoint
geosolutions-it/MapStore2 pull request #8038
Opened 2022-03-29 07:29 UTC by taba90

## Description
Add a setParams endpoint at **mapstore/rest/config/setParams**. The endpoint expect a JSON object like the following:

```
{
"map":{....},
"center":{...},
"bbox":{...},
"featureinfo":{...},
"actions":{...},
"page":"#/viewer/openlayers/config"
}
```
The overall JSON object will be made available in the sessionStorage with name `queryParams`.
The page attribute will be picked up and used for redirect after the JSON has been made available in the sessionStorage.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-03-30 15:47 UTC, offtherailz requested changes
Here some points, let's see also with @tdipisa 

**Must:** 
- [ ] need to escape `'`  to always have valid string (maybe add a test for it)
- [ ] we may need to test if it works with UTF-8 chars
- [ ] Need to document this somewhere in MapStore doc?

**Optional:** 
- [ ] supporting JSON format is ok. Don't know if support other params
- [ ] For `page` parameter,maybe need to have a configurable default. I think `../#viewer/openlayers/config` is ok as default.

2022-03-31 07:38 UTC, taba90 commented
@offtherailz feedback applied

2022-04-01 10:16 UTC, tdipisa commented
@dromagnoli can you please do the second review? @offtherailz is not available and we need to move this forward.

2022-04-01 10:29 UTC, dromagnoli approved these changes
Looks good to me.
I have only suggested a couple of doc fixes for better readability.

2022-04-01 10:29 UTC, dromagnoli commented on docs/developer-guide/map-query-parameters.md
> +Sometimes the request parameters can be too big to be passed in the URL, for instance when dealing with a entire map, or complex data. To overcome this kind of situations an adhoc `POST` service avai
```suggestion
Sometimes the request parameters can be too big to be passed in the URL, for instance when dealing with an entire map, or complex data. To overcome this kind of situations, an adhoc `POST` service available at `mapstore/rest/config/setParams` allows to pass the parameters in the request payload as either `application/json` or `application/x-www-form-urlencoded`. 
```

2022-04-01 10:41 UTC, tdipisa commented
> Looks good to me. I have only suggested a couple of doc fixes for better readability.

Thank you so much @dromagnoli. Also @alexander-fedorenko already tested it locally and it is working fine. @ale-cristofori I'm going to merge this PR so that you can update your local dev branch and do a final test before making #8039 ready to be reviewed.

2022-04-01 11:05 UTC, tdipisa approved these changes

2022-04-01 11:05 UTC, merged

2022-04-05 09:26 UTC, tdipisa commented
@ElenaGallo please ask for the backport of this as soon as also #8006 has been tested in DEV and it is ready to be backported too.

2022-04-06 09:55 UTC, ElenaGallo commented
Test passed, @taba90  please backport this to 2021.01.xx. Thank you

2022-04-13 09:58 UTC, tdipisa commented
@ElenaGallo backported with #8059