8006 Extend queryparams API
geosolutions-it/MapStore2 pull request #8039
Opened 2022-03-29 08:29 UTC by alexander-fedorenko

## Description
Implemented:
- "map" parameter processing both from get and source requests
- "featureinfo" request processing by re-using existing workflow of identify plugin (triggering click on the map with provided latlng).
To be done:
- Applying GET/POST data selection for remaining parameters: featureinfo, bbox, center, actions, marker (?)
- Amending tests
- "featureinfo" request - support list of layers to be passed and used as a filter for data request.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#8006

**What is the new behavior?**
Map configuration can be passed as a separate query parameter. Supporting reading of parameters both from GET request and from sessionStorage (written with POST request and backend)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-04-01 12:09 UTC, alexander-fedorenko commented
There are several ways to test how POST approach works.
1. Use browser built-in support to modify and resend requests.
- Open browser tools, networking tab and then open url /rest/config/setParams
- It will complain on unsupported method. On networking tab modify request to the page, change method to POST, add "Content-type: application/json" to the headers and set body of request with json like
```
{
    "map": {},
    "featureinfo": { lat...},
    "page": "#viewer/openlayers/new"
}
```
- Send request, check that it has status 200 and double click on it to open it in new tab.

2. Use supplementary HTML file to make form post request. I used something like this inside web/client directory:
```html
<html><head><meta charset="UTF-8">
<script>
    // Paste JSON or value between backticks
    window.onload = function(e){
        document.getElementById("page").value = '/#/viewer/openlayers/new';
        document.getElementById("map").value = `

    `;
        document.getElementById("featureinfo").value = `

    `;
        document.getElementById("bbox").value = `

    `;
        document.getElementById("center").value = `
        1,1
    `;
        document.getElementById("zoom").value = `
        4
    `;
        document.getElementById("actions").value = `
        []
    `;
        document.getElementById('submit-form').click();
    }
</script>
</head><body>
<form style="display: none;" id="post-form" action="/rest/config/setParams" method="POST" name="myForm">
    <textarea id="map" name="map"></textarea>
    <textarea id="page" name="page"></textarea>
    <textarea id="featureinfo" name="featureinfo"></textarea>
    <textarea id="bbox" name="bbox"></textarea>
    <textarea id="center" name="center"></textarea>
    <textarea id="zoom" name="zoom"></textarea>
    <textarea id="actions" name="actions"></textarea>
    <input id="submit-form" value="Submit" type="submit">
</form>

</body></html>

```

I'm not quite sure what is the real-world use-case for POST approach though. These two can help test that all works fine.

2022-04-04 08:05 UTC, MV88 commented
> @MV88 Please review when it's convenient. Deploying backend based on this PR will provide POST endpoint too.

@alexander-fedorenko this will be reviewed by @offtherailz

2022-04-04 08:25 UTC, offtherailz requested changes
Hi I'd like to test it too. In order to test it, we need to have some example. Let's take this opportunity to document this functionality. 

- [ ] Document this in https://mapstore.readthedocs.io/en/latest/developer-guide/map-query-parameters/#retro-compatibility refactoring with this structure: 
- Query Parameters
> MapStore allows to manipulate the map calling it with some paramers. This allows external application to open a customized viewer generating these parameters extenally. With this functionality you can modifiy for instance the initial position of the map, modify the entire map and even trigger some actions. 

- Passing Parameters to the map. 
    - Get Request (how to... with example)
    > The parameters can be passed in a query-string-like section, after the `#<path>?` of the request. Example. 
    - Post Request (fix a little the existing section with concrete example). 
- Available Parameters (one concrete example for each section).
    - Feature Info
    - Map
    - Center
    - Zoom
    - bbox 
    - Actions 
        - ...here the actions present in the doc. 
- [ ] See the comments inline for jsdoc

2022-04-04 08:25 UTC, offtherailz commented on web/client/utils/QueryParamsUtils.js
> +export const getRequestLoadValue = (name, state) => {
Document this function (please add parameters and correct if wrong): 
```suggestion
/**
 * Retrieves parameters from hash "query string" of react router
 * Example: `#/viewer/openlayers/0?center=0,0&zoom=5
 */
export const getRequestLoadValue = (name, state) => {
```

2022-04-04 08:25 UTC, offtherailz commented on web/client/utils/QueryParamsUtils.js
> +export const postRequestLoadValue = (name, storage = sessionStorage) => {
Document this function (please add parameters and correct if I'm wrong)
Example: 

```suggestion
/**
 * Retrieves parameters from the `queryParams` entry (JSON) of the passed storage (by default `sessionStorage`). 
 * Example: `#/viewer/openlayers/0?center=0,0&zoom=5
 */
export const postRequestLoadValue = (name, storage = sessionStorage) => {
```

2022-04-04 08:43 UTC, tdipisa commented
@alexander-fedorenko it would be good if you can provide the documentation right now since is seems @offtherailz need it. Please provide is directly where expected at the end, we will review it later after the testing phase only if necessary.

2022-04-04 11:53 UTC, alexander-fedorenko commented
@offtherailz Thank you! I've updated documentation and added examples. Please review when it's convenient.

2022-04-04 16:34 UTC, offtherailz requested changes
I simplified the documentation and discovered some issues. 

Testing I discovered that **is not possible to post** `application/json` opening the page from JavaScript, so I removed the JSON examples from the form. (only via ajax a post like this is allowed). 
So even if the service allows it, it is technically not possible to use the JSON format. You said you found a way to do it.
Anyway this can not be done because it is not supported by the browser. So I removed the doc for it. 

Moreover I improved a little the test page. You can find it in the updated documentation. 

I spend too much time understanding this and trying to test it, so I ask you to test the various use case (using the sample html improved) and check if: 
- [ ] check everything works fine on your side (testing with the back-end active)
- [ ] improve and clean up the html test page if needed
- [ ] I think page needs  to have (`../../`) for POST. Example: `../../#viewer/openlayers/config` . Please test and confirm. In the case please document and fix the test page. 
- [ ] Make more concrete examples: e.g. `#/mapstore/openlayers/config?center=...` that are **tested**.

2022-04-04 23:28 UTC, alexander-fedorenko commented
I've slightly improved example html to simplify the way default data is passed to the form. With this change it makes sense to keep JSON examples for POST request. What do you think?
- New test html works like a charm.
- Did a small cleanup and slight simplification.
- True, to work correctly for for mapstore located at any sub-directory `../../#viewer/openlayers/config` is needed.
- All the examples in doc are those I tried locally, both for GET and POST versions. There are few examples though that are formal ones, like featureinfo, actions to add layers or get feature info, they won't work without real catalogs, or layers on the map. I've updated GET examples to include complete router path, not only query string.

2022-04-05 09:20 UTC, offtherailz reviewed
Excellent, it works very good. I cleaned a little bit more.
Just document filterNameList and it is ok for me.

2022-04-05 10:46 UTC, offtherailz commented on docs/developer-guide/map-query-parameters.md
> +Allows to trigger [identify tool](../../user-guide/side-bar/#identify-tool) for the coordinates passed in "lat"/"lng" parameters. Optional parameter "filterNameList"
```suggestion

Allows to trigger [identify tool](../../user-guide/side-bar/#identify-tool) for the coordinates passed in "lat"/"lng" parameters. Optional parameter "filterNameList"
```

2022-04-05 10:47 UTC, offtherailz approved these changes

2022-04-05 10:47 UTC, offtherailz commented
We can merge when build is ready.

2022-04-05 11:00 UTC, merged

2022-04-05 11:01 UTC, alexander-fedorenko commented
@ElenaGallo please test it dev. Thanks!

2022-04-06 08:06 UTC, offtherailz commented
@ElenaGallo you can find in MapStore documentation here:
https://mapstore.readthedocs.io/en/latest/developer-guide/map-query-parameters/#post-request

some html to copy in a new `html` file (like the embedded) to test the various parameters. 
See the documentation learn how to compile the parameters.

2022-04-06 09:54 UTC, ElenaGallo commented
Test passed, @alexander-fedorenko please backport this to 2021.01.xx. Thanks