#8063 Document strategy of merging the map object with the current map
geosolutions-it/MapStore2 pull request #8068
Opened 2022-04-07 23:42 UTC by alexander-fedorenko

## Description
- Documenting strategy of merging the map object with the current map
- Removing check that was forcing to have valid MapStore map passed in "map" parameter. It was not compliant with the fact that configuration might not have keys required for check and can override only specific properties, which is also valid.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#8063 

**What is the new behavior?**
Documentation is updated;
Removed validation check that was the reason of partial overriding of the map configuration not working when "version" and "map" properties are not passed in the "map" parameter.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-04-08 07:33 UTC, offtherailz commented on docs/developer-guide/map-query-parameters.md
> +```
```suggestion
It also allows partial overriding of existing map configuration by passing only specific properties of the root object and/or the internal "map" object.

Following example will override "catalogServices" and "mapInfoConfiguration":
```text
#/viewer/openlayers/config?map={"mapInfoConfiguration":{"trigger":"click","infoFormat":"text/html"},"catalogServices":{"services": {"wms": {"url": "http://example.com/geoserver/wms","type": "wms","title": "WMS","autoload": true}},"selectedService": "wms"}}
```
Following example will update map "center" and "zoom" level, but will also change trigger event for the display of information sheet to "Hover":
```text
#/viewer/openlayers/config?map={"mapInfoConfiguration":{"trigger":"hover","infoFormat":"text/html"},"map":{"zoom":8,"center":{"x":1250000,"y":5370000,"crs":"EPSG:900913"}}}
```
```

2022-04-08 07:36 UTC, offtherailz commented on web/client/epics/config.js
> +        ...queryParamsMap,
`queryParamsMap` may be null ?

```suggestion
        ...(queryParamsMap ?? {}),
```

2022-04-08 07:37 UTC, offtherailz requested changes
Hi, please only check my comment, if it makes sense and works, that we can merge https://github.com/geosolutions-it/MapStore2/pull/8068/files#r845826929

2022-04-08 07:49 UTC, offtherailz approved these changes

2022-04-08 08:02 UTC, merged

2022-04-08 08:03 UTC, alexander-fedorenko commented
@ElenaGallo please test on dev when it's feasible

2022-04-13 12:50 UTC, ElenaGallo commented
Test passed, @alexander-fedorenko please backport to stable branch.