#8100: Support of vector geometries in Cesium Map
geosolutions-it/MapStore2 pull request #8166
Opened 2022-05-05 12:24 UTC by allyoucanmap

## Description

This PR introduces vector/wfs layers for cesium including a refactor of the current vector style editor to support similar interface we use in the wms style editor.

Changes:

- add WFS/Vector layers in cesium
- included specific parser for cesium, leaflet style to work with the json geostyler spec structure
- refactor of WFS/Vector layers workflow in leaflet and openalyers to support the new and legacy style
- include visual style editor for all type of map libraries for WFS and Vector layers with base symbolizers

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature
 

## Issue

**What is the current behavior?**

#8100
#8103

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

## Other useful information

2022-05-16 16:53 UTC, MV88 requested changes
this PR was complex and hard to review, if you have some maps to use for test would be nice.
especially for the geostyler support

I found severe performance issues while using cesium
[here](http://localhost:8081/?debug=true#/viewer/cesium/39475) is a map called **8100** , not sure it was related to new code or some steps i used
![image](https://user-images.githubusercontent.com/11991428/168642191-73a1ac90-dddb-424e-b6b5-f5e50044ae7b.png)

also why styleJSON is a string ?


is it possible to set geostyler rule using visual style editor using visibility limits?
![image](https://user-images.githubusercontent.com/11991428/168643685-d99f05d2-4f10-4513-b5f2-a37b844f33f3.png)


regarding the import statements can we start forcing to use @mapstore alias since  it would help make this import statement more portable?

2022-05-16 16:53 UTC, MV88 commented on web/client/components/map/leaflet/Feature.jsx
> +            ? <FeatureComponent
i've missed how this are rendered now with new styiling system since you no longer render a component

2022-05-16 16:53 UTC, MV88 commented on docs/developer-guide/maps-configuration.md
> +#### Example (deprecated)
why this is deprecated? we will be able to have features with multiple style definition or not?

2022-05-16 16:53 UTC, MV88 commented on web/client/components/map/leaflet/plugins/VectorLayer.jsx
> +} from '../../../../utils/VectorStyleUtils';
```suggestion
} from '@mapstore/utils/VectorStyleUtils';
```

2022-05-16 16:53 UTC, MV88 commented on web/client/components/map/leaflet/plugins/WFSLayer.jsx
> +} from '../../../../utils/VectorStyleUtils';
```suggestion
} from '@mapstore/utils/VectorStyleUtils';
```

2022-05-16 16:53 UTC, MV88 commented on web/client/components/map/leaflet/plugins/WFSLayer.jsx
> +            layer._msFeatures = {...response.data};
why do you use _ as name of some properties?

see also _msLegacyGeoJSON

2022-05-16 16:53 UTC, MV88 commented on web/client/components/map/openlayers/plugins/VectorLayer.js
> +import { applyDefaultStyleToLayer } from '../../../../utils/VectorStyleUtils';
```suggestion
import { applyDefaultStyleToLayer } from '@mapstore/utils/VectorStyleUtils';
```

2022-05-16 16:53 UTC, MV88 commented on web/client/components/map/openlayers/plugins/WFSLayer.js
> -            layer.geometryType = geometryType;
is this no longer needed right?

2022-05-23 14:09 UTC, allyoucanmap commented
@MV88 I commited your suggestion about the doc, I think the part related to performance could be controlled in another issue.
And we discussed the rest in a call so I think this could be approved

2022-05-24 07:44 UTC, MV88 approved these changes

2022-05-24 07:45 UTC, merged

2022-05-24 07:48 UTC, tdipisa commented
@ElenaGallo please let's prioritize a bit tests of both issues involved for this PR.

2022-05-25 09:37 UTC, ElenaGallo commented
Hi @allyoucanmap here what I found after testing [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/39593) on 3D mode:

1) For Point layer (ex: V_INTERVENTI), when you change the color of the halo, the width of the halo and the rotation, in the Text rule, the changes are not visible on the map
![1](https://user-images.githubusercontent.com/56537133/170230487-46260c77-708c-4a8f-90a0-6d0284991dc4.gif)


2) For polygonal and linear layers (ex: V_PIANO_BACINO, PROT.CIV: RIVI and TORRENTI MINORI), the Mark, Icon, Line and Text rules are not visible on the map

https://user-images.githubusercontent.com/56537133/170230638-8a48850f-c39d-4373-8a2a-0793b03266de.mov


**Possible Component Improvements**

a) In in Cesium, the widget button is available for layers but then the widgets are not visible in the viewer
b) In the attribute table: Zoom to feature does not zoom correctly on the feature and the Filter clicking on the map does not work.
c) The Filter layer with Area of Interest does not work (it is not possible to draw a rectangle, circle, etc. on the map)