Suggestion for a documentation on how resolve drawing conflicts for e…
geosolutions-it/MapStore2 pull request #8197
Opened 2022-05-16 09:09 UTC by alexander-fedorenko

## Description
This PR brings new chapter to the Developer Guide / Extensions with a short explanation on how to deal with drawing conflicts that may occur.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Documentation change

## Issue

**What is the current behavior?**
Missing info on how to resolve drawing conflicts

**What is the new behavior?**
As per description

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-05-19 09:34 UTC, tdipisa requested changes

2022-05-19 09:34 UTC, tdipisa commented on docs/developer-guide/extensions.md
> +Recent MapStore version (2022.01.xx) introduced layout improvements that apart from the other changes brings new sidebar menu
not 2022.01.xx but 2022.02.00 so:

Starting with MapStore v2022.02.00, layout improvements have been introduced which, in addition to other changes, introduce a new sidebar menu

2022-05-19 13:00 UTC, tdipisa requested changes
@alexander-fedorenko we can also consider to put a link in the migration guidelines to reach this section and highlight it to devs

2022-05-20 09:49 UTC, tdipisa commented
> @alexander-fedorenko This part of the doc is fine for me but I don't see the part related to panel registration to make them exclusive. I remember in the PR that you could register a panel to make it close if another one is opening but maybe I'm wrong

Good point. Thank you @allyoucanmap. Let us know for all the above @alexander-fedorenko, please.

2022-05-20 10:24 UTC, alexander-fedorenko commented
@allyoucanmap you're right, chapter about adding dock panels into list is missing. I will add it along with the reference to the updated page in migration guidelines asap.

2022-05-20 13:47 UTC, tdipisa approved these changes

2022-05-20 13:54 UTC, allyoucanmap approved these changes

2022-05-20 14:00 UTC, merged