8171 geostories import export
geosolutions-it/MapStore2 pull request #8233
Opened 2022-05-26 09:49 UTC by weberjavi

## Description
This PR creates a plugin that allows user to import and export geostories from a `.json` file. The imported geostory updates the `state` data for the currently selected dashboard (a similar behaviour is already implemented for the map import functionality). 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue
#8171 

**What is the current behavior?**
Currently there's no way for the user to import or export geostories.
#8171 

**What is the new behavior?**
User can now export and import geostories json files.

https://user-images.githubusercontent.com/6906348/170463139-29564c33-43e2-4cf9-b724-ac2b832435db.mp4

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-05-26 15:21 UTC, allyoucanmap requested changes

2022-05-26 15:21 UTC, allyoucanmap commented on web/client/components/export/ExportPanel.jsx
> +                    {exportPanelTitle}
The implementation is good, but there is code that has been already changed in the dashboard PR see https://github.com/geosolutions-it/MapStore2/commit/ef79f2a534011b621b47fa125f9b3c1f630b381a#diff-99209a97ab18b88c088db5f5d51fb0deeb88efa3a95e813fa286477bab084f06R50

I expected to not see this highlighted.
Did you create the PR from a clean branch aligned with master?
Did you pull the current master on your branch?

2022-05-27 13:26 UTC, allyoucanmap approved these changes

2022-05-27 13:34 UTC, merged

2022-05-27 13:34 UTC, allyoucanmap commented
@ElenaGallo please test this improvement in dev, thanks

2022-05-27 15:46 UTC, ElenaGallo commented
Test passed, @weberjavi please backport to 2022.01.xx. Thanks