#8227 WFS  identify in Cesium and layer settings
geosolutions-it/MapStore2 pull request #8265
Opened 2022-05-31 15:46 UTC by barema4

## Description
* This Pull Request allows one to display feature info of WFS layer in Cesium . It also allows the identity settings to add 
possibility to control the Identify type  for WFS layers in 2D and 3D  from layer settings. Allowing only the 
DISABLE IDENTIFY
PROPERTIES
TEMPLATE 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
* Does not add support for Get feature info requests for wfs layers in cesium
*  Does not make Identify settings available for this type of layer both 2d/3d
#<issue>
* #8227
**What is the new behavior?**
 * Adds support for Get feature info requests for wfs layers in cesium
 * Makes Identify settings available for this type of layer both 2d/3d

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-06-01 08:44 UTC, MV88 requested changes
@barema4 hi
I noticed that feature info does not work nice if you click near the line in 2d mode (openlayers)
![image](https://user-images.githubusercontent.com/11991428/171362568-b5cb5a7c-bf66-48b3-bf84-c162d89fffb0.png)

while if you click outside it works better
![image](https://user-images.githubusercontent.com/11991428/171362488-974993dc-c4af-44f3-a3f6-df61a3955a1b.png)

this can be noticed better in 3d since the circle drawn in the first case is not matching intersecting the line and in the second case is

I think there is something wrong in the way circle is created in 2d mode or on the point used?
try to create a vector GeoJson layer from the geometry created and used in the cql filter intersect, and then import it in the map just after having clicked somewhere.

I can show you what I mean

2022-06-01 08:44 UTC, MV88 commented on web/client/components/TOC/fragments/settings/FeatureInfo.jsx
> +        const formats = this.props.element.type === 'wfs' ? supportedWfsFormats : this.props.defaultInfoFormat;
can you add a unit tests that will cover the list of info formats used by "wfs" and maybe another one like "wms" ?

you can render this comp and check the items rendered in the list

2022-06-01 11:28 UTC, barema4 commented
Done adding unit tests for supported info formats for wfs and wms layers

2022-06-01 12:08 UTC, MV88 requested changes

2022-06-01 12:08 UTC, MV88 commented on web/client/components/TOC/fragments/settings/__tests__/FeatureInfo-test.jsx
> +        expect(testComponent.length).toBe(3);
can you check also the values inside?

2022-06-01 12:08 UTC, MV88 commented on web/client/components/TOC/fragments/settings/__tests__/FeatureInfo-test.jsx
> +        expect(testComponent.length).toBe(4);
can you check also the values inside?

2022-06-01 17:28 UTC, barema4 commented on web/client/components/TOC/fragments/settings/__tests__/FeatureInfo-test.jsx
> +        expect(testComponent.length).toBe(3);
Done checking for values inside

2022-06-06 08:55 UTC, MV88 requested changes
Hi @barema4  I checked your tests  for PR of info format and WFS, but these were not exactly testing what you have added in the codebase

Since the short time we have, I have already fixed them [here ](https://github.com/MV88/MapStore2/commit/2a478c24c6f32bae53416e7036bcdc95a31f7a02) 
can you include them in the PR?

if you like we can discuss about them, but the key concept is to recreate the runtime condition, i.e. passing right props to emulate a behaviour of the application, for example for the test for wfs, you missed to pass the type: "wfs" that was needed to test this component when a layer wfs is in use

please pay more attention to these details

2022-06-06 09:37 UTC, barema4 commented
Hi @MV88 , I have got  it  right. Thanks for calcification.  I have added them.

2022-06-06 10:07 UTC, MV88 approved these changes

2022-06-06 10:08 UTC, merged

2022-06-06 10:10 UTC, MV88 commented
@ElenaGallo please test in DEV

2022-06-06 12:30 UTC, tdipisa commented
@ElenaGallo let us know if we can backport to 2022.01.xx-c040 branch

2022-06-06 13:58 UTC, ElenaGallo commented
Test passed, @MV88 please backport to 2022.01.xx-c040 branch