#8211: Map switcher and legend widgets
geosolutions-it/MapStore2 pull request #8276
Opened 2022-06-01 14:38 UTC by dsuren1

## Description
This PR adds new feature to dashboard map and legend widgets
1. Map widget now lets user to select multiple maps and configure them with the support of Map switcher
2. Legend widget now allows user to change layer settings (visibility, opacity), legend looks similar to layers in TOC

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
#8211 

**What is the new behavior?**
https://docs.google.com/document/d/1cRGdMZGDhFGSBVjxAkSG__Vyty9FAhIA2grVserH9Xc/edit

![legend-ex](https://user-images.githubusercontent.com/26929983/171429889-bee2d58a-e549-42a7-b4c0-fae995d8e633.jpg)

![wid-add-layer](https://user-images.githubusercontent.com/26929983/171429636-161f2fa5-30a0-4854-9242-ca3aa0c117bc.gif)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

Reference: https://github.com/geosolutions-it/MapStore2-C040/issues/575

2022-06-01 16:32 UTC, MV88 requested changes
@dsuren1 on the code point of view I did not spot big things so my focus was more on the functionality point of view

@tdipisa 
here is a list of things I noticed. probably some of them can be excluded or moved to a different issue

-  [ ] you could potentially select  all the maps you have in the list,
can this be a configurable number, or do we not care?

- [x] sometimes an horizontal scrollbar appears
![image](https://user-images.githubusercontent.com/11991428/171438350-6ee6c7a8-68d2-4386-ad84-a47dd63ff5bd.png)

- [x] name of widget is covered if no space is available
![image](https://user-images.githubusercontent.com/11991428/171438621-a7e7b56b-154c-4e2e-92cc-13f7bc1b4ec8.png)

- [ ] it's not clear that you have to press CTRL to select multiple cards/maps
- [x] I have noticed some connection problems in particular when a  table widget is connect to a map and then if you change the map and then select a map that does not have the layer used by the table among layers

https://user-images.githubusercontent.com/11991428/171450373-dfdd1ce4-6f4d-484c-bc40-7193820d955f.mp4

- [x] do we have to show something if legend is not available?
![image](https://user-images.githubusercontent.com/11991428/171450867-3e0f81c3-5f01-41d7-b01e-7aa6de4075fe.png)
in another case we have a message
![image](https://user-images.githubusercontent.com/11991428/171451005-15dbacc8-9186-4b5c-b210-ced6a29aea53.png)

- [x] is it normal to have legends continuously re-rendered?
https://user-images.githubusercontent.com/11991428/171452793-d0876411-d6c0-46a1-a5c2-e98a1d623458.mp4

2022-06-01 16:32 UTC, MV88 commented on web/client/components/widgets/builder/wizard/map/MapCatalog.jsx
> +)(require('../../../../misc/cardgrids/SideGrid').default);
please use import statement here

2022-06-01 16:32 UTC, MV88 commented on web/client/components/widgets/builder/wizard/map/MapCatalog.jsx
> +export default ({
please let's give a name default export as a general rule

2022-06-03 06:39 UTC, dsuren1 commented
@MV88 
Thanks.

> * [ ]  name of widget is covered if no space is available

_I'm thinking of showing an icon when widget width is small. As we expand the widget when the width is enough to fit map switcher we display the same. Your thoughts?_
![image](https://user-images.githubusercontent.com/26929983/171798460-3953064d-e143-4fa5-84ac-09c1ed451cec.png)

> * [ ]  it's not clear that you have to press CTRL to select multiple cards/maps

_I thought since layers in TOC follows the same, it doesn't need any explicit helptext. Shall I add something like this?_
![image](https://user-images.githubusercontent.com/26929983/171799084-e7dff85b-0134-4e1c-9358-305f7d3005cc.png)

> * [ ]  I have noticed some connection problems in particular when a  table widget is connect to a map and then if you change the map and then select a map that does not have the layer used by the table among layers
> 
>  sync.connection.problem.mp4 

_I think this scenario is produced this way_
_1. Create map widget_
_2. Create table widget_
_3. Connect table with map_
_4. Delete map widget_ 
_5. Now add new map widget_
_6. Connection doesn't work. Because old connection is not cleared when dependant widget is deleted. Seems to be an existing issue. I will fix this_

> * [ ]  do we have to show something if legend is not available?

_This is due to the layer being `3dtiles`. I will filter the layers accordingly, such that it doesn't display any `3dtiles` layer in legend widget/wizard_

> * [ ]  is it normal to have legends continuously re-rendered?
>   https://user-images.githubusercontent.com/11991428/171452793-d0876411-d6c0-46a1-a5c2-e98a1d623458.mp4

_Possibly coz of [this]( https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/TOC/fragments/legend/Legend.jsx#L57) when `0` is used as `urlIdx`, and url is array it tends to generate a random number causing it to rerender. I will fix this_

2022-06-06 09:11 UTC, dsuren1 commented
> @dsuren1 thanks for commenting it out
> 
> > > * [ ]    name of widget is covered if no space is available
> > 
> > 
> > _I'm thinking of showing an icon when widget width is small. As we expand the widget when the width is enough to fit map switcher we display the same. Your thoughts?_ ![image](https://user-images.githubusercontent.com/26929983/171798460-3953064d-e143-4fa5-84ac-09c1ed451cec.png)
> 
> it could be a solution, unless you have already implemented we can consider it as a future enhancement

_I have implemented it along other updated in this PR_

> 
> > > * [ ]    it's not clear that you have to press CTRL to select multiple cards/maps
> > 
> > 
> > _I thought since layers in TOC follows the same, it doesn't need any explicit helptext. Shall I add something like this?_ ![image](https://user-images.githubusercontent.com/26929983/171799084-e7dff85b-0134-4e1c-9358-305f7d3005cc.png)
> 
> You are right (I did not knew you could to that also in the TOC). Anyway here it is more obvious that a user can select multiple items in the list, so I would specify it, we should also consider that CTRL is not present in MAC OS, please amend it considering this mac os aspect. maybe it could be similar to the previous proposal to use a icon showing a tooltip to explain selection @allyoucanmap what do you think here?
> 
> @dsuren1 So apart from first consideration, have you covered all the rest, so i can re-check right?

_Sure. I can add a tooltip instead of sub text including mac os's command key (⌘)_

2022-06-06 10:18 UTC, MV88 commented
> Sure. I can add a tooltip instead of sub text including mac os's command key (⌘)

i would change it as the following:

"
for multi-selection 
on windows use CTRL + click
on mac use control key + click
"

2022-06-06 12:43 UTC, MV88 requested changes
- [x] how big should be a map widget to see the map switcher?

![image](https://user-images.githubusercontent.com/11991428/172161344-e02e143f-faad-4db6-9bc7-b33080ec11ae.png)

I think you can revert this change since we have little time

- [ ] there are still some cases where dependencies are not correctly updated
see this

https://user-images.githubusercontent.com/11991428/172162929-aeca3db0-4a04-4b2a-8073-624da008ae2d.mp4

2022-06-06 13:09 UTC, dsuren1 commented
> * [ ]  how big should be a map widget to see the map switcher?
> 
> ![image](https://user-images.githubusercontent.com/11991428/172161344-e02e143f-faad-4db6-9bc7-b33080ec11ae.png)
> 
> I think you can revert this change since we have little time

_The width of the widget should be >800px so it can fit the title and switcher_

> 
> * [ ]  there are still some cases where dependencies are not correctly updated
>   see this
> 
>  sync.problem.mp4

_Let me check_

2022-06-06 13:15 UTC, MV88 commented
> The width of the widget should be >800px so it can fit the title and switcher

then I would make it smaller, like > 400 which includes when widgets is large at least 2 columns, or you revert it to what it was before

2022-06-06 14:32 UTC, MV88 approved these changes
LGTM

2022-06-06 14:32 UTC, merged

2022-08-19 10:02 UTC, DavidQuartz commented
@tdipisa @dsuren1 the multiple map selection feature 'control + click' does not work on Mac. It triggers a 'right click' effect instead.