Fix tileprovider print requests for remote URLs containing a query
geosolutions-it/MapStore2 pull request #8277
Opened 2022-06-02 02:44 UTC by mtnorthcott

## Description

Fix for when a tileprovider URL for a base layer contains a query string and a print request is made. Requests to the print server will be malformed such that the specified `extension` JSON field will contain that query string. Also passes through any query parameters to tile requests via the `customParams` JSON field.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Requests to the print server contain any query string in the `extension` JSON field and do not pass parameters through to individual tile requests.

**What is the new behavior?**

Query strings are trimmed from the `extension` field and instead passed through to individual tile requests via the `customParams` JSON field.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-06-06 22:54 UTC, shermp commented
As the person who opened #7816 thanks for submitting this PR. Looks simpler than what I implemented :smile:

2022-06-07 00:47 UTC, mtnorthcott commented
@shermp I didn't see the existing issue, thanks for the link :) also a coincidence that I encountered the issue using the same LINZ basemap as you've referenced!

2022-06-27 15:04 UTC, tdipisa commented
@mtnorthcott Thank you so much for contributing. I've assigned the review.

2022-06-28 09:14 UTC, MV88 requested changes
@mtnorthcott 

in my case it still produces an empty pdf

![image](https://user-images.githubusercontent.com/11991428/176140521-94ca38c2-fa40-436b-a29c-b9d9f9e6c194.png)

please, can you check again on your side and maybe rebase this branch to see if any recent changes on master are interfering?

this is the request sent 
```
curl 'http://localhost:8081/proxy/?url=https%3A%2F%2Fdev-mapstore.geosolutionsgroup.com%2Fmapstore%2Fpdf%2Fcreate.json' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: hidePopup-5-Welcome=true; hidePopup-9-Welcome=true' \
  -H 'Origin: http://localhost:8081' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:8081/?debug=true' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"units":"m","srs":"EPSG:3857","layout":"A3_no_legend","dpi":96,"outputFilename":"mapstore-print","geodetic":false,"mapTitle":"","comment":"","layers":[{"baseURL":"https://basemaps.linz.govt.nz/v1/tiles/aerial/EPSG:3857/","path_format":"${z}/${x}/${y}.webp","type":"xyz","extension":"webp","opacity":1,"tileSize":[256,256],"maxExtent":[-20037508.3392,-20037508.3392,20037508.3392,20037508.3392],"resolutions":[156543.03390625,78271.516953125,39135.7584765625,19567.87923828125,9783.939619140625,4891.9698095703125,2445.9849047851562,1222.9924523925781,611.4962261962891,305.74811309814453,152.87405654907226,76.43702827453613,38.218514137268066,19.109257068634033,9.554628534317017,4.777314267158508,2.388657133579254,1.194328566789627,0.5971642833948135],"customParams":{"api":"c01g6mqzxb1zvkqtwr16z8em136"}}],"pages":[{"center":[18907463.316621196,-5236853.681873997],"scale":9244667.357955176,"rotation":0}],"legends":[],"outputFormat":"pdf"}' \
  --compressed
```
![image](https://user-images.githubusercontent.com/11991428/176141636-d38a93dc-0e3b-44f5-a2a2-7aeb4f0307c2.png)
as you can see it contains customParams with api key

I am using this api key  c01g6mqzxb1zvkqtwr16z8em136

2022-06-28 09:19 UTC, shermp commented
@MV88 I don't think the version of MapFish print that Mapstore2 uses supports the `webp` image format. Try it with `jpeg`.

2022-06-28 09:59 UTC, MV88 requested changes
@shermp with jpeg works fine

I would approve this PR but we need also a small unit tests for changes like this

@mtnorthcott 
- [ ] may I ask you to create a dedicated a unit test in order to cover also the queryparams case for tile providers?

you may extend this one 

https://github.com/geosolutions-it/MapStore2/blob/b90efe57c87ada0ac2b18561a1fc3d463c45f8e5/web/client/utils/__tests__/PrintUtils-test.js#L638

or duplicate it and add some query params in the url and check they are being parsed correctly

let me know if you need clarification on this side

2022-07-20 01:18 UTC, mtnorthcott commented
@MV88 Thanks for your review. I've added the unit test you've requested and verified this works as expected :)

2022-07-22 09:31 UTC, MV88 approved these changes

2022-07-22 09:58 UTC, merged

2022-07-22 09:59 UTC, tdipisa commented
Thank you so much for contributing @mtnorthcott !

2022-07-22 10:04 UTC, MV88 commented
@ElenaGallo please test it in DEV

2022-08-30 14:59 UTC, tdipisa commented
@ElenaGallo it is also already in QA.