User Guide update - 3D Styling for vector data
geosolutions-it/MapStore2 pull request #8420
Opened 2022-07-19 15:15 UTC by ElenaGallo

## Description

Add 3D Styling for vector data on Layer Settings section

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Read the Docs file [here]()

2022-09-21 14:05 UTC, allyoucanmap requested changes

2022-09-21 14:05 UTC, allyoucanmap commented on docs/user-guide/layer-settings.md
> +* **Polygon type** to choose whether the classification should affect `3D`, `Terrain` or `Both`. (This option is available for File symbolizers)
```suggestion
* **Polygon type** to choose whether the classification, drape effect, should affect `3D`, `Terrain` or `Both`. (This option is available for Fill symbolizers)
```

2022-09-21 14:05 UTC, allyoucanmap commented on docs/user-guide/layer-settings.md
> +* **Clap to ground** to enable/disable the boolean Property specifying whether the polyline should be clamped to the ground (This option is available for Line and File symbolizers).
```suggestion
* **Clap to ground** to enable/disable the boolean Property specifying whether the polyline should be clamped to the ground (This option is available for Line and Fill symbolizers).
```

2022-09-22 08:56 UTC, allyoucanmap approved these changes

2022-09-22 08:57 UTC, merged

2022-09-22 09:01 UTC, allyoucanmap commented
@ElenaGallo please test in dev if everything has been deployed as expected

2022-09-23 11:38 UTC, tdipisa commented
@ElenaGallo please backport to 2022.02.xx. Thank you.