#8371: Documentation export as pdf
geosolutions-it/MapStore2 pull request #8455
Opened 2022-08-01 13:59 UTC by dsuren1

## Description
This PR adds support for documentation export as PDF

**Changes done**
- Modified hyperlinks such that it works in both html and exported PDF file
- Replaced mermaid diagrams with png as mermaid diagrams cannot be exported to PDF (no plugin support)
- Documentation is downloaded with default name `mapstore_documentation.pdf`
- Added new plugin `mkdocs-pdf-export-plugin` (forked with fix for relatives hrefs)
- Dependency libraries added `Markdown` and `WeasyPrint`
- Exported document has combined pages of all md files

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
#8371 

**What is the new behavior?**
Document can be exported as PDF via a small export icon on top of all the pages
![image](https://user-images.githubusercontent.com/26929983/182149524-8b53fb4b-1fc6-4f5f-ba0e-14733d532a02.png)

_Sample can be found here_: https://mapstore2-temp.readthedocs.io/en/latest/

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-08-01 16:24 UTC, MV88 requested changes
- [ ] i don't know why it is building here since locally i have some problems like
![image](https://user-images.githubusercontent.com/11991428/182197090-6ac15b8b-b68e-41a7-831e-a27a9f218638.png)


- [ ] links in docs/index.md fails in exported pdf
- [ ] syntax is wrong see
![image](https://user-images.githubusercontent.com/11991428/182196967-329501f3-82bc-46e4-ae00-b938a3d573e1.png)
- [ ] can you add or improve needed changes in order to build the docs locally, maybe we can improve it [here](https://mapstore.readthedocs.io/en/latest/developer-guide/documentation-guidelines/)?

2022-08-02 07:39 UTC, MV88 commented
@dsuren1 I suggest also to use https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint to check syntax of the markdown

2022-08-03 06:03 UTC, dsuren1 commented
> * [ ]  i don't know why it is building here since locally i have some problems like
> * [ ]  links in docs/index.md fails in exported pdf

I don't see this error and also if you use the built docs from this PR https://mapstore--8455.org.readthedocs.build/en/8455/. Downloading PDF has index.md page, and is exported to PDF and the link in home.md `Managing Users and Groups` section works fine.

This is the pdf downloaded from the doc built in the [PR ](https://mapstore--8455.org.readthedocs.build/en/8455/pdf/mapstore_documentation.pdf)

> * [ ]  syntax is wrong see

I have only modified the href that has reference in another section which doesn't work in the exported pdf. So I haven't touched other areas of md files.

> * [ ]  can you add or improve needed changes in order to build the docs locally, maybe we can improve it [here](https://mapstore.readthedocs.io/en/latest/developer-guide/documentation-guidelines/)?

Sure, I can add some guidelines

2022-08-03 07:30 UTC, MV88 commented
> I will modify this. But in my defense, I have only modified the href that has reference in another section of md file which doesn't work in the exported pdf, so I left the other ones untouched.

we can open a dedicated issue for this, please ignore

2022-08-03 07:38 UTC, dsuren1 commented
> > I will modify this. But in my defense, I have only modified the href that has reference in another section of md file which doesn't work in the exported pdf, so I left the other ones untouched.
> 
> we can open a dedicated issue for this, please ignore

Sure. Thanks. But I have updated this alone for now.

2022-08-03 08:47 UTC, dsuren1 commented
@MV88 
I have fixed all the broken internal links and also update documentation guideline accordingly with a note.

2022-08-08 12:28 UTC, tdipisa commented
@MV88 can you please complete the review?

2022-08-17 15:39 UTC, MV88 commented
@dsuren1 pr is conflicting please resolve it when you can

2022-08-18 13:13 UTC, MV88 requested changes
@dsuren1 
please check some of the comments
there some issues in files you have not touched

- [x] can you check and fix customize-theme.md which has a link to mapstore.geo-solutions.it?
- [x] in layers-settings the link of WMS Catalog Settings is not working
- [x] these two layer settings link points to a different url 
![image](https://user-images.githubusercontent.com/11991428/185380537-45ef4cf7-0601-4908-920a-9179e7614a17.png)
- [x] link of npm and node and python are not working in Requirements.md
- [x] database setup in Quick Build and Deploy is not working
- [x] More information on frontend building tools and configuration is available here link not working
- [x] some links inside Understanding frontend building tools not working, in particular
  - [x] karma.conf.continuous-test.js
  - [x] karma.conf.single-run.js
  - [x] tests.webpack.js
  - [ ] webpack.config.js
  - [ ] prod-webpack.config.js
- [ ] How to use a CDN link not working as it seems not to be a link, note the mouse pointer
![image](https://user-images.githubusercontent.com/11991428/185401529-5d459c9b-11fa-45fb-9c5c-331af59495d0.png)
- [ ] proxy.properties : configuration for the internal proxy (for cross-origin
requests). More information here, link not working

2022-08-19 07:47 UTC, dsuren1 commented on docs/developer-guide/documentation-guidelines.md
> +    For `mkdocs-material==3.2.0`, the installation using pip is as follows `pip install mkdocs-material==3.2.0`
pip installation of specific package version is denoted with `==`

2022-08-19 07:56 UTC, MV88 commented on docs/developer-guide/documentation-guidelines.md
> +    For `mkdocs-material==3.2.0`, the installation using pip is as follows `pip install mkdocs-material==3.2.0`
oh really? I thought it was a typo 😃

2022-08-19 08:15 UTC, MV88 approved these changes
LGTM I think we are good now

2022-08-19 08:15 UTC, merged

2022-08-19 08:23 UTC, MV88 commented
@ElenaGallo testable in DEV

2022-08-19 16:10 UTC, ElenaGallo commented
Test passed @dsuren1 please backport to the stable branch.