User Guide Update - Annotations button
geosolutions-it/MapStore2 pull request #8494
Opened 2022-08-18 13:33 UTC by ElenaGallo

## Description

Add Annotations button on Annotations  section

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Read the Docs file [here](https://elena-mapstore-docs.readthedocs.io/en/8415_userguide/user-guide/menu-bar/#burger-menu)

2022-09-21 13:53 UTC, MV88 requested changes
- [ ] the main menu entry on the left list is still called adding annotations
![image](https://user-images.githubusercontent.com/11991428/191513197-5eb2a8e7-ab57-4736-b5d0-3b745649161b.png), can you change it to Annotations ?

- [x] check lint problems on the .md files you edited, see [here](https://github.com/geosolutions-it/MapStore2/pull/8417#pullrequestreview-1115391391)

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
>  ********************
lint error here, please fix it

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +Starting from a new map or an already existing one, the editor can access the **Annotations** <img src="../img/button/annotations2.jpg" class="ms-docbutton" style="max-height:30px;"/> button from the
please add here an image of the toolbar
like
![image](https://user-images.githubusercontent.com/11991428/191512574-ade22142-df22-4c0e-8736-e92dc3c1d6e6.png)

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +<img src="../img/annotations/annotation_tool.jpg" class="ms-docimage" style="max-width:500px;" />
no need for this to be so long in height
![image](https://user-images.githubusercontent.com/11991428/191512706-b76544b2-070c-4fd3-a320-f396cfde590c.png)

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +Once all the *Geometries* have been created, the user can save the annotation through the **Save** <img src="../img/button/save_button.jpg" class="ms-docbutton" /> button and it will be visible:
```suggestion
Once all the *Geometries* have been created, the user can save the annotation through the **Save** <img src="../img/button/save_button.jpg" class="ms-docbutton" /> button that will be visible in the annotation list:
```

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +* once the annotations panel is closed, trought the <img src="../img/button/x2.jpg" class="ms-docbutton" /> button, in the [TOC](toc.md) as annotations layer
```suggestion
Then, if not present, a new **Annotations**  layer will be created and added to the [TOC](toc.md) <img src="../img/button/x2.jpg" class="ms-docbutton" /> 
```

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +* in the annotation list
```suggestion

```

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +Once annotations are added to the [TOC](toc.md), the user can **Manage** it by clicking to <img src="../img/button/edit_button.jpg" class="ms-docbutton" /> button from the TOC toolbar and the *Main A
```suggestion
Once annotations are added to the [TOC](toc.md), the user can **Manage** them by clicking to <img src="../img/button/edit_button.jpg" class="ms-docbutton" /> button from the TOC toolbar and the *Main Annotations panel* will be open.
```

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +Once annotations are added to the [TOC](toc.md), the user can **Manage** it by clicking to <img src="../img/button/edit_button.jpg" class="ms-docbutton" /> button from the TOC toolbar and the *Main A
maybe we can create a new section "Main Annotations panel" similar to Managing Annotations that can be linked here?

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +From it, the editor is allowed to:
here you use the word editor and in other places the word user, can you align these to editor or user?

2022-09-21 13:53 UTC, MV88 commented on docs/user-guide/annotations.md
> +In particular, the editor can:
isn't this part a bit mixed to Styling annotations, maybe you can move the gif here to that section

2022-09-23 11:47 UTC, tdipisa commented
> * [ ]  the main menu entry on the left list is still called adding annotations

@ElenaGallo I think this still need to be fixed.

2022-09-23 12:43 UTC, tdipisa approved these changes

2022-09-23 12:43 UTC, tdipisa commented
@ElenaGallo please backport to 2022.02.xx. Thank you

2022-09-23 12:44 UTC, merged