#8523 Extended condition of sidebar menu visibility
geosolutions-it/MapStore2 pull request #8530
Opened 2022-08-31 15:00 UTC by alexander-fedorenko

## Description
This PR adds extra check to make sure that sidebar menu is hidden whenever burger menu is rendered on the page, regardless of the length of items to render in sidebar.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#8523 

**What is the new behavior?**
Sidebar menu will be hidden whenever burger menu is rendered on the page.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-09-01 11:20 UTC, allyoucanmap requested changes
This PR adds a selector to the Side menu to ensure to make that not visible but I see another issue if compared with QA.
Why QA has also login/home tools while DEV show them for a brief moment and then it hides them?
QA screenshot
![image](https://user-images.githubusercontent.com/19175505/187900224-41c5f0b3-c9ce-4ba4-bfda-5ad5581c81b5.png)

DEV screenshot

![image](https://user-images.githubusercontent.com/19175505/187900363-a7da47c9-09f4-4234-8003-d5fcf934a5d2.png)

I would like to understand what's the difference between the two implementation QA vs DEV so could you please verify if the behaviour changes if you import BurgerMenu and SidebarMenu as static plugin?
I wouldn't expect to apply an additional selector to SidebarMenu but I would expect a fix on dynamic import.

2022-09-01 13:29 UTC, alexander-fedorenko commented
@allyoucanmap
This behavior indeed can be fixed by converting both BurgerMenu and SidebarMenu to static plugins. But I can't say for sure the exact reason why this change fixes it. QA is also affected by this issue (tested on QA branch locally), but it seems that these steps happens earlier there and they kept out of the user sight.
The reason behind those items appear in sidebar and then getting hidden is the fact that Home, Login plugins have same priority for OmniBar and SidebarMenu, but they should disappear from Omnibar to prevent duplicates once Sidebar is on the page.
The sequence is following: Page Loaded and plugins are getting mounted -> Sidebar is mounted and it is dispatching action to set flag in controls state -> Burger Menu is mounted and it is dispatching action to set flat that it is active -> Sidebar deactivates because BurgerMenu is on the page.
All these cross-dependencies are added to support seamless work of existing/old contexts.

I'm not sure if it's the best approach, but I think it will be cleaner to keep currently used set of plugins somewhere in state and keep it updated whenever new set of plugins is going to be rendered on the page (e.g. when PluginsContainer receives new set of plugins). This way both SidebarMenu and BurgerMenu can rely on information that will be available prior to components being mounted. @allyoucanmap what do you think?

2022-09-01 16:10 UTC, allyoucanmap commented
> This behavior indeed can be fixed by converting both BurgerMenu and SidebarMenu to static plugins. 

If the **main bundle size does not change** and If it could be fixed by having the same behaviour of QA reverting this two plugins to static import I'll go for it for the moment. I don't think this two plugins are importing additional dependencies so it should be safe to add them as static (please double check with a bundle analyzer)

> I'm not sure if it's the best approach, but I think it will be cleaner to keep currently used set of plugins somewhere in state and keep it updated whenever new set of plugins is going to be rendered on the page (e.g. when PluginsContainer receives new set of plugins). This way both SidebarMenu and BurgerMenu can rely on information that will be available prior to components being mounted. @allyoucanmap what do you think?

I'm going to link your comment in a separate issue but probably we will need to review how all the plugins are managed inside the context viewer. I would prefer to not add too much interdependencies between plugins.

2022-09-02 08:10 UTC, alexander-fedorenko commented
@allyoucanmap with the last change sidebar should stop appear for a moment when both sidebar & burger menu are added into the context.

2022-09-02 08:49 UTC, allyoucanmap commented
@tdipisa this issue is related to the new Measure tool configuration (I missed this https://github.com/geosolutions-it/MapStore2/issues/8463#issuecomment-1232954389) so is currently affecting master and we can move this to 2022.02.01.

In the Measure tool I removed priority because I needed to render a component always inside the map and noticed that was working if none of the container has priority defined.
So to fix this we need to restore the priorities and make sure that also component included in the Map container is always rendered.
There was a proposal to add a property called `alwaysRendered` in the container configuration to force the rendering and skip the priority check. Example:

```diff
export default createPlugin('Measure', {
    component: MeasurePlugin,
    containers: {
        BurgerMenu: {
            name: 'measurement',
            position: 9,
            panel: false,
            help: <Message msgId="helptexts.measureComponent"/>,
            tooltip: "measureComponent.tooltip",
            text: <Message msgId="measureComponent.Measure"/>,
            icon: <Glyphicon glyph="1-ruler"/>,
            action: () => setControlProperty("measure", "enabled", true),
            doNotHide: true,
+         priority: 2
        },
        SidebarMenu: {
            name: 'measurement',
            position: 9,
            panel: false,
            help: <Message msgId="helptexts.measureComponent"/>,
            tooltip: "measureComponent.tooltip",
            text: <Message msgId="measureComponent.Measure"/>,
            icon: <Glyphicon glyph="1-ruler"/>,
            action: toggleControl.bind(null, 'measure', null),
            toggle: true,
            toggleControl: 'measure',
            toggleProperty: 'enabled',
            doNotHide: true,
+         priority: 1
        },
        Map: {
            name: 'Measure',
            Tool: MeasureSupport,
            doNotHide: true,
+         alwaysRendered: true
        }
    },
    reducers: {
        measurement
    },
    epics: measurementEpics
});
```
Adding `alwaysRendered` means a change to the plugin architecture api, specifically to the [priority filter](https://github.com/geosolutions-it/MapStore2/blob/8d438d9ea2a0256115c34dfafc2680e6ae107224/web/client/utils/PluginsUtils.js#L332-L333) adding a check for this proposed property

2022-09-02 09:51 UTC, tdipisa commented
This issue is not affecting QA and a new PR will be open for 2022.02.01 to provide a better fix as described above.

2022-09-02 09:51 UTC, closed without merging