#8534 Making MAP_CONFIG_LOADED action dispatched once all plugins are loaded
geosolutions-it/MapStore2 pull request #8538
Opened 2022-09-02 09:36 UTC by alexander-fedorenko

## Description
This PR adds changes into the code that triggers entity (map, context, geostory, dashboard)
 configuration load whenever page is mounted. Instead of doing it right away, app will wait while all plugins are loaded and only then page component will dispatch an action starting workflow of configuration load.
There are several plugins relying on MAP_CONFIG_LOADED action, therefore they should be loaded (reducers and epics should be added) prior to this action dispatched.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#8534 

**What is the new behavior?**
MAP_CONFIG_LOADED action is dispatched after all plugins are loaded, `updateLayerDimensionDataOnMapLoad` epic can properly set default layer for timeline.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-09-02 12:19 UTC, allyoucanmap requested changes
Could you please double check about some differences in the requests from this branch and dev?

- [ ] Map viewer has an additional attributes (#/viewer/openlayers/39079)

this branch

![image](https://user-images.githubusercontent.com/19175505/188140219-789a5934-f43f-4091-9176-d306055d2d10.png)

dev

![image](https://user-images.githubusercontent.com/19175505/188140257-9ca718db-cea9-48dd-b7c3-db4cc04d5819.png)

- [ ] Also dashboards has more wps request if compared with dev (#/dashboard/21694) 

this branch

![image](https://user-images.githubusercontent.com/19175505/188140964-0e00208e-5066-460b-ae74-960639214908.png)

dev

![image](https://user-images.githubusercontent.com/19175505/188141034-c6efa132-f12a-474f-9309-c37de7e8f544.png)

2022-09-02 16:15 UTC, allyoucanmap commented
@tdipisa 
the code looks fine so if @alexander-fedorenko confirms that the requests are the same for him we can proceed with the merge

2022-09-02 16:18 UTC, tdipisa commented
> @tdipisa the code looks fine so if @alexander-fedorenko confirms that the requests are the same for him we can proceed with the merge

Thank you @allyoucanmap. @alexander-fedorenko I'm looking forward to hearing from you about this.

2022-09-04 22:12 UTC, alexander-fedorenko commented
@tdipisa All good, requests count match on the branch, dev and qa for map viewer, dashboard and geostory.

![map-local-dev-qa](https://user-images.githubusercontent.com/4226620/188335253-1dfb1999-5a39-4f64-aa5f-8038828d6d4b.jpg)

![dash-local-dev-qa](https://user-images.githubusercontent.com/4226620/188335256-d4426e1e-a00a-48bd-99ac-752d05212158.jpg)
![geo-local-dev-qa](https://user-images.githubusercontent.com/4226620/188335257-53493ebc-058a-484c-b460-fcd239766922.jpg)

2022-09-05 09:08 UTC, tdipisa approved these changes

2022-09-05 09:12 UTC, merged

2022-09-05 09:12 UTC, tdipisa commented
Thank you @alexander-fedorenko. @ElenaGallo please test this in DEV and let us know for the backport to 2022.02.xx.

2022-09-05 10:28 UTC, ElenaGallo commented
Test passed on DEV, @alexander-fedorenko please backport to 2022.02.xx