#8520: Reduce dashboards clutter and widget update
geosolutions-it/MapStore2 pull request #8555
Opened 2022-09-06 08:50 UTC by dsuren1

## Description
This PR attempts to declutter the widgets in dashboard to allow more widgets to be viewed. Also provides a possibility to configure widgets options (especially `DataGrid` options) through dashboard plugin

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
#8520 

**What is the new behavior?**
New dashboard (100%)
![2022-09-06 13_43_07-MapStore HomePage](https://user-images.githubusercontent.com/26929983/188589395-a84c5864-9049-47de-ba86-bc0f6d06609a.jpg)

Map viewer
![2022-09-06 13_42_05-DevTools - localhost_8081__debug=true](https://user-images.githubusercontent.com/26929983/188589462-e523000c-12dd-4ec7-a15c-1e70c934c4a7.jpg)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-09-06 09:20 UTC, MV88 requested changes
looks nice overall. but I noticed some things that we can discuss together if they have to done or not

- [x] the filter field **width** inside table widget when there is space remains small

DEV
![image](https://user-images.githubusercontent.com/11991428/188596055-6cc2ffd2-6483-4230-8d70-990299297122.png)

PR
![image](https://user-images.githubusercontent.com/11991428/188596127-eb4c564a-a027-49d0-b27e-8bd9f6d72b76.png)

- [ ] second point, the header of map widgets seems to have a different height,
![image](https://user-images.githubusercontent.com/11991428/188596519-2efae0d1-090f-4157-94b7-e2cb0d200305.png)
Probably it is because the map widget filter
![image](https://user-images.githubusercontent.com/11991428/188597319-5396e348-e625-4745-8853-d3ba4ff7feef.png)

- [ ] the title of widgets before it was centered, now it is left aligned
![image](https://user-images.githubusercontent.com/11991428/188598016-1448d1d6-6bfc-47df-b011-fa5127ae5a71.png)

2022-09-06 09:20 UTC, MV88 commented on web/client/plugins/Dashboard.jsx
> + * @prop {object} cfg.widgetOpts widget specific options
which options can contain gridOpts ?
let's put more details here

2022-09-06 09:20 UTC, MV88 commented on web/client/plugins/Dashboard.jsx
> + *          "table": {
can you list somewhere above the list of entries that can be used ? table, counter etc.

2022-09-06 09:20 UTC, MV88 commented on web/client/themes/default/less/widget.less
> +.em (@prop, @val) {
what if we want to use this function somewhere else?
is there a way to include it in the mapstore theme?
like this color-var in css-properties.less?

https://github.com/geosolutions-it/MapStore2/blob/7567d12b49fea8a00ac827b77708856e9927b125/web/client/themes/default/less/mixins/css-properties.less#L15-L21

2022-09-06 10:25 UTC, MV88 commented
@dsuren1 I've spoken with @tdipisa.

let's ignore for now second and third points and the thing related to css-properties.less?
@allyoucanmap please give us some insight when you are back

2022-09-06 10:40 UTC, tdipisa commented
@MV88 a few clarifications below:

 >the filter field width inside table widget when there is space remains small

To be fixed

>second point, the header of map widgets seems to have a different height,

@dsuren1 let me know if we can do something for this relatively quickly otherwise leave it as it is for now

>the title of widgets before it was centered, now it is left aligned

This is coming from the @allyoucanmap proposal therefore leave it as it is for now.

2022-09-06 10:42 UTC, dsuren1 commented
@tdipisa 
> > second point, the header of map widgets seems to have a different height,
> 
> @dsuren1 let me know if we can do something for this relatively quickly otherwise leave it as it is for now

Yes, can be fixed. Working on it.

2022-09-06 11:54 UTC, dsuren1 commented
Fixed
**Map widget (Map switcher)**
![2022-09-06 17_01_28-MapStore HomePage](https://user-images.githubusercontent.com/26929983/188625379-9f8a9e1e-6f50-4672-89c1-b80b99951901.jpg)

**Map widget (one map)**
![2022-09-06 17_02_00-MapStore HomePage](https://user-images.githubusercontent.com/26929983/188625387-a7a1dea6-3c5a-4bfe-8d06-5b6a7fe9780e.jpg)

2022-09-06 12:29 UTC, MV88 approved these changes
A bit better on second point, at leas in case of one map only 
LGTM

2022-09-06 12:31 UTC, MV88 commented
@tdipisa let us know when we can merge this

2022-09-08 09:00 UTC, merged

2022-09-08 09:01 UTC, tdipisa commented
@ElenaGallo please test this in DEV and let us know. For the backport we have to wait after the release of 2022.02.00