#8545 LayerDownload: service selector
geosolutions-it/MapStore2 pull request #8607
Opened 2022-09-23 07:49 UTC by belom88

## Description
New selector to select service.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

#8545

**What is the new behavior?**
New selector for download dialog has been added to select service from list: "WPS", "WFS".
If "WPS" is unavailable, the selector is disabled with selected option "WFS".

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

2022-09-27 08:21 UTC, allyoucanmap requested changes
We should add a cfg option called `defaultSelectedService` that defines the initial selected service in the dropdown when a user opens the download dialog and they have the possibility to select the two options.
We can add a new argument to `checkWPSAvailability(url, selectedService)` action.
The `defaultSelectedService` will be `wps` by default as the current behaviour.
ecample of the expected configuration aviability in mapstore
```js
{
  "name": "LayerDownload",
  "cfg": {
    "defaultSelectedService": "wfs"
  }
}
```

2022-09-27 08:21 UTC, allyoucanmap commented on web/client/components/data/download/DownloadOptions.jsx
> +                options={this.services} />
I suggest to hide the select input when wps is not available Instead of  disabled it

2022-09-27 08:21 UTC, allyoucanmap commented on web/client/translations/data.es-ES.json
> +            "service": "Service",
```suggestion
            "service": "Servicio",
```

2022-09-29 16:10 UTC, allyoucanmap requested changes
- [ ] Please complete the PR with unit tests on actions, reducers, epics and components of the implemented parts, thanks

2022-10-03 10:07 UTC, allyoucanmap approved these changes

2022-10-03 10:08 UTC, allyoucanmap commented
@ElenaGallo please test on dev and let us know when we can backport on the stable branch 2022.02.xx, thanks

2022-10-03 10:08 UTC, merged

2022-10-03 12:46 UTC, ElenaGallo commented
@belom88 the English translation of the option title is incorrect. It should be `Service` instead of `layerdownload.service`.
![service](https://user-images.githubusercontent.com/56537133/193579927-78cba644-e394-4235-b2e5-20418f5e19b5.png)

2022-10-03 13:43 UTC, belom88 commented
@ElenaGallo that should be browser cache issue. Please, clean the cache in you web browser.

2022-10-03 14:45 UTC, ElenaGallo commented
@belom88 now I see the right title.

2022-10-05 09:19 UTC, ElenaGallo commented
@tdipisa @belom88 I also noticed that for raster layers there is the possibility to change from WPS to WFS but then the WFS service is not enabled and the note report '_The server doesn't support WFS or WPS download for this layer!_' (the message is incorrect because WPS is supported). 

**How to reproduce**
For the test used _sfdem_ layer form the [demo map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)
![raster](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif)

2022-10-05 09:37 UTC, tdipisa commented
> @tdipisa @belom88 I also noticed that for raster layers there is the possibility to change from WPS to WFS but then the WFS service is not enabled and the note report '_The server doesn't support WFS or WPS download for this layer!_' (the message is incorrect because WPS is supported).
> 
> **How to reproduce** For the test used _sfdem_ layer form the [demo map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358) ![raster](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif) [ ![raster](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif) ](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif) [ ](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif)

@belom88 (FYI @allyoucanmap) that should not be allowed. A fix is needed.

2022-10-05 09:38 UTC, tdipisa commented
> @tdipisa @belom88 I also noticed that for raster layers there is the possibility to change from WPS to WFS but then the WFS service is not enabled and the note report '_The server doesn't support WFS or WPS download for this layer!_' (the message is incorrect because WPS is supported).
> 
> **How to reproduce** For the test used _sfdem_ layer form the [demo map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358) ![raster](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif) [ ![raster](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif) ](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif) [ ](https://user-images.githubusercontent.com/56537133/194025142-f5d92f24-2b83-4cd8-89e5-7809acdfd33c.gif)

@belom88 (FYI @allyoucanmap) this shluld not be allowed. A fix is needed for this.