#8766: Timeline plugin configuration of snap and mode on startup
geosolutions-it/MapStore2 pull request #8788
Opened 2022-11-09 10:03 UTC by dsuren1

## Description
This PR allow configuration of new options in Timeline plugin
- `initialMode` - `single|range`
- `initialSnap` - `now|fullRange`
- `resetButton` - boolean

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

## Issue

**What is the current behavior?**
- https://github.com/geosolutions-it/MapStore2/issues/8766

**What is the new behavior?**
Based on the configuration the timeline plugin is initialized and time is set on the timeline slider
Kindly refer the issue for scenarios

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-11-09 17:23 UTC, offtherailz requested changes
For the moment follow the suggestions I asked. I wasn't able to test it yet (I need to set-up some sample time data to do that). 
Anyway you can start working on it.

2022-11-09 17:23 UTC, offtherailz commented on web/client/reducers/dimension.js
> +    }
I should keep the epic in the middle if possible, or we can not control or avoid this operation with a flag. 
This is technically an operation that the timeline plugin does to initialize. Not a standard behavior of the dimensions state.

2022-11-10 08:39 UTC, dsuren1 commented on web/client/epics/dimension.js
> -                setCurrentOffset(offsetTime)
Kindly correct me if I'm wrong, instead we should have an epic in timeline to dispatch `initializeSelectedLayer` on `MAP_CONFIG_LOADED` and remove it from here(dimension) while retaining the dispatch action of dimension data and remove the `MAP_CONFIG_LOADED` from the dimension reducer based on this [comment ](https://github.com/geosolutions-it/MapStore2/pull/8788#discussion_r1018197891) ?

2022-11-10 09:08 UTC, offtherailz commented on web/client/epics/dimension.js
> -                setCurrentOffset(offsetTime)
Yes. Also  `autoselect` and `setEndValuesSupport` should be delegated to timeline. 

In general `dimension` should not depend from timeline. 

I see `autoselect` and `setEndValuesSupport` are triggered after `updateLayerDimensionData`. 
So maybe we can delegate all these to the timeline:
- `initializeSelectedLayer` on `MAP_CONFIG_LOADED`
- `autoselect` `setEndValuesSupport` after `UPDATE_LAYER_DIMENSION_DATA`

I think this helps to isolate the purposes of the various parts:
- dimension takes care of keeping updated the dimension data of the layers and the map and time
- timeline /playback update the current time, range, downloads the proper dimension data (invoking dimension) accordingly with the current viewport of the timeline and so on. 



Moreover looking at the code, I see that `setEndValuesSupport` is triggered only after `ADD_LAYER` but not on `MAP_CONFIG_LOADED`, that looks incorrect to me. (I'm afraid that saving a map with layers with start-end values and then reloading may have different results ). Could you please check?

2022-11-10 10:26 UTC, offtherailz commented
Hi @dsuren1
I asked to change the icon to clear up the meanings. In the meanwhile I reviewed this PR: https://github.com/geosolutions-it/MapStore2/pull/8793

This makes me think about a way to clarify and unify similar concepts graphically, so I discussed with @allyoucanmap about it. 

In both the application we have an functionality `filter data by viewport` that should be have the same icon for both the feature grid and the timeline, becuase they have similar meaning (filter the content of the plugin on the current map viewport`.

For this reason, asking to @tdipisa first, we'd like to create a new icon "Filter by viewport" to use for both the PRs.

So I should wait to update the documentation to use the new icon.
The new icon needs to similar to this 
![zoom-to](https://user-images.githubusercontent.com/1279510/201066213-e9a7ffbe-2a98-4ee6-8be3-783528e3d667.svg)
But with the filter on center instead of the magifier
![filter](https://user-images.githubusercontent.com/1279510/201066334-fb596260-4016-4331-8b6d-cbfd291ed942.svg)

2022-11-10 12:02 UTC, dsuren1 commented on web/client/epics/dimension.js
> -                setCurrentOffset(offsetTime)
@offtherailz 
> Moreover looking at the code, I see that setEndValuesSupport is triggered only after ADD_LAYER but not on MAP_CONFIG_LOADED, that looks incorrect to me. (I'm afraid that saving a map with layers with start-end values and then reloading may have different results ). Could you please check?

Looks like `endValuesSupport` & `snapRadioButtonEnabled` are being set directly in the timeline reducer on `MAP_CONFIG_LOADED`

Also I did stumble upon [this](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/reducers/timeline.js#L107) where the snapType is always set to 'start' on `SELECT_LAYER`. Could you please clarify if this is intended?

2022-11-11 06:48 UTC, dsuren1 commented
@offtherailz 
Except for new icon the rest have been updated as per suggestion

2022-11-14 06:35 UTC, dsuren1 commented
@offtherailz 
Kindly clarify the following. Thanks!
> * [ ]  I tried to click reset with `"initialMode": "single", "initialSnap": "now"` but it didn't worked. Please  make sure that it works. A second time I have a strange zoom behavour:

Could you please share me the test data (time layer) used, as I'm unable to reproduce this behavior with the time layers present in _gs-stable_ (`meteroite` and `storm-obs`)

> * [ ] The reset button should show "set range to include all data" with "<->" icon only when range mode is active.

_Should the reset button be enabled only in these two scenarios i.e. `single-now` and `range -fullRange`? What about `range-now`, is this an invalid combo?_

> * [ ]  In single mode, the reset button should show a clock icon and the text "set time to now" if snapping is disabled, "set time to nearest value to now" if snapping is enabled

Since snapping and layer selection is directly related (i.e. with autoselect, enabling one will select the other). With current implementation, hitting reset would select the layer when not selected which in turn trigger epic to `snap to nearest now`. 
With this requirement, in this case(`single-now` - layer unselected/snapping is disabled), should the layer be left _unselected_?

2022-11-14 09:08 UTC, offtherailz commented
> Could you please share me the test data (time layer) used, as I'm unable to reproduce this behavior with the time layers present in _gs-stable_ (`meteroite` and `storm-obs`)

This is my steps sequence:
- Configure timeline as following: 
```json
{
              "name": "Timeline",
              "cfg": {
                "expandLimit": 20,
                "resetButton": true,
                "initialMode": "single",
                "initialSnap": "now"
              }
            },
```
- create a new map
- add storm_obs from catalog
- open the timeline and click on a time different from now
- click on reset button (nothing happens)

https://user-images.githubusercontent.com/1279510/201619768-bfab2b3b-4e66-4ec4-99a9-55c2f7986e68.mp4

Anyway if you are going to change the logic, probably it will not make difference. 

> Should the reset button be enabled only in these two scenarios i.e. single-now and range -fullRange? What about range-now, is this an invalid combo?

The button at this point do not depend from initial state anymore. It depends from the current mode only. Resets to full range if we are in range mode, resets to now if we are in single time mode. I should rely only on this now, in order to make things more simple and independent. 

> Since snapping and layer selection is directly related (i.e. with autoselect, enabling one will select the other). With current implementation, hitting reset would select the layer when not selected which in turn trigger epic to snap to nearest now.
With this requirement, in this case(single-now - layer unselected/snapping is disabled), should the layer be left unselected?

If so, we should correct it. The behavior of reset should be the same of clicking on now on the timeline. The click event cause a sequence that sets time to now if the layer is not selected, or to the nearest value of now if not. Find out where this happens and reuse the same flow, if possible.

2022-11-14 09:22 UTC, offtherailz commented
@dsuren1 https://github.com/geosolutions-it/MapStore2/pull/8807 the icon has been merged. Please align to master to get the right icon

2022-11-15 09:23 UTC, offtherailz commented
@dsuren1 I updated the JSDoc by testing it with `npm start` + `npm run jsdoc:test`.  
Please take a look if it makes sense to you too.

2022-11-15 09:36 UTC, dsuren1 commented
@offtherailz Thanks. It looks fine.

2022-11-15 09:42 UTC, merged

2022-11-15 09:47 UTC, offtherailz commented
Please @ElenaGallo test this on DEV. 
You can do it by creating a context and modifying the properties provided in the doc checking that:
- The reset button does what it need, and it is visible when enabled
- When add (the first) time layer, the timeline sets to range / single mode if configured
- When add (the first) time layer, the timeline sets to include all data, if `initialSnap`= `fullRange` is configured