#8831 Date formats in attributes table
geosolutions-it/MapStore2 pull request #8832
Opened 2022-11-17 01:13 UTC by alex-fko

## Description
This PR provides changes necessary for support of custom formatting for `date`, `date-time` and `time` attribute types inside of the feature editor attributes table and inside of the Table widget.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#8831 

**What is the new behavior?**
`FeatureEditor` and `Widgets` plugins allows to define custom format for attribute types mentioned above.

```json
{
  "name": "FeatureEditor",
  "cfg": {
    "dateFormat": {
      "date": "YY-MM-DD",
      "date-time": "YY-MM-DDTHH:mm[Z]"
    }
  }
}
```

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-11-17 15:22 UTC, allyoucanmap requested changes
Hi @alex-fko the solution is ok but I'm proposing to change the pluginsCfg to dateFormats.
Could you please verify if the suggested changes are correct?

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/plugins/featuregrid/FeatureEditor.jsx
> +                        pluginCfg={props.pluginCfg}
```suggestion
                        dateFormats={props.dateFormats}
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/plugins/featuregrid/FeatureEditor.jsx
> +  *     "dateFormat": {
```suggestion
  *     "dateFormats": {
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/plugins/Widgets.jsx
> + * @prop {object} [dateFormat] object containing custom formats for one of the date/time attribute types. Once specified, custom formats will be applied for specific attribute types in Table widget.
```suggestion
 * @prop {object} [dateFormats] object containing custom formats for one of the date/time attribute types. Once specified, custom formats will be applied for specific attribute types in Table widget. Following keys are supported: "date-time", "date", "time".
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/components/widgets/widget/TableWidget.jsx
> +    pluginCfg
```suggestion
    dateFormats
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/components/widgets/widget/TableWidget.jsx
> +                pluginCfg={pluginCfg}/>
```suggestion
                dateFormats={dateFormats}/>
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/components/data/featuregrid/formatters/index.js
> +export const getFormatter = (desc, pluginCfg) => {
```suggestion
export const getFormatter = (desc, dateFormats) => {
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/components/data/featuregrid/enhancers/editor.js
> +                        getFormatter: (desc) => getFormatter(desc, props.pluginCfg)
```suggestion
                        getFormatter: (desc) => getFormatter(desc, props.dateFormats)
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/components/data/featuregrid/formatters/index.js
> +import {dateFormats} from "../../../../utils/FeatureGridUtils";
```suggestion
import { dateFormats as defaultDateFormats } from "../../../../utils/FeatureGridUtils";
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/components/data/featuregrid/formatters/index.js
> +        const format = get(pluginCfg, ['dateFormat', desc.localType]) ?? dateFormats[desc.localType];
```suggestion
        const format = dateFormats[desc.localType] ?? defaultDateFormats[desc.localType];
```

2022-11-17 15:22 UTC, allyoucanmap commented on web/client/components/data/featuregrid/formatters/index.js
> +            return !isNil(value) ? moment(value, dateFormats[desc.localType]).format(format) : null;
```suggestion
            return !isNil(value) ? moment(value, defaultDateFormats[desc.localType]).format(format) : null;
```

2022-11-22 15:05 UTC, allyoucanmap commented on web/client/plugins/featuregrid/FeatureEditor.jsx
> +  * @prop {object} cfg.dateFormat object containing custom formats for one of the date/time attribute types. Following keys are supported: "date-time", "date", "time"
```suggestion
  * @prop {object} cfg.dateFormats object containing custom formats for one of the date/time attribute types. Following keys are supported: "date-time", "date", "time"
```

2022-11-22 15:05 UTC, allyoucanmap approved these changes

2022-11-22 15:19 UTC, merged

2022-11-22 15:20 UTC, allyoucanmap commented
@ElenaGallo please test on dev and let me know if I can backport to 2022.02.xx-c040, thanks.

2022-11-22 16:14 UTC, ElenaGallo commented
@allyoucanmap test passed on DEV, You can backport. Thanks