#8670 Improve clamp to ground label
geosolutions-it/MapStore2 pull request #8855
Opened 2022-12-02 16:18 UTC by tdipisa

## Description

Improve clamp to ground label in 3D style editor.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [X] Other... Please describe: translations update

## Issue
**What is the current behavior?**

#8670 

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2022-12-02 16:37 UTC, allyoucanmap requested changes
- [x] If we modify this label it will change also the one for the line symbolizer so probably we need to create two different labels:

- Fill -> Clamp outline to ground
- Line -> Clamp to ground

Current Fill and line symbolizer
![image](https://user-images.githubusercontent.com/19175505/205341401-6912568c-93a6-4f25-8a3b-8b5a13f6abef.png)

- [ ] It's also missing the Italian translation

2022-12-02 16:37 UTC, allyoucanmap commented on web/client/translations/data.es-ES.json
> +        "about_a0": "esta",Klemmen Sie den Umriss an den Boden
```suggestion
        "about_a0": "esta",
```

2022-12-05 16:35 UTC, allyoucanmap approved these changes

2022-12-05 16:46 UTC, merged

2022-12-05 16:46 UTC, tdipisa commented
@ElenaGallo please test this in DEV and let us know if we can backport to 2022.02.xx

2022-12-06 16:04 UTC, ElenaGallo commented
Test passed on DEV, @allyoucanmap please backport to 2022.02.xx