Update User Guide - Images and links
geosolutions-it/MapStore2 pull request #8924
Opened 2023-01-23 11:33 UTC by ElenaGallo

## Description

Update images and links on User Guide

2023-01-23 16:02 UTC, MV88 requested changes
- [ ] docs/user-guide/img/managing-users-and-groups/login-win.jpg is not containing home button
- [ ] docs/user-guide/img/managing-users-and-groups/manager.jpg is not containing home button
- [ ] docs/user-guide/img/home-page/new-res.jpg when you use new-res.jpg near "Create new resources" can you specify which element is
- [ ] is this filter icon explained somewhere? 
![image](https://user-images.githubusercontent.com/11991428/214086805-e1f0bf2f-643a-4f55-bca7-23a4b691f40c.png)
- docs/user-guide/img/background/bck-available.jpg has changed a lot, why ?
![image](https://user-images.githubusercontent.com/11991428/214087298-df2f3e79-2b87-422d-9efb-85921b94fbbe.png)

2023-01-23 16:55 UTC, ElenaGallo commented
Hi @MV88, 

> - [ ] docs/user-guide/img/managing-users-and-groups/login-win.jpg is not containing home button
> - [ ] docs/user-guide/img/managing-users-and-groups/manager.jpg is not containing home button
for the speech that is being made in the section where these two images are located, I think it is better that they are screenshots of what can be seen from the Homepage and not from Manage Accounts

> - [ ] is this filter icon explained somewhere? 
![image](https://user-images.githubusercontent.com/11991428/214086805-e1f0bf2f-643a-4f55-bca7-23a4b691f40c.png)

I open a new issue

> that button although is missing in current Side bar list explanation

It is not listed in the sidebar because it is only found in the sidebar of a context and not by default in the map viewer

2023-01-24 08:54 UTC, MV88 commented
>  For the speech that is being made in the section where these two images are located, I think it is better that they are screenshots of what can be seen from the Homepage and not from Manage Accounts

ok

> It is not listed in the sidebar because it is only found in the sidebar of a context and not by default in the map viewer

ok

2023-01-24 08:55 UTC, MV88 approved these changes

2023-01-24 08:56 UTC, merged