Issue 8920
geosolutions-it/MapStore2 pull request #8952
Opened 2023-02-07 09:49 UTC by mulondo

## Description
The PR fixes the issue of a wrong computation of the leader line when relative to the ground.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#8920 

**What is the new behavior?**
The leader line when relative to the ground computation is fixed.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

https://user-images.githubusercontent.com/22595454/217209668-cdd63c28-886f-4d5a-9cba-a0c202e2e71e.mp4

2023-02-07 09:59 UTC, tdipisa commented
@allyoucanmap can you please proceed with the review?

2023-02-07 10:40 UTC, allyoucanmap requested changes
The issue was including also a requirement on the change of Italian translation that is missing in the PR, please add the needed translations

![image](https://user-images.githubusercontent.com/19175505/217222555-831c4718-eddd-4878-b1a3-64261a1d1c3c.png)

2023-02-07 10:40 UTC, allyoucanmap commented on web/client/utils/styleparser/CesiumStyleParser.js
> +export function getLeaderLinePositions({
Please don't export because this should be only an internal function

2023-02-07 10:40 UTC, allyoucanmap commented on web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
> +import CesiumStyleParser, { getLeaderLinePositions } from '../CesiumStyleParser';
see previous comment

2023-02-07 10:40 UTC, allyoucanmap commented on web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
> +        it.only('should add leader line for relative height Reference', (done) => {
please remove the elsint comment and the .only

2023-02-07 10:40 UTC, allyoucanmap commented on web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
> +            }).catch(done());
The test needs to be done with the CesiumStyleParser class see this [other test as an example](https://github.com/geosolutions-it/MapStore2/blob/7d87fd5a77e19a0a8125bc7380b1d6b445ad6e08/web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js#L382-L539)

2023-02-07 11:53 UTC, mulondo commented
> The issue was including also a requirement on the change of Italian translation that is missing in the PR, please add the needed translations
> 
> ![image](https://user-images.githubusercontent.com/19175505/217222555-831c4718-eddd-4878-b1a3-64261a1d1c3c.png)

ok let me look into that as well

2023-02-13 13:30 UTC, allyoucanmap approved these changes

2023-02-13 13:31 UTC, merged

2023-02-13 13:31 UTC, allyoucanmap commented
@ElenaGallo please test this fix on dev, thanks

2023-02-14 10:32 UTC, tdipisa commented
@mulondo @allyoucanmap the test is passed in DEV. This update should be backported to branch c040-2022.02.xx and the [downstream project](https://github.com/geosolutions-it/MapStore2-C040) updated accordingly.

2023-02-14 13:17 UTC, mulondo commented
> @mulondo @allyoucanmap the test is passed in DEV. This update should be backported to branch c040-2022.02.xx and the [downstream project](https://github.com/geosolutions-it/MapStore2-C040) updated accordingly.

Noted