#9001 Made project branch parametric
geosolutions-it/MapStore2 pull request #9002
Opened 2023-03-07 14:50 UTC by offtherailz

## Description

In order to automate the release process, this hard-coded string that need to be updated on every commit must be removed.
For this reason, I propose to make this script parametric. The project creation will rely on master branch.

If a user wants to build the project from a release branch, he have to specify the branch/commit as parameter. 

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9001

**What is the new behavior?**
Removing this hardcoded version, we can move on with automation

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-04-03 09:23 UTC, MV88 requested changes
sounds ok, but this requires 
- [ ] an update to internal create project doc
- [ ] an update on the training doc


@tdipisa @offtherailz I would do at least first point as part of this PR and open an issue to keep track of the update of the training too

2023-04-03 09:32 UTC, tdipisa commented
@MV88 ok

2023-06-21 10:19 UTC, offtherailz commented
I updated  the doc. For the training, it is related to the future release

2023-07-26 09:23 UTC, MV88 approved these changes

2023-07-26 09:24 UTC, merged