#9248 - Import/export an application context
geosolutions-it/MapStore2 pull request #9270
Opened 2023-07-04 10:28 UTC by dsuren1

## Description
This PR adds feature in context creator wizard to import/export the selected context.

The plugins are enabled by default under `context-creator`.
- ContextImport
- ContextExport

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
- #9248 

**What is the new behavior?**
User can export and import the context into context creator. Existing context will be replaced if any during import.
The name of the context is view is upon context import to avoid duplication

![context_import_export](https://github.com/geosolutions-it/MapStore2/assets/26929983/a22dc266-395f-48c4-b65c-f8ae93e19976)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-07-05 14:15 UTC, offtherailz requested changes
- [ ] I tried to export a new context and it has a strange format. is there a reason for this?
   - It inclues a `resource` --> `data` tree containing the effective data to export
      - `allTemplates` should not be exported
      - `pluginsConfig` should not be exported too
   Please save only the content of resource --> data content in the root, consistent with the data saved on the server.
Trying to import the context doesn't replace:
- [ ] the context name (this is opinable anyway)
- [ ] When importing a context on an existing one (navigating to the map and back before to import) the map is not updated 
[screencast-drive.google.com-2023.07.05-16_09_44.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/86deee78-0063-4a20-a845-4ace245121e7)
- [x] The import export buttons are available only on the first screen. I suggest to show them in all the windows (export is correct to be always available, import should be disabled on steps > 1. I suggest to disable it and show a tooltip saying "to import a context, go to step 1).

2023-07-06 04:53 UTC, dsuren1 commented
@offtherailz 
I have updated the PR with the rest of the comment

> * [ ]  the context name (this is opinable anyway)

The reason for not replacing name is because, the name is unique, replacing it with imported value will cause a duplication which will force the user to modify it anyway. Importing on an existing context (saved context), the name is retained from the exisiting context so it works just like updating the context which will replace everything else except the name and id

2023-07-06 08:09 UTC, offtherailz commented
> @offtherailz I have updated the PR with the rest of the comment
> 
> > * [ ]   the context name (this is opinable anyway)
> 
> The reason for not replacing name is because, the name is unique, replacing it with imported value will cause a duplication which will force the user to modify it anyway. Importing on an existing context (saved context), the name is retained from the exisiting context so it works just like updating the context which will replace everything else except the name and id

After discussion I updated the point you mention with the result of our discussion, avoiding to replace the name at all

2023-07-07 15:55 UTC, offtherailz requested changes
- [ ] JSON still contains a "data" root. it have to be identical to the context JSON coming from the server. so  something like `{ "windowTitle": "Save test", "mapConfig": {...} `
- [ ] As wel as I export and import map and windowTitle seems not to be imported correctly

[screencast-github.com-2023.07.07-17_52_43.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/41b17f28-6bc1-424e-aea8-a839330c56c9)

Stopping here with the review. Please make sure that everything works fine before re-requesting the review.

2023-07-07 16:10 UTC, offtherailz commented on web/client/translations/data.de-DE.json
> +                "windowTitlePlaceholder": "Fenstertitel eingeben..."
```suggestion
                "windowTitlePlaceholder": "Fenstertitel eingeben..."
```

2023-07-07 16:10 UTC, offtherailz commented on web/client/translations/data.it-IT.json
> +                "windowTitlePlaceholder": "Inserisci il titolo della finestra..."
```suggestion
                "windowTitlePlaceholder": "Inserisci il titolo della finestra..."
```

2023-07-07 16:11 UTC, offtherailz commented on web/client/translations/data.es-ES.json
> +                "windowTitlePlaceholder": "Ingrese el título de la ventana..."
```suggestion
                "windowTitlePlaceholder": "Ingrese el título de la ventana..."
```

2023-07-07 16:12 UTC, offtherailz commented on web/client/translations/data.en-US.json
> +                }
Are these changes significant (E.g. align with the other json translation). Otherwise please remove.

2023-07-07 16:13 UTC, offtherailz commented on web/client/translations/data.en-US.json
> +                "saveCfgErrorNotification": {
Is this change significant? otherwise remove

2023-07-10 06:37 UTC, dsuren1 commented
@offtherailz Ignore the request for review. I accidentally hit it. Let me check the issues again

2023-07-10 08:21 UTC, offtherailz commented on web/client/translations/data.en-US.json
> +                "heading": "Export context as a .json file"
```suggestion
                "heading": "Export context as a file"
```

2023-07-10 08:24 UTC, offtherailz approved these changes

2023-07-10 08:36 UTC, merged

2023-07-17 05:03 UTC, dsuren1 commented
@ElenaGallo 
Kindly test this change in DEV. Thanks

2023-07-17 10:03 UTC, ElenaGallo commented
Hi @dsuren1,
shouldn't the context export be available only after entering both the name and the window title?
Now, starting from a new context, after entering the name it is possible to export it but when it is imported into a new context it is not recognized

https://github.com/geosolutions-it/MapStore2/assets/56537133/a686e965-c927-4da8-9a96-2625a06372f2

2023-07-17 16:25 UTC, tdipisa commented
@ElenaGallo @dsuren1 

>shouldn't the context export be available only after entering both the name and the window title?

Yes, as per my discussion with @dsuren1 today.

>Now, starting from a new context, after entering the name it is possible to export it but when it is imported into a new context it is not recognized

we ca ignore this for the moment. The current behavior is in line with export of other resources. The export is taking the current state of a context and special cases, like the resource name check, seems already properly considered.