feat: can import geojson files as layer with query params
geosolutions-it/MapStore2 pull request #9276
Opened 2023-07-11 12:36 UTC by f-necas

## Description
PR used to import GeoJSON files from query parameters.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

https://github.com/geosolutions-it/MapStore2/issues/8927

**What is the new behavior?**
GeoJSON can be imported with an action query parameter.
```
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/config?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":["LayerTitle"],"sources":[{"type":"GEOJSON","url":"https://pkgstore.datahub.io/examples/geojson-tutorial/example/data/db696b3bf628d9a273ca9907adcea5c9/example.geojson"}]}]
```

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-07-24 14:08 UTC, allyoucanmap requested changes
The implementation looks good, thanks @f-necas for the contribution!
Just some general changes below in particular a fix for the missing notification error when the url of a GeoJSON is not valid

2023-07-24 14:08 UTC, allyoucanmap commented on docs/developer-guide/map-query-parameters.md
>  Example:
We could add a section at the bottom to explain how to add a GeoJSON via catalog query param, eg:

---

It is possible to add GeoJSON layer using the following configuration:

```json
{
    "type": "CATALOG:ADD_LAYERS_FROM_CATALOGS",
    "layers": ["My GeoJSON Layer"],
    "sources": [{ "type":"GEOJSON", "url":"https://example.com/example.geojson" }]
}
```

`#/viewer/config?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":["My GeoJSON Layer"],"sources":[{"type":"GEOJSON","url":"https://example.com/example.geojson"}]}]`

This GeoJSON catalog will return a single record similar to the 3D Tiles catalog and for this reason the name used in the layers array will be used to apply the title to the added vector layer.

2023-07-24 15:38 UTC, allyoucanmap approved these changes

2023-07-24 15:39 UTC, f-necas commented
Thanks @allyoucanmap for the review. I've made the changes.

2023-07-25 09:55 UTC, allyoucanmap commented
@f-necas there was a temporary problem with the readthedocs so I'll need to close and reopen the PR again to trigger the workflow

2023-07-25 12:39 UTC, merged

2023-08-10 11:46 UTC, landryb commented
fwiw, went to try this with the link in the PR description, and here it fails:
```
Error
Some records have not been found: LayerTitle Please check the query URL and its parameters.
```
is the syntax in the sample url valid ? is the geosolutions dev instance deployed with this PR ?

2023-08-10 13:31 UTC, landryb commented
right. ***blunders*** damn CORS...