Issue #9311 - populate search bar on select
geosolutions-it/MapStore2 pull request #9321
Opened 2023-08-02 14:39 UTC by ale-cristofori

## Description
When performing a search from the map page search bar, results appear and when selecting the desired one the selected text should populate the search bar.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#9311 

**What is the current behavior?**
The search text box is not populated with the selected item text but with the text typed by the user.
#9311 

**What is the new behavior?**
The search text box should be populated with the selected item text.
https://github.com/geosolutions-it/MapStore2/assets/14953970/9e082e0c-ab2e-421e-8d5b-e4dd6ddc4f94

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-08-02 15:47 UTC, MV88 requested changes
LGTM just one little thing

2023-08-02 15:47 UTC, MV88 commented on web/client/actions/search.js
> +export function selectSearchItem(item, mapConfig, service, resultsStyle) {
missing js doc

2023-08-03 08:26 UTC, ale-cristofori commented on web/client/actions/search.js
> +export function selectSearchItem(item, mapConfig, service, resultsStyle) {
included JSDOC for new parameter

2023-08-03 08:27 UTC, ale-cristofori reviewed
re-reviewed and modified as requested

2023-08-03 09:01 UTC, MV88 approved these changes

2023-08-10 09:48 UTC, tdipisa commented
@ElenaGallo please test this in DEV.

2023-08-10 09:48 UTC, merged