#9369 Setting up readthedocs build.os
geosolutions-it/MapStore2 pull request #9373
Opened 2023-08-30 15:59 UTC by offtherailz

Draft PR to fix #9369

2023-09-01 15:21 UTC, tdipisa requested changes
- The pagination bar should be green 
- The GeoSolutions logo is broken for some pages

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/ef873ea0-3f3e-48be-ace6-c00de5ce7b37)

- The home page should be like the old one without the Quickstart in the toolbar possibly
![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/18659f60-ae08-42ab-b0c0-59b6ea7f52e3)

2023-09-04 16:06 UTC, tdipisa approved these changes

2023-09-04 16:07 UTC, merged

2023-09-04 16:19 UTC, tdipisa commented
@ElenaGallo this is a relevant update of the documentation, therefore pay attention during tests and let us know if you fine any discrepancy with the old version. If all good let us know when we can backport

2023-09-06 12:29 UTC, ElenaGallo commented
Test passed, @offtherailz please backport this to the stable branch. Thanks