#9396 Review annotations UI and system
geosolutions-it/MapStore2 pull request #9397
Opened 2023-09-06 16:20 UTC by allyoucanmap

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Feature and Redactor

## Issue

**What is the current behavior?**

#9396

**What is the new behavior?**

This PR refactors the annotations to add support in 3D maps

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

## Other useful information

2023-09-12 10:08 UTC, offtherailz commented on docs/developer-guide/mapstore-migration-guide.md
> +Please update the configuration if some customizations were applied to the Annotations plugin
```suggestion
The Annotation plugin has been updated to be supported also in 3D maps. This update introduced some changes:

- All the configurations related to the "Annotations" plugin has been removed from `localConfig.json` `defaultState` entry and moved to the `cfg` property of the plugin
- The annotations reducers is not needed anymore inside the default reducers of the app

Please update the configuration if some customizations were applied to the Annotations plugin by: 
- Removing `annotations` entry from your `localConfig.json` `defaultState`
- If you customized the app, you can remove the `annotations` reducer from default reducers.
```

2023-09-12 10:37 UTC, offtherailz requested changes
First of all, I like the final result a lot. :+1: :+1: :+1: :rocket: 

Please organize with @tdipisa to check my notes and make some of them or open issues for things that can be postponed. 

- [ ] Inline fixes for documentation etc... 
- [ ] Identify on hover for annotations do not look to work anymore See this map: http://localhost:8081/#/viewer/36414

current branch: http://localhost:8081/#/viewer/36414

[identify.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/d19ef4aa-23d2-4b94-96bc-9f9a63671238)

dev: https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/36414

[identify_dev.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/21c4eb22-c563-4bc2-a573-f5d8826443bc)

Anyway I noticed, that after activating the identify on over, when switching to another map, the identify stops working at all, so we may need to create a separate issue for investigating issues with this tool.

Map exported 
[identify_map.zip](https://github.com/geosolutions-it/MapStore2/files/12584910/identify_map.zip)


- [ ] grab icon in TOC is not fully visible

![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/dd95515a-b0c2-4dc1-9e6d-60b339e11a82)

- [ ] I was able to reproduce an invalid annotation here but I can not see the error details or how to fix it. (removing last coordinate fixed it).

[annotation_creation_error.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/9a1338f0-ee0d-4e3d-a2f9-57ca1653dc77)

![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/cf2607a9-db9d-402a-9c1b-d979d9dbfabc)

- [ ] The default style for circle is a little unnatural ( 0px outline, gray fill) . It should be 1 px outline, to be consistent with the other styles.

- [ ] Height reference relative to the pointer hieight do not seems to work for Geometry transformation, if we do not set "bring to the front". I don't know, maybe it is a cesium issue.
[geometry_transformation.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/51ab7e30-20aa-45b2-a7e2-3e0675dd4bd6)

2023-09-12 10:37 UTC, offtherailz commented on build/docma-config.json
> +                "web/client/plugins/Annotations/index.jsx",
Wrong file name caused the doc not to be added to the plugins documentation
```suggestion
                "web/client/plugins/Annotations/index.js",
```

2023-09-12 10:37 UTC, offtherailz commented on web/client/plugins/Annotations/index.js
> +  * Example of plugin configuration
```suggestion
  * Annotations Plugin. Implements annotations handling on maps.
  * @prop {object[]} lineDashOptions `[{value: [line1 gap1 line2 gap2 line3...]}, {...}]` defines how dashed lines are displayed.
  * Use values without unit identifier.
  * If an odd number of values is inserted then they are added again to reach an even number of values
  * for more information see [this page](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray)
  * @prop {string} defaultPointType default point type of marker geometry type. Can be `'marker'` or `'symbol'`
  * @prop {string} defaultShape the default symbol used when switching for the symbol styler
  * @prop {string} defaultShapeStrokeColor default symbol stroke color
  * @prop {string} defaultShapeFillColor default symbol fill color
  * @prop {number} defaultShapeSize default symbol shape size in px
  * @prop {string} format `'decimal'` or `'aeronautical'` degree for coordinates
  * @prop {string} defaultTextAnnotation default text value for text annotations (default: `'New'`)
  * @prop {object} geometryEditorOptions properties to be passed to `CoordinatesEditor` of `GeometryEditor`. For more information refer to the documentation of `CoordinatesEditor` component
  * @prop {string} symbolsPath the relative path to the symbols folder where `symbols.json` and SVGs are located (starting from the `index.html` folder, i.e. the root) `symbols.json` can be structured like [this](https://github.com/geosolutions-it/MapStore2/blob/90fb33465fd3ff56c4bbaafb5ab0ed492826622c/web/client/product/assets/symbols/symbols.json)
  * `symbols.json` present in `symbolsPath` folder is mandatory and it contains the list of symbols to be used in the Annotations Plugin
  * - width and height of SVGs should be 64px
  * - the `name` is related to the filename of the symbol (the file must be named `<name>.svg`).
  * - the `label` is the name used in the symbol dropdown menu
  * ```
  * [
  *   {"name": "filename", "label": "label"},
  *   {"name": "square", "label": "Square"}
  * ]
  * ```
  * @prop {boolean} geodesic **deprecated** draw geodesic annotation. By default `geodesic` is `true` (Currently applicable only for "circle" annotation type)
  * @prop {object[]} fields **deprecated** Available annotation fields (`title` and `description` are mandatory). A list of object specifying:
  *  - `name`: the field synthetic name
  *  - `type`: type of value for the field (`'text'` or `'html'`)
  *  - `validator`: (optional) function for rule for validation
  *  - `validationError`: (optional) id for the translations file containing the validation error message
  *  - `showLabel`: whether to show or not the label of the field in the viewer / editor
  *  - `editable`: whether the field can be edited or not in editing mode
  * @class Annotations
  * @memberof plugins
  * @static
  * @example
  * // Example of plugin configuration
```

2023-09-12 10:37 UTC, offtherailz commented on web/client/translations/data.it-IT.json
> +            "selectAnnotationFeature": "Seleziona una geometria annotation nel pannello di sinistra per editare coordinate e stili",
If we use "si prega" just before, let's use the same level of confidence  for the other strings.
```suggestion
            "selectAnnotationFeature": "Selezionare una geometria annotation nel pannello di sinistra per editare coordinate e stili",
```

2023-09-12 10:37 UTC, offtherailz commented on web/client/translations/data.it-IT.json
> +            "deactivatedMapInteraction": "Le interazioni di disegno delle annotazioni sono state disattivate perchè il '{pluginName}' plugin è stato attivato. Chiudi il '{pluginName}' plugin per atti
```suggestion
            "deactivatedMapInteraction": "Le interazioni di disegno delle annotazioni sono state disattivate perchè il '{pluginName}' plugin è stato attivato. Chiudere il '{pluginName}' plugin per attivare le interazioni di disegno delle annotazioni"
```

2023-09-12 12:52 UTC, tdipisa commented
@offtherailz I've discussed points above with @allyoucanmap and he will check all of them today to see how to proceed with some of them (eg. the identify one). For sure we will create a separate issue for normalizing the grab icon.

2023-09-12 15:51 UTC, allyoucanmap commented
@tdipisa @offtherailz opened a separated issue for the icon https://github.com/geosolutions-it/MapStore2/issues/9430

2023-09-12 15:56 UTC, allyoucanmap commented
> - [ ]  Height reference relative to the pointer hieight do not seems to work for Geometry transformation, if we do not set "bring to the front". I don't know, maybe it is a cesium issue.

@offtherailz @tdipisa based on the video it seems that the marker is inside the building so it's not visible when bring to front is false. Bring to front property makes the marker visible even if behind another feature

2023-09-12 16:14 UTC, allyoucanmap commented
> @offtherailz @tdipisa based on the video it seems that the marker is inside the building so it's not visible when bring to front is false. Bring to front property makes the marker visible even if behind another feature

After checking again it seems a problem related to the use of eyeOffset applied as workaround to manage the z-index of billboard, I'll open a new issue to investigate this

2023-09-13 07:51 UTC, offtherailz approved these changes
Tested, all looks good (and cool)

2023-09-13 09:17 UTC, merged

2023-09-13 09:17 UTC, allyoucanmap commented
@ElenaGallo, please test this PR on dev, thanks