#9325 enhancement: support for 'isNull' logical operator on date field in layer filter
geosolutions-it/MapStore2 pull request #9423
Opened 2023-09-11 10:00 UTC by mahmoudadel54

## Description
It is an enhancement feature added to filter layer from attribute table. Add 'isNull' operator to date field to filter attribute table based on it. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [s] Feature
 
## Issue
#9325 
**What is the current behavior?**
There was no operator for 'isNull' for date field
#9325 

**What is the new behavior?**
'isNull' operator is added to the filter layer for date field.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

## Other useful information

2023-09-11 11:00 UTC, allyoucanmap commented on web/client/components/data/query/FilterField.jsx
> +                <div className="filter-field-value">{this.props.filterField?.operator === 'isNull' ? null : selectedAttribute && this.props.filterField.operator ? this.renderValueField(selectedAttrib
Could we remove this one and place this logic in the [DateField](https://github.com/geosolutions-it/MapStore2/blob/504d686ca9363ff0314dc763b60265a9c94ffa4d/web/client/components/data/query/DateField.jsx#L41) component and use the operator to disable or hide the value field if needed?

2023-09-12 08:00 UTC, allyoucanmap requested changes
The implementation is good, just few changes to apply:

- [ ] use disabled prop instead of `this.props.operator === "isNull" ? '' :` to keep it consistent with string field
- [ ] fix failing test

About the disabled prop,
current implementation:
![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/21674278-b7a1-4a8d-b3cc-75a373250654)

expected:
![2023-09-12 09_54_38-Window](https://github.com/geosolutions-it/MapStore2/assets/19175505/f3b4a699-76c6-4077-a5fe-d24db95bff48)

Note: both UTCDateTimePicker and NumberPicker support disabled prop that could be applied as follow `disabled={this.props.operator === "isNull"}`

2023-09-12 12:45 UTC, allyoucanmap approved these changes
LGTM

2023-09-12 12:57 UTC, merged

2023-09-12 12:58 UTC, allyoucanmap commented
@ElenaGallo please test this in dev and let us know if we can backport on 2023.02.xx, thanks.
Note: this also introduces `isNull` operator for numbers, dates, date-time and time

2023-09-12 14:39 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport this to 2023.02.xx.Thanks