Update User Guide - Add COG catalog option
geosolutions-it/MapStore2 pull request #9486
Opened 2023-09-25 13:12 UTC by ElenaGallo

## Description

Add COG catalog option in [Catalog](https://mapstore--9486.org.readthedocs.build/en/9486/user-guide/catalog/#cog-catalog) Section

2023-09-25 15:43 UTC, tdipisa requested changes

2023-09-25 15:43 UTC, tdipisa commented on docs/user-guide/catalog.md
> +MapStore allows to add COG as layers and backgrounds through the *Catalog* tool, a specific source type can be configured as follows by specifying the URL of a reachable `geotiff.tif`
```suggestion
MapStore allows to add COG layers (also as a background) through its *Catalog* tool where a specific source type can be configured as follows by specifying the URL of a reachable COG `.tif` resource.
```

2023-09-25 15:44 UTC, tdipisa requested changes
@ElenaGallo please also fix the PR source branch name

2023-09-26 08:00 UTC, ElenaGallo commented
Closed in favor of #9492

2023-09-26 08:00 UTC, closed without merging