#9469: COG layer zoom to extent
geosolutions-it/MapStore2 pull request #9497
Opened 2023-09-26 14:51 UTC by dsuren1

## Description
This PR adds possibility to fetch extent of COG layers

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
- #9469 

**What is the new behavior?**
- Ability to fetch metadata of COG layer to support zoom on extent on layer
- Catalog record data model updated

### Screenshot
<img width="588" alt="Screenshot 2023-09-26 at 8 08 19 PM" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/0d4f7bc3-328d-41e3-a87d-f95bf61503e0">

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-09-26 14:59 UTC, offtherailz commented on web/client/translations/data.es-ES.json
> +                "tooltip": "Esta opción recuperará metadatos para admitir el zoom a la capa al agregarla. Puede ralentizar la operación de búsqueda si las imágenes son demasiado grandes o demasiadas.
```suggestion
                "tooltip": "Esta opción recuperará metadatos para admitir el zoom a la capa. Puede ralentizar la operación de búsqueda si las imágenes son demasiado grandes o demasiadas."
```

2023-09-26 15:00 UTC, offtherailz commented on web/client/translations/data.fr-FR.json
> +                "tooltip": "Cette option récupérera les métadonnées pour prendre en charge le zoom sur la couche lors de l'ajout. Cela peut ralentir l'opération de recherche si les images sont trop g
```suggestion
                "tooltip": "Cette option récupérera les métadonnées pour prendre en charge le zoom sur la couche. Cela peut ralentir l'opération de recherche si les images sont trop grandes ou trop nombreuses."
```

2023-09-26 15:00 UTC, offtherailz commented on web/client/translations/data.de-DE.json
> +                "tooltip": "Diese Option ruft Metadaten ab, um das Zoomen auf die Ebene beim Hinzufügen zu unterstützen. Es kann den Suchvorgang verlangsamen, wenn die Bilder zu groß oder zu viele si
```suggestion
                "tooltip": "Diese Option ruft Metadaten ab, um das Zoomen auf Ebene zu unterstützen. Es kann den Suchvorgang verlangsamen, wenn die Bilder zu groß oder zu viele sind."
```

2023-09-26 16:25 UTC, offtherailz requested changes
- [ ] Using this map http://localhost:8081/#/viewer/46215 (with catalog updated accordingly, given that they take a very long time, downloading something like 500MB) instead of zooming I have this errors ( and the zoom do not happen): 

```
Error in epic "zoomToExtentEpic". Original error: TypeError: Cannot read properties of null (reading 'getSimplifiedGeometry')
    at View.fit (View.js:1343:53)
    at eval (Map.jsx:316:29)
    at SwitchMapSubscriber.eval [as project] (map.js:206:7)
    at SwitchMapSubscriber._next (switchMap.js:88:27)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at MapSubscriber._next (map.js:83:26)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at WithLatestFromSubscriber._next (withLatestFrom.js:113:34)
    at Subscriber.next (Subscriber.js:89:18)
    at Subject.next (Subject.js:55:25)
[..]
EpicsUtils.js:31 Uncaught TypeError: Cannot read properties of null (reading 'getSimplifiedGeometry')
    at View.fit (View.js:1343:53)
    at eval (Map.jsx:316:29)
    at SwitchMapSubscriber.eval [as project] (map.js:206:7)
    at SwitchMapSubscriber._next (switchMap.js:88:27)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at MapSubscriber._next (map.js:83:26)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at WithLatestFromSubscriber._next (withLatestFrom.js:113:34)
    at Subscriber.next (Subscriber.js:89:18)
    at Subject.next (Subject.js:55:25)
    at eval (createEpicMiddleware.js:80:16)
    at eval (createEpicMiddleware.js:79:22)
```
Please handle this use case.

- [ ] The request really takes eons... we should open an issue to allow to cancel the catalog request while loading.
- [ ] Can we avoid to do these requests on save, but only on search, so we avoid the double time?

2023-09-27 06:55 UTC, dsuren1 commented
@offtherailz 
> * [ ]  Using this map http://localhost:8081/#/viewer/46215 (with catalog updated accordingly, given that they take a very long time, downloading something like 500MB) instead of zooming I have this errors ( and the zoom do not happen):

It caused because geokeys are empty for the layer which results in empty crs data. **Fixed**

> * [ ]  Can we avoid to do these requests on save, but only on search, so we avoid the double time?

I have added cache to avoid requests. Kindly let me know if I need to increase the expiry time, as I'm using the default expiry time now.

2023-09-27 08:46 UTC, offtherailz approved these changes

2023-09-27 08:47 UTC, offtherailz commented
I think your chages are a good compromise. Thank you very much.

2023-09-27 08:48 UTC, merged

2023-09-27 10:30 UTC, ElenaGallo commented
Test passed, @dsuren1 please backport. Thanks