support loading COG layers from query params
geosolutions-it/MapStore2 pull request #9531
Opened 2023-10-02 12:15 UTC by landryb

## Description
work in progress for #9527

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**

#9527

**What is the new behavior?**
http://localhost:8081/#/viewer/new?actions=%5B%7B%22type%22:%22CATALOG:ADD_LAYERS_FROM_CATALOGS%22,%22layers%22:%5B%22testtitle%22%5D,%22sources%22:%5B%7B%22type%22:%22cog%22,%22url%22:%22https%3A%2F%2Fcogeo.craig.fr%2Fopendata%2Fortho%2Forthocraig3_vichy_2021.cog.tif%22%7D%5D%7D%5D should work and zoom to the provided COG

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-10-02 13:06 UTC, landryb commented
@dsuren1 help/feedback welcome on this. Even with `projectionDefs` containing `EPSG:2154` i cant get the layer to be automagically added.

2023-10-02 14:39 UTC, landryb commented
ok it loads the cog with your tweak from https://github.com/geosolutions-it/MapStore2/issues/9527#issuecomment-1742711134 but im not comfy with it.. maybe i should set name to the value of `text` to avoid having a specialcase like this or that can lead to conflicts later on ?

also, it doesn't automatically zoom to the COG extent even if it knows its bbox (i have the 'zoom to layer' button in the toc), while it's the case when the COG is added from the catalog.

2023-10-02 14:48 UTC, landryb commented
with 9f2f3c93a it works but i have to figure out what triggers the zoom to layer behaviour

2024-01-15 15:55 UTC, landryb commented
> Thank you so much for contributing @landryb. We will check this asap. This is still WIP n your side as reported din description?

no this is ready for review, eslint is happy with the js changes, and i've just tested it backported on a local 2023.02 build of ms2-georchestra and it does what i expect, eg `?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":["cog clerco cc46"],"sources":[{"type":"cog","url":"https%3A%2F%2Fcogeo.craig.fr%2Fopendata%2Fortho%2Fortho25_cc46_clerco_1996.cog.tif"}]}]` properly loads the COG at initial ms2 loading.

2024-01-15 15:56 UTC, landryb commented
updated the issue description to state that it wasnt just WIP, but working for me :) it was already working in the initial PR from october, but it had stalled and bitrotted.

2024-02-23 09:50 UTC, landryb commented
can i get a review on this before it bitrots more ? should i rebase the branch or a merge commit like [f22d540](https://github.com/geosolutions-it/MapStore2/pull/9531/commits/f22d5405b1745d4c221ded6c6355ac5cc9137779) above is acceptable ?

2024-02-23 12:05 UTC, dsuren1 commented
@landryb we are waiting for this [PR](https://github.com/geosolutions-it/MapStore2/pull/9857) to be merged as it refactors the COG workflow along with options to style. I think you may have to rebase again to include the new changes after the linked PR is merged.

2024-03-22 06:24 UTC, dsuren1 commented
@landryb Could you please align your changes with latest master. Thanks!

2024-03-25 10:51 UTC, landryb commented
> @landryb Could you please align your changes with latest master. Thanks!

sure, will try to understand what happened in #9857 & #10089 wrt my changes.. from my understanding i should reuse `LayerUtils.getLayerConfig` instead of my own `fetchMetadata` (added in 461da074, used in 71899b36c) .. and test.

2024-03-25 13:50 UTC, landryb commented
@dsuren isnt there a problem with `LayerUtils.getLayerConfig` added in d683b824 ? the order of parameters doesn't seem to be match between the call in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/catalog/COG.js#L57:
```
return LayerUtils.getLayerConfig({url, controller, layer})
```
and the API in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/cog/LayerUtils.js#L56
```
export const getLayerConfig = ({ url, layer, controller })
```

i dunno if that matters.. but whatever order of parameters i put in my code, eslint complains if i try building the layer object/parameter on the fly:
```
Line 72, column 52: /data/src/georchestra/mapstore2-georchestra/MapStore2/web/client/api/catalog/COG.js: Unexpected token (72:52)

  70 |     return Promise.all([...layers]).then((_layers) => {
  71 |         if (!_layers.length) {
> 72 |             return LayerUtils.getLayerConfig({_url, {
```
eslint is happy if i build the layer object before, as done in [0260ac7](https://github.com/geosolutions-it/MapStore2/pull/9531/commits/0260ac7eaadceb0de0de64a10c5bc7d371c5c8c4) (untested yet)

2024-03-25 14:20 UTC, dsuren1 commented
@landryb 

`getLayerConfig` takes object as a parameter, the order of the prop is not a concern but the name of the prop passed. Modify your code as shown below

```diff
> 80 |        return LayerUtils.getLayerConfig({url: _url, layer, controller})
```

2024-03-25 14:49 UTC, landryb commented
> @landryb
> 
> `getLayerConfig` takes object as a parameter, the order of the prop is not a concern but the name of the prop passed. Modify your code as shown below
> 
> ```diff
> return LayerUtils.getLayerConfig({url: _url, layer, controller})
> ```

ah, thanks, now i understand the logic, it wasnt obvious for me that the variable names were auto matched on object properties. fixed with [60e7269](https://github.com/geosolutions-it/MapStore2/pull/9531/commits/60e72699e3245bfad56043ad57e52225efc0686b) and i've been able to successfully test it on a locally running instance with `?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":["Vichy 3cm"],"sources":[{"type":"cog","url":"https%3A%2F%2Fcogeo.craig.fr%2Fopendata%2Fortho%2Forthocraig3_vichy_2021.cog.tif"}]}]` as params

2024-04-09 11:00 UTC, dsuren1 requested changes
@landryb 
Kindly update the doc`map-query-parameters.md` for adding COG layer via query paramater similar to other layer type. Also a note in the docs regarding the 'limitation' mentioned below. Thanks!


@offtherailz @tdipisa 
The only limitation to adding COG layer via query parameter, is that it is not possible to cancel the metadata fetch call as there is not control exposed at the moment. So when a big source is requested the map load time maybe significantly affected.

2024-04-10 11:43 UTC, dsuren1 requested changes

2024-04-10 11:43 UTC, dsuren1 commented on docs/developer-guide/map-query-parameters.md
> +Depending on the internal structure optimization done on the remote COG file, the map load time might be long.
```suggestion
!!! note
    Depending on the internal structure optimization done on the remote COG source, the map load time might be long. Furthermore, it is not feasible to cancel metadata fetching for the COG layer(s) when loading layers via query parameters.
```

2024-04-10 11:44 UTC, dsuren1 approved these changes

2024-04-10 11:53 UTC, merged

2024-04-10 12:12 UTC, dsuren1 commented
@ElenaGallo Kindly test it in DEV and let us know if it can be backported. Thanks!

2024-04-10 14:40 UTC, ElenaGallo commented
test passed, @dsuren1 please backport to 2024.01.xx. Thanks

2024-04-16 07:51 UTC, tdipisa commented
@ElenaGallo @dsuren1 this is for 2024.01.01 so let's wait the delivery of 2024.01.00 before merging the backport.