Fix #9575 Avoid full rerender in filterRenderer
geosolutions-it/MapStore2 pull request #9577
Opened 2023-10-10 17:14 UTC by offtherailz

## Description

The issue happens when fields is not defined. In selector the "[]" was regenerated everytime.
I fixed the selector and added an additional security in featureEditor to avoid regeneration of filterRenderers (and so loss of focus) when the values are equal.
This guarantees that if the feature grid receives them dynamically for some reason, the filter renderers are not re-computed.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9575

**What is the new behavior?**

Fix #9575
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-10-11 11:22 UTC, dsuren1 requested changes
@offtherailz 
The fix works fine. But it introduces a new issue where the filter row is _hidden on first load_ of feature grid. Kindly check if this is happening. Thanks!

https://github.com/geosolutions-it/MapStore2/assets/26929983/577be0df-75c4-46eb-a130-62d1ca32d185

2023-10-11 16:50 UTC, offtherailz commented
Thank you @dsuren1 , I didn't noticed it. 
This is because I used wrongly `useMemo` API. Actually there is no way to pass a custom comare function to it. So I removed it and the test for it.

2023-10-11 16:50 UTC, offtherailz commented on web/client/plugins/featuregrid/__tests__/FeatureEditor-test.jsx
> +
```suggestion
```

2023-10-11 16:51 UTC, offtherailz commented on web/client/plugins/featuregrid/FeatureEditor.jsx
> +    // reason the describeFeatureType or fields are generated but equal.
```suggestion
```

2023-10-12 05:08 UTC, dsuren1 approved these changes

2023-10-12 05:09 UTC, merged

2023-10-12 08:39 UTC, tdipisa commented
@ElenaGallo please test in DEV and QA

2023-10-16 10:55 UTC, ElenaGallo commented
Test passed on DEV, @offtherailz please backport to the stable branch. Thanks