Fix #9638 ui issue with context when adding all plugins
geosolutions-it/MapStore2 pull request #9639
Opened 2023-10-20 15:57 UTC by MV88

## Description

fixed the issues in the contexts

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9638

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-10-23 16:04 UTC, offtherailz approved these changes
This menu is not so visible
![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/80a28e3c-d4a7-4293-8146-707ef44ee8df)

So I pushed some changes to make it look like this:

![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/b2676c1a-9887-4899-a3a7-11dc987bcd23)

From my testings now it works well. Please double check you too @MV88

2023-10-23 16:36 UTC, offtherailz requested changes
- [ ] with #/context/Longitudinal_profile
the overflow is now broken: 

![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/e9e02dfa-47c3-445f-9286-e9f6432e52bd)

Previous implementation worked correctly: 
![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/9495d3d7-d2a7-49e4-a9ca-48e340a23830)

- [ ] I fixed the menu style. Anyway when you close the burger menu, the popup stays open. We have to hide it. 
- [ ] Fix `useEffect`

2023-10-24 09:30 UTC, offtherailz approved these changes
Simplified logic behind menu

2023-10-24 09:30 UTC, offtherailz commented on web/client/plugins/longitudinalProfile/Menu.jsx
> +        MenuComp = DropDownMenu;
Solved

2023-10-24 09:42 UTC, merged

2023-10-24 09:43 UTC, MV88 commented
@ElenaGallo please test it in DEV

2023-10-24 11:06 UTC, ElenaGallo commented
Test passed, @tdipisa  it is possible to  marge the backport  https://github.com/geosolutions-it/MapStore2/pull/9652