[Backport 2023.02.xx] fix issue of not showing background layer in case of switching from 2D mode to 3D mode (#9464)
geosolutions-it/MapStore2 pull request #9646
Opened 2023-10-23 17:51 UTC by mahmoudadel54

## Description
backport 2023.02.xx - #9464  :fix issue of not showing background layer in case of switching from 2D mode to 3D mode (#9614 )

Fixing not showing the default background layer on the map when user switches from 2D mode to 3D mode.

2023-10-24 09:15 UTC, MV88 requested changes

2023-10-24 09:15 UTC, MV88 commented on web/client/configs/localConfig.json
> +				"type": "backgrounds",
this is different from the original  PR

![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/c1271ce8-6677-437a-9b8e-f2a6b862c5ba)


please fix it

2023-10-24 09:15 UTC, MV88 commented on web/client/configs/new.json
> -		"layers": [
same here, if you have enabled some formatter please disable it, at least for this project

2023-10-27 08:45 UTC, tdipisa commented
@mahmoudadel54 waiting for GS-MAIN update before proceeding with the backport like for #9361 and #9379

2023-10-27 08:46 UTC, closed without merging