#9216: handle fixing not visibility of spatial filter for widgets created by attribute table
geosolutions-it/MapStore2 pull request #9674
Opened 2023-10-30 03:02 UTC by mahmoudadel54

## Description
Handle fixing not visibility of spatial filter for widgets that created by the attribute table

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#9216 

**What is the current behavior?**
#9216 

**What is the new behavior?**
If user makes a spatial filter via attribute table then wants to create a widget from attribute table - like a chart widget for example - and wants to apply the same spatial filter on the widget. 
By clicking on spatial filter button on the chart widget, user can see the applied spatial filter on map.  

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-11-03 17:43 UTC, MV88 requested changes
please provide more info

2023-11-03 17:43 UTC, MV88 commented on web/client/epics/widgetsbuilder.js
> +// };
remember to erase commented code

2023-11-03 17:43 UTC, MV88 commented on web/client/epics/widgetsbuilder.js
> +// import { featureTypeSelected } from '../actions/wfsquery';
same here

2023-11-03 17:43 UTC, MV88 commented on web/client/epics/widgetsbuilder.js
> +                // featureTypeSelected(...getFTSelectedArgs(getState())),
can you explain why this is going to fix the issue?

2023-11-07 11:29 UTC, MV88 requested changes
you are not adding "widgets" when calling featureTypeSelected in the e widgetsBuilder epic

missing tests for actions

2023-11-07 11:29 UTC, MV88 commented on web/client/actions/wfsquery.js
> +export function featureTypeSelected(url, typeName, fields = [], owner) {
add a unit test for this

2023-11-07 11:29 UTC, MV88 commented on web/client/actions/wfsquery.js
> +export function featureTypeLoaded(typeName, featureType, owner) {
add a unit test for this

2023-11-07 11:29 UTC, MV88 commented on web/client/actions/wfsquery.js
> +export function createQuery(searchUrl, filterObj, owner) {
add a unit test for this

2023-11-10 16:45 UTC, MV88 approved these changes

2023-11-10 16:46 UTC, merged

2023-11-10 16:46 UTC, MV88 commented
@ElenaGallo please test it in DEV

2023-11-13 09:48 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport this to 2023.02.xx branch. Thanks

2023-11-13 10:14 UTC, tdipisa commented
@mahmoudadel54 @MV88 before backporting this issue I would like to clarify if [this new issue](https://github.com/geosolutions-it/MapStore2/issues/9697) created by @ElenaGallo is connected to the development made within this PR. 
If yes, the milestone of the new issue should change accordingly @ElenaGallo

2023-11-13 11:30 UTC, mahmoudadel54 commented
> @mahmoudadel54 @MV88 before backporting this PR I would like to clarify if [this new issue](https://github.com/geosolutions-it/MapStore2/issues/9697) created by @ElenaGallo is connected to the development made within this PR. If yes, the milestone of the new issue should change accordingly @ElenaGallo

I have checked this issue #9697 , it has been existing before this PR. 
@tdipisa @MV88

2023-11-14 16:22 UTC, tdipisa commented
Got it and I've better checked the issue description. It is not connected with this PR. Thank you @mahmoudadel54, please proceed with the backport.

2023-11-15 07:12 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport this to 2023.02.xx branch. Thanks

Backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/9704