#9683: add Details Panel for MS dashboard
geosolutions-it/MapStore2 pull request #9689
Opened 2023-11-10 13:43 UTC by mahmoudadel54

## Description
It is a new feature added to MS for dashboard. I added Details panel widget to dashboard. 
- It reflects on Resource grids, dashboard views [View, Edit modes].
- The tool have the same options (eg. show as modal, show at startup etc.)
- The tool is defined in the same way of the corresponding one for maps.
- Edit the layout to put add widget & show/hide connection buttons to the sidebar menu

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#9683 

**What is the current behavior?**
#9683 

**What is the new behavior?**
Details panel widget is added for dashboard. User can add/edit dashboard details and set some details for the dashboard and set some options like opening this details on startup, show details on modal/right panel via resource grids and from dashboard view page in view/edit modes.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

2023-11-13 14:07 UTC, MV88 requested changes
- [ ] there is clearly something wrong here when you create a new dashboard

![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/25c73f85-770b-49ef-bd6e-bdb658d1828b)

while it works fine when you load a dashboard
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/eb4801ca-6619-4616-9466-d628b05fcb46)


- [ ] the style of plus button should be blank bg (similar to others) from the start and maybe should be the second one, after login and  when pressed it should become like it is now. because primary background means something active
- [ ] also we should make become a only open button or become unclickable (disabled but visible)

- [ ] i cannot drag and drop or resize widgets on the right if I load this dashboard: http://localhost:8081/?debug=true#/dashboard/21694
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/f62a2f59-9e35-436b-9e05-cd474e5507b6)
it works until a certain point notice the cursor, maybe that is the space of details panel which covers click on the area
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/7664c7d0-4213-4d42-84cd-e80efc25afa8)
anyway here the placeable area  (red background area) looks properly calculated
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/426b0859-c1a3-4d61-bc1f-6ed792bc79e2)

2023-11-15 09:27 UTC, mahmoudadel54 commented on web/client/plugins/SidebarMenu.jsx
> +            <div id="mapstore-sidebar-menu-container" className={`shadow-soft ${this.props.did ? "fullHightSideBar" : ""}`} style={this.getStyle(this.props.style)}>
did is dashboard id, but I removed it to make sidebar generic as you said

2023-11-17 14:33 UTC, MV88 requested changes
looks better i have only noticed a few minor things:

- [ ] the language selector goes behind body panel, but with a z-index it gets fixed, please test
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/29a51030-407d-4912-b8dd-1301636d993f)
- [ ] the Save button has no tooltip
- [ ] loading property is no longer needed in the DashboardEditor plugin

2023-11-20 06:43 UTC, mahmoudadel54 commented
> looks better i have only noticed a few minor things:
> 
> * [ ]  the language selector goes behind body panel, but with a z-index it gets fixed, please test
>   ![image](https://user-images.githubusercontent.com/11991428/283824063-29a51030-407d-4912-b8dd-1301636d993f.png)
> * [ ]  the Save button has no tooltip
> * [ ]  loading property is no longer needed in the DashboardEditor plugin

For z-index point, I see that z-index of #mapstore-sidebar-menu-container = 1030 
I have tried to put a z-index to #mapstore-navbar-container with 1031 and it works well so I can specify this style in dashblaod.less to be just for dashboard page only instead of generalize it. 
What do you think ? @MV88

2023-11-20 08:58 UTC, MV88 commented
> #mapstore-navbar-container

hi if the fix you found is increasing  #mapstore-navbar-container z-index i would not put it inside dashboard.less. but instead in navbar.less and also maybe you can remove the z-index definition of that inside dashboard.less

2023-11-21 09:14 UTC, merged

2023-11-21 09:21 UTC, MV88 commented
@ElenaGallo please test in DEV

2023-11-22 14:40 UTC, ElenaGallo commented
@mahmoudadel54 @tdipisa There are no Export, Import and Delete buttons in the new sidebar.

**QA**
![qa](https://github.com/geosolutions-it/MapStore2/assets/56537133/fa4ca3e9-61db-4dcc-9570-181b3aa92c33)

**DEV**
![dev](https://github.com/geosolutions-it/MapStore2/assets/56537133/d9266011-fe7e-4463-9531-e9b9180325cb)

2023-11-23 11:46 UTC, tdipisa commented
@mahmoudadel54 I'm sorry but this is of course not correct 
![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/e29e7a07-bfa2-4b5b-957e-af2d1571f46b)

this should be fixed to be resource related

2023-11-24 16:34 UTC, MV88 commented
this has to be backported in c040-2023.02.xx

2023-11-27 08:53 UTC, mahmoudadel54 commented
> this has to be backported in c040-2023.02.xx

Backport is done --- > https://github.com/geosolutions-it/MapStore2/pull/9750