Fix #9685 Add possibility to use vector layers inside GeoProcessing tool
geosolutions-it/MapStore2 pull request #9691
Opened 2023-11-10 14:20 UTC by MV88

## Description

* refactored the way the counter for each tool is handled, plus some clean up
* add possibility to configure a wpsUrl to be used as default source in the plugin otherwise the url from the layer will be used
* changed the way the groups for buffered and  intersected layers are generated

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9685

**What is the new behavior?**

you can use vector layers inside GeoProcessing plugin 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-11-20 09:42 UTC, offtherailz requested changes
- [ ] Zoom to feature selected incorrect

https://github.com/geosolutions-it/MapStore2/assets/1279510/cafe7f31-748d-4e56-b170-c3a168af7ca5

- [ ] When switch layer, old feature remain selected

[selected_.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/df90aa5f-7cdf-4db3-9817-0ffa2edf68ff)

- [ ] I tried to create a buffer layer, and  then use this buffer layer to intersect with states layer. The result looks to be the buffer layer itself, instead of the intersection.

[Intersection_wrong.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/f4194f3e-0c5d-4dc3-9d9f-8a0bab4086f0)

Please test extensively before submitting reviews.

2023-11-21 15:07 UTC, MV88 commented
@offtherailz PR is ready again for review. 

- when fixing last point i encountered a bug in geoserver (using stable)

basically it's this request (trying to intersect two multipolygon)
[failing intersection request.txt](https://github.com/geosolutions-it/MapStore2/files/13427790/failing.intersection.request.txt)

with this error

```
{
    "type": "FeatureCollection",
    "features": []
}<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 https://gs-stable.geosolutionsgroup.com/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>An error occurred while encoding the results of the process
found non-noded intersection between LINESTRING ( -109.0472 35.9967,
-109.046 34.9546 ) and LINESTRING ( -109.0463 34.9052,
-109.046 34.9546 ) [ (-109.046,
    34.9546, NaN)
]</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>

```

currently it tells you there is no intersection between the two. but we can better parse the result by dispatching a more appropriate notification

2023-11-22 08:34 UTC, offtherailz commented
@MV88 please fix the tests

2023-11-22 12:37 UTC, MV88 commented
> @MV88 please fix the tests

done

2023-11-27 17:47 UTC, offtherailz commented
As discussed with @aaime, @MV88 is right, this issue  on JTS causes the proble misted https://github.com/locationtech/jts/issues/938 WE could try to activate OverlayNG to workaround it

2023-12-04 09:21 UTC, tdipisa commented
@offtherailz thank you 

>-Djts.overlay=ng

Let's enable this in gs stable to complete the review.

>We should change strategy to avoid upload/download/upload roundrip. Maybe this is an optimization, so it is not strictly mandatory, but could be useful to move complexity.

>We should use, whenever possible, WFS directly or sending directly the geometry when vector data locally is available.
What are the counter-sides for this strategy?

Let's wait for the review to be completed then we can consider to do this optimization as part of this PR.

2023-12-04 11:34 UTC, randomorder commented
JAVAT_OPTS update on `gs-stable` @tdipisa

2023-12-04 11:44 UTC, tdipisa commented
Thank you @randomorder.
@offtherailz you can proceed and complete the review.

2023-12-06 15:25 UTC, offtherailz commented
It works perfectly now :+1:

2023-12-06 16:56 UTC, merged

2023-12-06 16:56 UTC, MV88 commented
@ElenaGallo please test it in DEV

2023-12-07 09:28 UTC, ElenaGallo commented
@MV88 It is not possible to buffer or intersect a measurement layer.


https://github.com/geosolutions-it/MapStore2/assets/56537133/992dc822-dbb3-4210-a756-39ca26b5415e