#9553: Improving readability of long attribute values in attribute table and table widgets
geosolutions-it/MapStore2 pull request #9701
Opened 2023-11-14 12:00 UTC by mahmoudadel54

## Description
In this PR, I handled showing a tooltip for long attribute value in attribute table and table widgets only if user hovers on the cells that has shown content less than the attribute value. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Enhancement

## Issue
#9553 

**What is the current behavior?**
#9553 

**What is the new behavior?**
 Showing a tooltip for long attribute value in attribute table and table widgets only if user hovers on the cells that has shown content less than the attribute value. 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
I created a generic enhancer with name "handleLongTextEnhancer" to handle the tooltip for long content

2023-11-14 15:50 UTC, MV88 requested changes
looks ok, but I have some inline comments to get your attention

2023-11-14 15:50 UTC, MV88 commented on web/client/components/misc/enhancers/handleLongTextEnhancer.jsx
> +export  const handleLongTextEnhancer = (RenderFormatter) => (props) => {
maybe we can call this just Component or Wrapped
```suggestion
export  const handleLongTextEnhancer = (Component) => (props) => {
```

2023-11-14 15:50 UTC, MV88 commented on web/client/components/misc/enhancers/handleLongTextEnhancer.jsx
> +export  const handleLongTextEnhancer = (RenderFormatter) => (props) => {
please add jsdoc here with also an example

2023-11-14 15:50 UTC, MV88 commented on web/client/components/misc/enhancers/handleLongTextEnhancer.jsx
> +        overlay={isContentOverflowing ? <Tooltip id="tooltip">{RenderFormatter ? <RenderFormatter {...props} /> : value}</Tooltip> : <></>}
is the ternary needed? i mean don't we always have the Wrapped component when using this enhancer?

if it is not needed we can remove it here and in the below

2023-11-15 16:04 UTC, MV88 commented on web/client/components/misc/enhancers/handleLongTextEnhancer.jsx
> + * @param {Component} Wrapped the wrapper to add tooltip for its long content
```suggestion
 * @param {Component} Wrapped the component wrapped with a tooltip when its content is too long
```

2023-11-15 16:04 UTC, MV88 approved these changes

2023-11-21 08:42 UTC, merged

2023-11-21 08:42 UTC, MV88 commented
@ElenaGallo please test it in DEV

2023-11-21 11:01 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2023.02.xx. Thanks

2023-11-21 12:08 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport to 2023.02.xx. Thanks

Backport is done --- > #9719