#9706: Allow time range filtering for Attribute Table quick filter
geosolutions-it/MapStore2 pull request #9743
Opened 2023-11-23 23:14 UTC by mahmoudadel54

## Description
- adding filter operators dropdown list in attribute table that includes range operator for time/date attributes 
- creating a custom picker for range
- write unit tests
- Edit in style 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#9706 

**What is the current behavior?**
#9706 

**What is the new behavior?**
Different filter operators dropdown is added to the attribute table columns including range time/date

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

2023-11-24 14:48 UTC, MV88 requested changes
The functionality works well, but  there a few things to change and some inconsistencies/bugs to handle:
- [ ] operator must match
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/b4ca217a-489b-4d92-a2a3-5dad51598fca)
- [x] cursor style
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/02115c33-64fb-430a-b228-fe4f67a68dc4)
- [x] invalid range 
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/47da0ec3-4a16-4cee-87c0-b4367bce231f)
- [x] one single icon was requested
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/b01a8e06-76d7-4b7a-abfd-660deb6ada76)
- [x] little style issue
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/8d4fc46d-a926-41dc-930a-dc427b24fd8c)
- [x] improve focus style on time picker
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/1b28d134-8d16-4cf8-8827-e59c9e86dce2)
- [x] improve style on operator
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/fa7b0bd6-cd33-4d0a-878a-e21299163a77)
- [x] inconsistent value after wsitching back from between operator >< 
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/309eb2b6-9918-475b-bdff-5aa9f71c1aed)
- [ ] single datetime field is not using new component and must use it

2023-11-24 14:48 UTC, MV88 commented on web/client/components/data/featuregrid/filterRenderers/AttributeFilter.jsx
> +                // dropUp={this.props.dropUp}
remove comment

2023-11-24 14:48 UTC, MV88 commented on web/client/components/data/featuregrid/filterRenderers/AttributeFilter.jsx
> +        isWithinAttrTbl: PropTypes.bool
i think that this should be removed in the future since also attribute table in dashboard should inherit timerange changes

2023-11-24 14:53 UTC, MV88 requested changes
some extra points

2023-11-24 14:53 UTC, MV88 commented on web/client/components/data/featuregrid/filterRenderers/AttributeFilter.jsx
> +                    if (isValueExist || isNullOperatorSelected || isOperatorChangedFromIsNullAndValueNotExist ) this.props.onChange({value: isNullOperatorSelected ? null : isValueExist, attribute: th
lots of logic here, not very easy to track

2023-11-24 14:53 UTC, MV88 commented on web/client/components/misc/datetimepicker/CustomDateTimePickerWithRange.js
> +export default DateTimePicker;
name exported is different from file name

2023-12-13 13:25 UTC, MV88 requested changes
- [x] this is not done "one single icon was requested" as it was requested in the issue here
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/87c67166-550e-4f20-8e77-8b788fbaa265)
- [ ] calendar is not fully visible, can you add at leas a scrollbar if you can't display as drop up?
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/154e3018-5ec3-4af0-bda1-88b372c4fed5)


the rest seems ok a part some inline comment

2023-12-13 13:25 UTC, MV88 commented on web/client/components/data/featuregrid/filterRenderers/AttributeFilter.jsx
> +        if (isValid) this.props.onChange({value, attribute: this.props.column && this.props.column.key, inputOperator: this.state.operator});
please avoid at all inline if

2023-12-13 13:25 UTC, MV88 commented on web/client/components/misc/datetimepicker/DateTimePicker.js
> +        }, {});
you can use "omit by" from lodash lib

or better if you which are the props you need you can use "pick"

2023-12-14 10:05 UTC, mahmoudadel54 commented
> * [ ]  this is not done "one single icon was requested" as it was requested in the issue here

I don't know how can I get the attached icon, I searched for the icons in react-widget lib version 3.5.0 but I didn't find
@MV88 

> * [ ]  calendar is not fully visible, can you add at leas a scrollbar if you can't display as drop up?

I have tried much time to use drop up but there is a big css issue I couldn't resolve it

2023-12-14 12:51 UTC, mahmoudadel54 commented
@MV88 
For adding scroll in dates picker, this is a demo demonstrating implementation of it. Is it acceptable ?

https://github.com/geosolutions-it/MapStore2/assets/58145645/6808bd95-5655-4dc5-aa5e-05d1adf75369

2023-12-14 13:48 UTC, MV88 commented
> > * [ ]   this is not done "one single icon was requested" as it was requested in the issue here
> 
> I don't know how can I get the attached icon, I searched for the icons in react-widget lib version 3.5.0 but I didn't find the required one @MV88

I'm sorry maybe you haven't done it before. 
You have to create a new one
- take the calendar and time icons and merge them together by using a tool for editing svg like inkscape
- put the new svg in this folder https://github.com/geosolutions-it/MapStore2/tree/master/web/client/themes/default/svg
- make it similar in size to the others
- run npm run generate:icons
- test calling it inside glyphicon component the the name of the svg file

> > * [ ]   calendar is not fully visible, can you add at leas a scrollbar if you can't display as drop up?
> 
> I have tried much time to use drop up but there is a big css issue I couldn't resolve it and during trying handle this point, it reflects on other css for the attribute table I will try the 1st suggestion of making scroll

ok i'll try to give a better look, but maybe @allyoucanmap has a suggestion on this point

2023-12-14 13:49 UTC, MV88 commented
> @MV88 For adding scroll in dates picker, this is a demo demonstrating implementation of it. Is it acceptable ?
> 
>  scroll.in.dates.pickers.mp4

at least you can view almost all data, there is still some part not well selectable

2023-12-15 08:43 UTC, allyoucanmap commented
@mahmoudadel54 @MV88 here the icon 
[date-time.zip](https://github.com/geosolutions-it/MapStore2/files/13683066/date-time.zip)

2023-12-15 09:05 UTC, MV88 requested changes
@mahmoudadel54 hi

things to do here
- [ ] use new icon made by @allyoucanmap 
- [ ] solve conflict
- [ ] try to fix at least the bottom part of the datepicker
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/cb602d03-ea6c-48b0-88bc-485746ddd3ed)

2023-12-21 15:49 UTC, MV88 commented
> @mahmoudadel54 hi
> 
> things to do here
> 
> * [x]  use new icon made by @allyoucanmap
> * [x]  solve conflict
> * [x]  try to fix at least the bottom part of the datepicker
>   ![image](https://private-user-images.githubusercontent.com/11991428/290777049-cb602d03-ea6c-48b0-88bc-485746ddd3ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDkwMTIsIm5iZiI6MTcwMzE0ODcxMiwicGF0aCI6Ii8xMTk5MTQyOC8yOTA3NzcwNDktY2I2MDJkMDMtZWE2Yy00OGIwLTg4YmMtNDg1NzQ2ZGRkM2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMTI1ZWUxOTQyNGQ3OGY2ZjMxYmI4NmQ3ZDM2ZjgzMGE4MmFlMzQzMzJlYTJmZjQ5Y2EwYmU0MjNmNzI2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AmV17lBmcJ63Hg_1Vcpg-cOAigRdGgRhMCvMtulZcaQ)

@tdipisa 
the third point here is not resolved and i tried locally to find an alternative fix but it could require some refactor effort and for the moment i'm going to put this in blocked. 

i'll also push some changes to a separate branch that will produce a similar result but which is incomplete
and not fully working
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/20ab3f1d-7319-4785-a840-7672167a2d31)

2024-01-14 23:28 UTC, mahmoudadel54 commented
> > @mahmoudadel54 hi
> > things to do here
> > 
> > * [x]   use new icon made by @allyoucanmap
> > * [x]   solve conflict
> > * [x]   try to fix at least the bottom part of the datepicker
> >   ![image](https://private-user-images.githubusercontent.com/11991428/290777049-cb602d03-ea6c-48b0-88bc-485746ddd3ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDkwMTIsIm5iZiI6MTcwMzE0ODcxMiwicGF0aCI6Ii8xMTk5MTQyOC8yOTA3NzcwNDktY2I2MDJkMDMtZWE2Yy00OGIwLTg4YmMtNDg1NzQ2ZGRkM2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMTI1ZWUxOTQyNGQ3OGY2ZjMxYmI4NmQ3ZDM2ZjgzMGE4MmFlMzQzMzJlYTJmZjQ5Y2EwYmU0MjNmNzI2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AmV17lBmcJ63Hg_1Vcpg-cOAigRdGgRhMCvMtulZcaQ)
> 
> @tdipisa the third point here is not resolved and i tried locally to find an alternative fix but it could require some refactor effort and for the moment i'm going to put this in blocked.
> 
> i'll also push some changes to a [separate branch](https://github.com/geosolutions-it/MapStore2/compare/master...MV88:MapStore2:9706_datetimepciker_refactor?expand=1) that will produce a similar result but which is incomplete and not fully working ![image](https://private-user-images.githubusercontent.com/11991428/292252625-20ab3f1d-7319-4785-a840-7672167a2d31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzQ3NjEsIm5iZiI6MTcwNTI3NDQ2MSwicGF0aCI6Ii8xMTk5MTQyOC8yOTIyNTI2MjUtMjBhYjNmMWQtNzMxOS00Nzg1LWE4NDAtNzY3MjE2N2EyZDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDIzMjEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTAwYTdmOTE0ZTBmMzAzMjIyZjJiOWRjMWJlMDY3ZTRjNDBkNGU1OGE4MjI2NjA1NWY1NDE4MjYzOWIzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PT2MUhGXShJjxcK_6dT7HJt62W9UshP0QkJX7F_4MeQ)
> 
> The refactor parts are
> 
> * [ ]  there will be three new components:
>   
>   * [x]  a DateTimePicker that will allow user to select a date only, a time only, a date and time
>   * [x]  a RangedDateTimePicker that will reuse the previous component to show the ranged mode
>   * [ ]  a new Time.jsx component that will allow to type or select an hour
>   * [ ]  otherwise we can maintain the old DateTimePicker and CustomDateTimePickerWithRange and refactor them later on
> * [ ]  for the time picker we can simply use a combobox and not current component,
>   
>   * [ ]  we can keep the selected value with background as primary or the default selected bg color we have, e.g
>     ![image](https://private-user-images.githubusercontent.com/11991428/295511622-14835786-38fb-496e-b181-221a54c58639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzQ3NjEsIm5iZiI6MTcwNTI3NDQ2MSwicGF0aCI6Ii8xMTk5MTQyOC8yOTU1MTE2MjItMTQ4MzU3ODYtMzhmYi00OTZlLWIxODEtMjIxYTU0YzU4NjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDIzMjEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOGM0OTQ4YTllYzUwMTg0NTk3NmNjZGRhNjY3MDZjOTNhMjM2OWU4ZWVkNTI0OGY5ZTQ0ODQzNTViNTgwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLLt8Kir0h-qJguSssaw3-KZy6kF-OqZ6aFVF8Q2tKI)
>   * [ ]  create a new component for the moment called Time in web\client\components\misc\datetimepicker
>   * [ ]  quickly check if this is applicable to the one in queryform
>   * [ ]  we have then check if clicks in and outside the container behaves correctly
>   * [ ]  we need to maintain the possibility to edit the value manually once selected from the combobox
> * [x]  in the case of datetime picker both picker must be visible from the start, so the overall style must be refined or adapted (like reducing paddings etc making it more compact than what is in the image above)
> * [x]  this means to avoid to show the vertical scrollbar as well
> * [ ]  when user clicks on time picker it should expand at the top if if space is not available
> * [x]  the date time picker will hide if user clicks outside the related container of the datetime picker


Hi @MV88 
I have tried to use Combobox component as you mentioned but it didn't work as expected so I tried to use popover component as in your POC branch and this is a demo demonstrating the UI improvements in pickers
Also I have fixed the issue of fixing the popover even if user makes some scroll in the UI like here if user opens date picker and wants to scroll into horizontal direction [it is in demo as well]


https://github.com/geosolutions-it/MapStore2/assets/58145645/71bdb4d3-0ba6-455e-b392-9628009bbc67

2024-01-15 17:22 UTC, MV88 requested changes
i have noticed these 
- [ ] ![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/db490d72-5b11-489b-a096-f526a9aaf5e1)
- [ ] reopening the combobox the selected hour is not visible
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/d4022671-4b00-43cf-8566-172ebb81dddb)
- [ ] editing year manually in the input field is is not aligned to the calendar
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/a934a1e1-ab89-4223-a32c-91bc1ad17ebc)

please better check how this tools can be used to spot these problems

2024-01-18 11:28 UTC, MV88 requested changes
- [ ] placeholder for time should be type a time to filter...
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/a01c32d7-5cbd-4d5d-babf-d2046d48a579)
- [ ] when passing from date time ranged to a single datetime app crashed
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/6ef6d091-75c6-4c03-9ff5-eb0d6c11724c)


https://github.com/geosolutions-it/MapStore2/assets/11991428/e442bf4e-3104-4184-8216-bb80b88d6a1d




- [ ] also you can enter 70 seconds and it's not parsed. but i think we can improve this in another pr

2024-01-19 09:59 UTC, MV88 requested changes
looks ok. a few changes here

2024-01-19 10:22 UTC, MV88 requested changes
- [x] there is an issue with the popover size when mode is changed in the calendar

https://github.com/geosolutions-it/MapStore2/assets/11991428/b21d4290-c960-42c2-ab93-ffa24f71df48

2024-01-22 15:57 UTC, tdipisa commented
@MV88 can you please proceed asap with the review?

2024-01-22 16:23 UTC, MV88 approved these changes

2024-01-22 16:23 UTC, merged

2024-01-22 16:24 UTC, MV88 commented
@ElenaGallo please test it in DEV using a date, time and date time layer like this map https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/28584

2024-01-22 17:26 UTC, ElenaGallo commented
Hi @mahmoudadel54, I only notice that some filters, in edit mode, are enabled
![1](https://github.com/geosolutions-it/MapStore2/assets/56537133/36a6045c-365e-4b57-9709-a88cb3ed029f)

**How to reproduce**
- Open the attribute table
- Click on Edit mode

2024-01-22 17:31 UTC, tdipisa commented
@ElenaGallo please open a new issue for the above and assign it to refer to @dsuren1. 
@dsuren1 that should be a quick fix to do. Thank you.

2024-01-23 05:43 UTC, dsuren1 commented
@ElenaGallo 
I believe this is an expected behavior. Kindly check this map in [QA](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/28584)
<img width="1984" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/248c7913-5de4-4e3c-804a-c267d801e203">

The only problem I see is that when the field is disabled, the operator dropdown should be disabled too, as some are not, from the screenshot you shared. Kindly report this in the new issue. Thanks!

2024-01-23 08:30 UTC, tdipisa commented
@dsuren1 that's effectively the reason why I've asked to open a new issue. Thank you for clarifying this anyway.

2024-01-23 08:40 UTC, ElenaGallo commented
@dsuren1 @tdipisa new issue here: https://github.com/geosolutions-it/MapStore2/issues/9901