#9739 & #9760: Fix - Dependency management of widgets
geosolutions-it/MapStore2 pull request #9803
Opened 2023-12-07 13:05 UTC by dsuren1

## Description
This PR attempts to fix the issue with the dependency management of widgets

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**
- #9739 
- #9760 

**What is the new behavior?**
- The dependencies are correctly formulated and enforce the original requirement of dependency of the widget
- Fixed counter widget doesn't set fallback value when the value is null/undefined
- Fixed Layer/Map multi-selection doesn't work on Mac

### Test data
`/dashboard/47595`
`/dashboard/47592`
`/dashboard/47714`

### Screenshot
<img width="1982" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/b6f5305a-e811-4355-85c8-f710e73188d4">

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2023-12-18 10:13 UTC, offtherailz requested changes
The fix works, anyway the code have to be a little reorganized and cleaned up, or it is diffcoult to read and maintain. 
Please follow my suggestions @dsuren1 . 

I'm asking this for master only I think.

2023-12-18 12:50 UTC, dsuren1 commented on web/client/plugins/Dashboard.jsx
> +                }
Not required, as dependency selection is only allowed on `map` and `table` and both are checked here

2023-12-18 16:00 UTC, dsuren1 commented
@offtherailz 
In case of new chart widget (not **saved yet**), when connecting to a transitive depedent widget, the chart view of the current chart widget in wizard will not show updated view (i.e excludes filters from dependent widget) but upon save and back to edit it shows updated chart view and works fine from there on as the chart should have an `id` which `dependenciesToWidget` enhancer requires when generating `dependenciesMap`. Is it behavior okay?

As part of this PR, I have removed the requirement of the presence of an`id` in the enhancer to allow all widget types to get updated when connecting to a transitive dependent widget (i.e before saving the current widget)

**Example**
Try creating a widget (chart/counter) and connect to the map of this dashboard (`/dashboard/47592`)

2024-01-15 14:30 UTC, offtherailz commented
> @offtherailz In case of new chart widget (not **saved yet**), when connecting to a transitive depedent widget, the chart view of the current chart widget in wizard will not show updated view (i.e excludes filters from dependent widget) but upon save and back to edit it shows updated chart view and works fine from there on as the chart should have an `id` which `dependenciesToWidget` enhancer requires when generating `dependenciesMap`. Is it behavior okay?
> 
> As part of this PR, I have removed just the requirement of the presence of an`id` alone in the enhancer to allow all widget types to get updated when connecting to a transitive dependent widget (i.e before the widget is saved for the first time)
> 
> **Example** Try creating a widget (chart/counter) and connect to the map of this dashboard (`/dashboard/47592`), observe the behavior with id and without id validation in `dependenciesToWidget` enhancer locally

@dsuren1 it looks correct the way you did, from the user point of view. The ID of the widget should not be required to be dependent, so also new widget while editing first time can have a consistent preview..

2024-01-15 15:34 UTC, offtherailz approved these changes

2024-01-15 15:34 UTC, merged

2024-01-15 15:45 UTC, tdipisa commented
@ElenaGallo please test in DEV and let us know. there are 2 issues connected to this PR and one of them is also for 2023.02.02

2024-01-15 17:27 UTC, ElenaGallo commented
Test passed, @dsuren1 please backport to 2023.02.xx. Thanks

2024-01-15 17:31 UTC, tdipisa commented
@ElenaGallo probably nothing to be backported for this. I'm waiting confirmation from @dsuren1.

2024-01-16 04:38 UTC, dsuren1 commented
@tdipisa You are right. This fix doesn't need to be backported, a fix without traces has already been merged to [stable](https://github.com/geosolutions-it/MapStore2/pull/9804)

2024-01-16 08:34 UTC, tdipisa commented
@dsuren1 thank you for the confirmation.