Fix #8579 Review showElevation property of MousePosition plugin
geosolutions-it/MapStore2 pull request #9819
Opened 2023-12-15 13:47 UTC by allyoucanmap

## Description

This PR introduces a new type of layer called `elevation` to get height information to display in the mouse position plugin. This split the concept of terrain for visualization and elevation as data information.

In particular this note included in the documentation:

> Note that in the Cesium 3D viewer all the heights are relative to the WGS84 ellipsoid while usually locally DTM/DEM file could have an elevation value relative to the mean sea level (MSL). So with this new layer it's possible to have a terrain layer with the correct WGS84 ellipsoidal height while querying the mouse position with a MSL height.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x]  Minor changes to existing features

## Issue

**What is the current behavior?**

#8579

**What is the new behavior?**

Introduction of a new layer of type elevation

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

## Other useful information

2023-12-19 16:11 UTC, offtherailz commented on docs/developer-guide/mapstore-migration-guide.md
> +The wms layer with useForElevation property is deprecated and a `elevation` layer introduced in substitution.
```suggestion
The wms layer with `useForElevation` property is deprecated and a `elevation` layer introduced in substitution.
```

2023-12-19 16:45 UTC, offtherailz requested changes
I updated the documentation to make it more understandable. Please take a look at my changes.

I wasn't able to test it: 

![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/626f6ed9-669c-41d1-97b0-51e3ad9e79a9)

Context used: 
[additionalLayers-new-context.json](https://github.com/geosolutions-it/MapStore2/files/13718199/additionalLayers-new-context.json)

Did I missed something?

2023-12-21 08:50 UTC, allyoucanmap commented
@offtherailz here a working context: [elevation-layer-context.json](https://github.com/geosolutions-it/MapStore2/files/13739247/elevation-layer-context.json)

2024-01-08 14:20 UTC, offtherailz approved these changes

2024-01-08 14:20 UTC, merged

2024-01-08 14:20 UTC, offtherailz commented
@ElenaGallo, could you please test this on  DEV (as well as deployed) ? Thank you