#9825: Add an config option to enable mapInfo highlight by default
geosolutions-it/MapStore2 pull request #9829
Opened 2023-12-19 06:23 UTC by mahmoudadel54

## Description
This PR enables mapInfo highlight in identify by default if the option 'identifyHighlight' is added to config file.
The PR includes:
- Adding an option called "identifyHighlight" to enable/disable mapInfo highlight by default in localConfig file
- implement initiate highlight value based on the added option and the default is 'false'
- write unit tests based on change

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
https://github.com/geosolutions-it/MapStore2/issues/9825

**What is the current behavior?**
#9825 

**What is the new behavior?**
Now if the config option 'identifyHighlight' is defined by true, the mapInfo highlight in identify side bar will be active by default.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

2023-12-20 17:38 UTC, MV88 requested changes
it works, but please refactor this by reusing the INIT_PLUGIN action

generally when there is a cfg prop that needs to initialize the state and then change due to user actions we follow this approach
- only when plugin mounts (where connect is ) we call an onMount onInit action
- in the reducer we initialize the configuration
- we then user another action to change a specific prop value and a selector to fetch the value

Also please remember to avoid touching localConfig.json if not needed. undefined or null are falsy values as well, and it's better not not list props in cfg if not needed and use the default value associated to it at plugin level

2023-12-20 17:38 UTC, MV88 commented on web/client/configs/localConfig.json
> +                    "identifyHighlight":false,
no need to alter this

2023-12-20 17:38 UTC, MV88 commented on web/client/plugins/Identify.jsx
> + * @prop cfg.identifyHighlight {boolean} the highlight feature button will be activated by default if true
maybe we can call the prop highlightEnabledFromTheStart

2023-12-20 17:38 UTC, MV88 commented on web/client/plugins/Identify.jsx
> +        initiateOrResetHighlight,
rename to setHighlightFeatures

2024-01-09 17:05 UTC, MV88 approved these changes

2024-01-09 17:05 UTC, merged

2024-01-09 17:08 UTC, MV88 commented
@ElenaGallo please test in DEV using a context nad customizing the Cfg of Identify plugin with "highlightEnabledFromTheStart": true

2024-01-09 17:10 UTC, tdipisa commented
@ElenaGallo let us know for the backport

2024-01-11 09:36 UTC, ElenaGallo commented
Test passed, @mahmoudadel54 please backport to 2023.02.xx. Thanks

2024-01-11 10:00 UTC, mahmoudadel54 commented
> Test passed, @mahmoudadel54 please backport to 2023.02.xx. Thanks

Backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/9871