Fix #9892 thumb max size filter restored
geosolutions-it/MapStore2 pull request #9893
Opened 2024-01-17 14:34 UTC by MV88

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #9892

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-01-17 17:11 UTC, allyoucanmap requested changes

2024-01-17 17:11 UTC, allyoucanmap commented on web/client/components/misc/Thumbnail.jsx
> +        const imageSize = files?.[0]?.size;
I would propose a different approach, a new prop called `checkOriginalFileSize`, if true we can check directly here without performing the resize of the image, something like this:

Note: checkOriginalFileSize should be set true only for the background dialog

```js
const imageSize = files?.[0]?.size;
if (checkOriginalFileSize && imageSize >= maxFileSize) {
    return onError(['SIZE'], files);
}
```

This should restore previous behaviour and it should not affect other thumbnails that are not using the original image size limit.

2024-01-17 17:11 UTC, allyoucanmap commented on web/client/components/misc/Thumbnail.jsx
>                  ], files);
Based on previous comment this should be restored as before

2024-01-18 08:41 UTC, tdipisa requested changes

2024-01-18 08:41 UTC, tdipisa commented on web/client/components/misc/Thumbnail.jsx
> + * @prop {boolean} checkOriginalFileSize if tru it checks maxFileSize compared to source image
```suggestion
 * @prop {boolean} checkOriginalFileSize if true it checks maxFileSize compared to source image
```

2024-01-18 08:44 UTC, allyoucanmap approved these changes

2024-01-18 08:47 UTC, tdipisa approved these changes

2024-01-18 08:55 UTC, merged

2024-01-18 08:55 UTC, MV88 commented
@ElenaGallo please test it in DEV