fix importing geojson files on firefox on linux (#9912)
geosolutions-it/MapStore2 pull request #9913
Opened 2024-01-25 13:04 UTC by landryb

for some reason mimetype is detected as application/geo+json

## Description
cf #9912

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#9912

**What is the new behavior?**

importing geojson files in the 'add data' & 'import data' item of profile tool passes mimetype check

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

2024-01-25 13:12 UTC, landryb commented
something is still wrong nevertheless, because trying various geojson files in the profile tool import line item, i mostly get *The provided line is outside the profile coverage* error messages - while they *are* on the DEM coverage, when reprojected.

2024-01-25 13:47 UTC, tdipisa commented
Hi @landryb, thank you so much for your contribution. Is it possible for you to check failing unit tests?

2024-01-25 14:05 UTC, landryb commented
> Hi @landryb, thank you so much for your contribution. Is it possible for you to check failing unit tests?

well i've seen the failure and it is in some cesium-related code, and the error message `{"message":"Couldn't find a repository matching this job.","error":true}` doesnt mean much to me, so i doubt its actually related to the PR. i dunno if one can retrigger the github action to check..

2024-01-25 14:05 UTC, landryb commented
> something is still wrong nevertheless, because trying various geojson files in the profile tool import line item, i mostly get _The provided line is outside the profile coverage_ error messages - while they _are_ on the DEM coverage, when reprojected.

for this, cf #9914

2024-02-13 11:56 UTC, MV88 requested changes
Hello @landryb 
i'll report here my findings:

Actually there are some issues even before reaching longitudinal profile.
in particular we do not yet support import of geojson files that are not reprojected to EPSG:4326.

see here, trying to import [test2154.json](https://github.com/geosolutions-it/MapStore2/files/14052330/test2154.json) on a map with is already using EPSG:2154 
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/1edb8382-0cfc-4d8e-9818-65a9387220d7)
the bbox is assuming to be in 4326 here
https://github.com/geosolutions-it/MapStore2/blob/593c4d5eeb8d3615d0b6ce7324ef70960c0c44c9/web/client/utils/LayersUtils.js#L616

also because [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/longitudinalProfile/enhancers/processFile.js#L56) the projection is expected to be in **map.projection** which something related to mapstore map.json files 

in fact the UI shows this warning
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/dba73b50-d468-45f1-b9ff-6042f07d9f9d)

Please try to convert the json file to EPSG:4326 and re-test.

Aside from that I have tested using master branch importing a **file.geojson** or **file.json** and they both are recognized as **application/json** so if the geojson is valid (only 4326) I'm able to import it inside the longitudinalProfile tool

i'm using this for testing (remove .txt) in [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/Longitudinal)
 [a geosjon line - FC.geojson.txt](https://github.com/geosolutions-it/MapStore2/files/14261178/a.geosjon.line.-.FC.geojson.txt)

i think this PR is not needed tbh

2024-02-19 10:32 UTC, landryb commented
@mv88 did you try with firefox on linux ? i get your comments are about the geojson projection, while this PR/issue isnt about this topic, but about the detected mimetype..

2024-03-29 17:39 UTC, MV88 requested changes
@landryb hi, sorry for being late
I had the time to better review this and indeed .geojson  are recognized as geo-json mime type, but in order to better support it you need also to include changes here for the normal map import tool

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/import/dragZone/enhancers/processFiles.jsx#L105

adding `|| type === 'application/geo+json'`

additionally there are some tests that are failing, do you have time to have a look at that?

i have tested using these
[geosol training.zip](https://github.com/geosolutions-it/MapStore2/files/14807186/geosol.training.zip)
keep in mind that for now geojson needs to be projected in 4326 to work fine in longitudinal profile tool for example

2025-01-21 15:02 UTC, landryb commented
i think the `application/geo+json` thing for geojson import has been fixed with #10081 & #10082 (i'll have to retest that), but i guess this is still valid for the longitudinal profile tool.

2025-01-22 10:05 UTC, MV88 approved these changes

2025-01-22 10:25 UTC, merged

2025-01-22 10:25 UTC, MV88 commented
@ElenaGallo please test it in DEV