Update mapstore-migration-guide.md
geosolutions-it/MapStore2 pull request #9926
Opened 2024-01-29 11:29 UTC by offtherailz

## Description

In this migration guidelines the replacement of `BurgerMenu` with `SidebarMenu` is not reported. Here the correct instructions.  

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Doc

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-01-30 09:01 UTC, MV88 requested changes

2024-01-30 09:01 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
> +- edit `locaConfig.json` `plugins.dashboard` section
```suggestion
- edit `localConfig.json` `plugins.dashboard` section
```

2024-03-04 16:15 UTC, MV88 commented on docs/developer-guide/mapstore-migration-guide.md
> +},
what is this Menu?

2024-03-04 16:17 UTC, MV88 requested changes
are you sure that Menu is needed?

Also burger menu should be already removed from previous iteration., but maybe is better to remind this to the users

2024-03-04 17:39 UTC, offtherailz commented on docs/developer-guide/mapstore-migration-guide.md
> +  "name": "Menu",
```suggestion
  "name": "SidebarMenu",
```

2024-03-06 08:45 UTC, MV88 approved these changes

2024-03-06 08:45 UTC, merged