Update User Guide - Unadvertised resources
geosolutions-it/MapStore2 pull request #9976
Opened 2024-02-15 15:20 UTC by ElenaGallo

## Description

Add Unadvertised option on [Resources properties](https://mapstore--9976.org.readthedocs.build/en/9976/user-guide/resources-properties/) section

2024-03-11 13:57 UTC, tdipisa requested changes
That's good. Only a few corrections in form of suggestions that you can directly apply from github UI.

2024-03-11 13:57 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +* Enable the **Unadvertised** option to makes the resource owner or the admin the only one who can see and search the resource on the [Home Page](home-page.md) or in the [Map Catalog](map-catalog.md)
```suggestion
* Enable the **Unadvertised** option to makes the owner of the resource or the MapStore admin the only ones who can see and search that resource in the [Home Page](home-page.md) or in the [Map Catalog](map-catalog.md) tool.
```

2024-03-11 13:57 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +* Add a **Permission** rule
Please put a link to the related section.

2024-03-11 13:57 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +While an admin user can also view who created the resource and the last user who modified it. An example in the image below:
```suggestion
Admin users can also see who created and modified the resource. An example in the image below:
```

2024-03-11 13:57 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +Only for resources of type map and dashbaord, it is possible to add details to the resource. This is useful to associate some information to the resource or an overview description of its content. In
```suggestion
Only for resources of type _map_ and _dashbaord_, it is possible to add details as additional information in form of descriptive content for the resource itself. This is useful to associate some information to the resource or an overview description of its content. In this case the *Edit properties* window is the following:
```

2024-03-11 13:57 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +With a click on the **Add new details** button <img src="../img/button/add_details_button.jpg" class="ms-docbutton"/> it opens a panel where the user can write the details of the resource.
```suggestion
With a click on the **Add new details** button <img src="../img/button/add_details_button.jpg" class="ms-docbutton"/> a panel opens and the user can write the details of the resource.
```

2024-03-11 13:57 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +* Enable the **Show at startup** <img src="../img/button/show-at-starup-button.jpg" class="ms-docbutton"/> button. If active, as soon as the user opens the resources, the details panel is visualized.
```suggestion
* Enable the **Show at startup** <img src="../img/button/show-at-starup-button.jpg" class="ms-docbutton"/> button. If active, when the user opens a resources with details defined, these are visualized in a descriptive panel.
```

2024-03-12 12:04 UTC, tdipisa requested changes

2024-03-12 12:04 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +* * Enable the **Unadvertised** option to makes the owner of the resource or the MapStore admin the only ones who can see and search that resource in the [Home Page](home-page.md) or in the [Map Cata
```suggestion
* * Enable the **Unadvertised** option to make the owner of the resource or the MapStore admin the only ones who can see and search that resource in the [Home Page](home-page.md) or in the [Map Catalog](map-catalog.md) tool.
```

2024-03-12 12:04 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +Once a resource is saved, the *Edit properties* panel shows the creation and last modification date. An example in the image below:
```suggestion
Once a resource is saved, the *Edit properties* panel shows the creation and the last modification dates. An example in the image below:
```

2024-03-12 12:04 UTC, tdipisa commented on docs/user-guide/resources-properties.md
> +Only for resources of type *map* and *dashboard*, it is possible to add details as additional information in form of descriptive content for the resource itself. This is useful to associate some info
```suggestion
Only for resources of type *map* and *dashboard*, it is possible to add details as additional information in form of descriptive content for the resource itself. This is useful to associate some information to the resource and provide an overview of its content. In this case the *Edit properties* window is the following:
```

2024-03-12 12:06 UTC, tdipisa commented
There is also a [failing check on ESLINT](https://github.com/geosolutions-it/MapStore2/actions/runs/8247531208/job/22556153689?pr=9976)

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/994cac67-9b8f-4164-866a-b9b800a81fa7)

Please check and fix. Thank you @ElenaGallo

2024-03-12 17:09 UTC, offtherailz commented
@ElenaGallo could you please re-add the rule and fix the indentation of the line.

`docs/user-guide/resources-properties.md` is only the matter of an indentation.

2024-03-12 17:16 UTC, offtherailz commented on .markdownlint.json
> +  "ul-indent":false,
```suggestion
```

2024-03-12 17:17 UTC, offtherailz commented on docs/user-guide/resources-properties.md
> +* * Enable the **Unadvertised** option to make the owner of the resource or the MapStore admin the only ones who can see and search that resource in the [Home Page](home-page.md) or in the [Map Catal
```suggestion
* Enable the **Unadvertised** option to make the owner of the resource or the MapStore admin the only ones who can see and search that resource in the [Home Page](home-page.md) or in the [Map Catalog](map-catalog.md) tool.
```

2024-03-13 16:16 UTC, tdipisa approved these changes

2024-03-13 16:16 UTC, tdipisa commented
@ElenaGallo please backport to 2024.01.xx. Thank you.

2024-03-13 16:16 UTC, merged